### ISSUE TITLE
Publish-Script add the private functions into the 'Tag' field

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PowerShellGetv2#10]
This [function](https://github.com/LaurentDardenne/ProjectTools/blob/master/Edit-String.ps1) contains a lots of private functions : 

``` powershell
    Edit-String   # MAIN function
    New-Exception
    Test-InputObjectProperty
    ConvertTo-String
    Convert-DictionnaryEntry
    New-ObjectReplaceInfo
    isParameterWellFormed
    BuildList
```

They are all present into the 'Tags' field :

```
**Tags**
Replace Regex Template String Edit PSScript PSIncludes_Function PSFunction_Edit-String
PSFunction_New-Exception PSFunction_Test-InputObjectProperty PSFunction_ConvertTo-String PSFunction_Convert-DictionnaryEntry 
PSFunction_New-ObjectReplaceInfo PSFunction_isParameterWellFormed PSFunction_BuildList
PSCommand_Edit-String PSCommand_New-Exception PSCommand_Test-InputObjectProperty
PSCommand_ConvertTo-String PSCommand_Convert-DictionnaryEntry 
PSCommand_New-ObjectReplaceInfo PSCommand_isParameterWellFormed PSCommand_BuildList 
```

Windows Seven
Powershell v 5.0.10586.117
PackageManagement 1.1.0.0

**Comment by ThomasNieto** [comment]
@LaurentDardenne Can you clarify the request? Are you saying the `Publish-Script` is currently adding private functions as tags in the NuGet package? Or are you saying it doesn't do that currently and you would like that be a added as a feature?

If you're referring to the former I would like you to see if it happens on the latest version of PowerShellGet. If it's the latter then I would like a little more information why it would be useful to add private functions as tags.

**Comment by LaurentDardenne** [comment]
Hi,
_Are you saying the Publish-Script is currently adding private functions as tags in the NuGet package?_
Yes. With [MyGet](https://www.myget.org/feed/ottomatt/package/nuget/Edit-String) and [here](https://www.myget.org/feed/ottomatt/package/nuget/Log4Posh)
I must test again with the latest version.
