### ISSUE TITLE
Install-Package Azure or AzureRM errors on Windows 10

### ISSUE THREAD

**Issue by eanders-ms** [PowerShell/PowerShellGetv2#100]
Hello, I hope I'm in the right place. I'm attempting to install the latest Azure PowerTools and getting this error:

![image](https://cloud.githubusercontent.com/assets/12176807/23771241/1d0d3be6-04cb-11e7-8770-c993173fa645.png)

The same happens for `Install-Module AzureRM -Force` (I'm unsure the difference).

How can I get it to install?

```
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by bmanikm** [comment]
@eanders-MS 
Please ensure that you have installed the latest Windows updates on your machine. Alternatively, the latest version of PowerShellGet can be installed from PSGallery using the steps mentioned [here](https://github.com/PowerShell/PowerShellGet#get-the-latest-version-from-powershell-gallery).

After installing the latest version, open a new PS Console and try to install the AzureRM module with -Verbose -Debug switch parameters. Please provide debug output if your are unable to install it.

**Comment by bmanikm** [comment]
This issue got fixed in the latest version of PowerShellGet.
