### ISSUE TITLE
Publish-Module does not propagate Credentials to sub-functions

### ISSUE THREAD

**Issue by gogbg** [PowerShell/PowerShellGetv2#103]
Publish-Module cannot verify if Dependant Modules are already present in cases where PSReposity should be accessed with alternate credential.

## Expected Behavior
If Publish-Module is been run with "Credential" parameter it should propagate the provided Credentials to the other functions that are doing validations against the PSRepository.
The suggested solution is to detect if "Credential" parameter is being supplied and propagate it to the sub-functions.

## Current Behavior
When you try to publish a module that has dependencies defined in it`s ".psd1" file it fails to properly detect if they are already present on the PSRepository when the following conditions are present:
- Alternative credentials are being provided using the "Credential" parameter
- The Credentials supplied are different from the credentials of the user running the process.

## Possible Solution
Implement optional Credential parameter to the following functions:
- Publish-PSArtifactUtility
- Get-ModuleDependencies
- ValidateAndGet-RequiredModuleDetails

and detect and propagate the Credential parameter if it have been supplied.

## Steps to Reproduce (for bugs)
1. Publish-Module -Name testmodule -Repository LocalPsRepo -NuGetApiKey 123 -Credential (Get-Credential)
2. Provide Credentials different from the one used to run the PowerShell process.

## Your Environment

> $PSVersionTable

Name                           Value                                                                                                       
----                           -----                                                                                                       
PSVersion                      5.0.10586.117                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                     
BuildVersion                   10.0.10586.117                                                                                              
CLRVersion                     4.0.30319.42000                                                                                             
WSManStackVersion              3.0                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                         
SerializationVersion           1.1.0.1                                                                                                     

> Get-Module -ListAvailable PowerShellGet,PackageManagement

ModuleType Version    Name                                ExportedCommands                                                                 
---------- -------    ----                                ----------------                                                                 
Script     1.1.3.0    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}           
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}           
Script     1.1.2.0    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}                     
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}                     

> Get-PackageProvider

> Get-PackageProvider -ListAvailable
```

**Comment by dotps1** [comment]
I found this as well, I created a PR that has been accepted, it just has not be published to production AFAIK.

https://github.com/PowerShell/PowerShellGet/pull/93

**Comment by gogbg** [comment]
I`ve also submitted PR before seeing your post :)
