### ISSUE TITLE
Register-PSRepository throws exception when run inside Windows Server container

### ISSUE THREAD

**Issue by pcgeek86** [PowerShell/PowerShellGetv2#106]
Problem Overview
--------------

We're trying to register an internal / private NuGet PowerShell module repository inside of a Windows Server Container. When we attempt to register the repository, an exception is thrown by the `Register-PSRepository` command. The repository can be registered properly outside of a Windows Server Container.

Steps to reproduce
------------------

1. Create a `Dockerfile` based on `microsoft/windowsservercore`
2. Run `Register-PSRepository` command inside `Dockerfile`

### build.cmd

```
cd "%~dp0"

powershell.exe -Command Save-Module -Name PowerShellGet -Path ./

docker build --tag amazon/redacted --file Dockerfile --no-cache .
```

### Dockerfile

```
FROM microsoft/windowsservercore

MAINTAINER Trevor Sullivan <tsulli@amazon.com>

RUN mkdir c:\Amazon

COPY [ "PackageManagement", "c:/Program Files/WindowsPowerShell/Modules/PackageManagement"]
COPY [ "PowerShellGet", "c:/Program Files/WindowsPowerShell/Modules/PowerShellGet"]
COPY redacted.ps1 c:\Amazon

RUN powershell.exe -ExecutionPolicy Bypass -File c:\Amazon\redacted.ps1

ENTRYPOINT powershell
```

Expected behavior
-----------------

Container builds successfully, without errors.

Actual behavior
---------------

Exception is thrown:

```
Set-Variable : Object reference not set to an instance of an object.
At C:\Program
Files\WindowsPowerShell\Modules\PowerShellGet\1.1.2.0\PSModule.psm1:4077
char:13
+             Set-Variable -Name selectedProviderName -value $null -Sco ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-Variable], NullReferenceE
   xception
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShe
   ll.Commands.SetVariableCommand

PackageManagement\Register-PackageSource : Unhandled Exception - Message:'One
or more errors occurred.' Name:'AggregateException' Stack Trace:'   at
System.Threading.Tasks.Task.ThrowIfExceptional(Boolean
includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean
waitCompletionNotification)
   at Microsoft.PowerShell.PackageManagement.Cmdlets.RegisterPackageSource.Proc
essRecordAsync()
   at Microsoft.PowerShell.PackageManagement.Cmdlets.AsyncCmdlet.<>c__DisplayCl
ass83_0.<AsyncRun>b__0()'
At C:\Program
Files\WindowsPowerShell\Modules\PowerShellGet\1.1.2.0\PSModule.psm1:4211
char:17
+ ...     $null = PackageManagement\Register-PackageSource @PSBoundParamete ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...erPackageSo
   urce:RegisterPackageSource) [Register-PackageSource], Exception
    + FullyQualifiedErrorId : UnhandledException,Microsoft.PowerShell.PackageM
   anagement.Cmdlets.RegisterPackageSource
```

### redacted.ps1

```
Install-PackageProvider -Name NuGet -MinimumVersion 2.8.3 -Force
$Parameters = @{
    Name = 'customrepo'
    SourceLocation = 'http://website.com/'
    PublishLocation = 'http://website.com/api/v2/package'
    InstallationPolicy = 'Trusted'
    PackageManagementProvider = 'NuGet'
}
Register-PSRepository @Parameters
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Cheers,
Trevor Sullivan

**Comment by pcgeek86** [comment]
Moved from https://github.com/PowerShell/PowerShell/issues/3412

**Comment by Krishna-Vutukuri** [comment]
@pcgeek86 I am able to successfully build a container using these instructions in my test environment.  Here is the PSVersionTable on my machine:

Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

and here is the output I received:

C:\temp\PowerShellGet-106>docker build --tag amazon/redacted --file Dockerfile --no-cache .
Sending build context to Docker daemon 3.129 MB
Step 1/8 : FROM microsoft/windowsservercore
 ---> 4d83c32ad497
Step 2/8 : MAINTAINER Trevor Sullivan <tsulli@amazon.com>
 ---> Running in 2a7b2ade62d2
 ---> 1807d3fc9047
Removing intermediate container 2a7b2ade62d2
Step 3/8 : RUN mkdir c:\Amazon
 ---> Running in b2300d11f142
 ---> e21f120f0e06
Removing intermediate container b2300d11f142
Step 4/8 : COPY PackageManagement c:/Program Files/WindowsPowerShell/Modules/PackageManagement
 ---> c77f89a76c4a
Removing intermediate container ec1d2ea42678
Step 5/8 : COPY PowerShellGet c:/Program Files/WindowsPowerShell/Modules/PowerShellGet
 ---> f8abcb5ca184
Removing intermediate container 2902f93b9776
Step 6/8 : COPY redacted.ps1 c:\Amazon
 ---> d23d27f77d2b
Removing intermediate container b7d43b62a77e
Step 7/8 : RUN powershell.exe -ExecutionPolicy Bypass -File c:\Amazon\redacted.ps1
 ---> Running in 1ac9282003c7

Name                           Version          Source           Summary
----                           -------          ------           -------
nuget                          2.8.5.208        https://onege... NuGet provi...


 ---> 9560320ae869
Removing intermediate container 1ac9282003c7
Step 8/8 : ENTRYPOINT powershell
 ---> Running in 27e9456fe684
 ---> 2ca6b341b13a
Removing intermediate container 27e9456fe684
Successfully built 2ca6b341b13a

output from docker run -ti amazon/redacted

Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\> get-psrepository

Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2/
customrepo                Trusted              https://www.website.com/
