### ISSUE TITLE
Update-ScriptFileInfo and New-ScriptFileInfo do not update ScriptFileInformation as described

### ISSUE THREAD

**Issue by CermakPOI** [PowerShell/PowerShellGetv2#138]
## Expected Behavior

The Script content should be extended with the provided ScriptFileInformation (Description, Releasenotes,...)

## Current Behavior

PS C:\WINDOWS\system32> New-ScriptFileInfo -Description "Script file description." -PassThru
This removes all previous Script content!

PS C:\WINDOWS\system32> Update-ScriptFileInfo -Description "Script file description."
Error System.InvalidOperationException: Unable to add PSScriptInfo to the script file 'Z:\10_Powershell\02_Dev\10_ISCOMxx\ISCOM03P\POISQL-GHServerDataPorter_20170608_0810.ps1'. You can use the New-ScriptFileInfo cmdlet to add the metadata to the existing script file.
   bei System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)

## Your Environment

```PowerShell
5.1.14393.1198
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.1198
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1198
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

> Get-Module -ListAvailable PowerShellGet,PackageManagement
PS C:\> Get-Module -ListAvailable PowerShellGet,PackageManagement


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.4.0    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...
Script     1.1.3.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}

> Get-PackageProvider -ListAvailable
Name                     Version          DynamicOptions
----                     -------          --------------
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
NuGet                    2.8.5.209        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag...
NuGetProvider            2.8.5.208
PowerShellGet            1.1.3.1          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, ...
PowerShellGet            1.0.0.1
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent

**Comment by bmanikm** [comment]
@CermakPOI 
By default, New-ScriptFileInfo should not replace the existing file, unless you specify -Force.
Have you tried to use Update-ScriptFileInfo with **-Force** switch for the existing script file which was not created using New-ScriptFileInfo?

**Comment by CermakPOI** [comment]
Update-ScriptFileInfo with these parameters
```
		Path		    = $FileScript
		CompanyName	 = "MyCompany"
		Copyright	   = "(c) 2017. All rights reserved."
		RequiredModules = 'POI.PS.Library'
		Version	  = $NewVersion
		Author	   = $Author
		Description  = $ScriptDescription
		ReleaseNotes = $NewReleaseNotes
		Force = $true
		PassThru = $true

```
Result:

```
Error System.InvalidOperationException: Unable to add PSScriptInfo to the script file 'D:\MyScript.ps1'. You can use the New-ScriptFileInfo cmdlet to add the metadata to the existing script file.
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)

```


I think the Problem is the try-block starting in line 5505 in C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.1.3.1\PSModule.psm1

If something goes wrong in this try, there is no catch. 
SFI is my short for ScriptFileInfo.

I have a Workaround, i create the SFI manually for an existing file if SFI not exist:
```
$SFI = Test-ScriptFileInfo -Path $FileScript 
	if (-not $SFI) {
		$NewGUID = [System.Guid]::NewGuid()
		$PSSFI = @"

<#PSScriptInfo

.VERSION $MyVersion

.GUID $NewGUID

.AUTHOR $Author

.COMPANYNAME 

.COPYRIGHT 

.TAGS 

.LICENSEURI 

.PROJECTURI 

.ICONURI 

.EXTERNALMODULEDEPENDENCIES 

.REQUIREDSCRIPTS 

.EXTERNALSCRIPTDEPENDENCIES 

.RELEASENOTES
Versions	Date	Author	Description

.PRIVATEDATA 

#>

"@
		
		Write-Verbose "Adding PSScriptInfo in front of File '$FileScript'"
		try {
				$FileContentOriginal = (Get-Content -Path $FileScript  -ErrorAction SilentlyContinue | out-string).trim()
		} catch {
		}
		"$PSSFI`r`n$FileContentOriginal" | Set-Content -Path $FileScript
		
		if (-not $ReleaseNotes) {
			$ReleaseNotes = 'Initial Release'
		}
		try {
			$SFI = Test-ScriptFileInfo -Path $FileScript -ErrorAction Stop
		} catch {}
	}
```

After that i can work with Update-ScriptFileInfo to add my data.

**Comment by bmanikm** [comment]
@CermakPOI Source file gets replaced only when the temp file is correct with the script info and validated. Please take a look at https://github.com/PowerShell/PowerShellGet/blob/development/PowerShellGet/PSModule.psm1#L5673 .

Please note that 
- New-ScriptFileInfo cmdlet is for creating a new script file with the script info,
- Update-ScriptFileInfo is mainly for the script files with existing script info. 
- Update-ScriptFileInfo with -Force tries to add the script info to the existing script file which was not created using New-ScriptFileInfo. If there is any error that means your existing script file might be having some encoding or other issues.

To investigate further, could you please provide the repro script file?

**Comment by CermakPOI** [comment]
I can send you the script per PM/email.

**Comment by bmanikm** [comment]
@CermakPOI, Could you please send it in PM on Gitter? My Gitter id is bmanikm. [![Join the chat at https://gitter.im/PowerShell/PowerShellGet](https://badges.gitter.im/PowerShell/PowerShellGet.svg)](https://gitter.im/PowerShell/PowerShellGet?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by bmanikm** [comment]
Closing this as the repro script is not available.
