### ISSUE TITLE
Provide means to 'rate' gallery items

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PowerShell/PowerShellGetv2#146]
Hi all!

Not sure where to post this.  The [uservoice item](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/13799814-the-powershell-gallery-should-have-a-rating-system) is closed and seems dead, despite the solution not appearing to address the original request.

[This reddit thread](https://www.reddit.com/r/PowerShell/comments/6l92ql/powershell_modules_frameworks_sticky/) on popular modules is a good example of why this would be helpful.  At the moment, there's no way to say _show me high quality PowerShell modules_.  None.  Yeah, you can google around, find various community references, but this is inefficient and painful.

Any chance we could revisit some sort of [feedback mechanism on the PowerShell Gallery](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/13799814-the-powershell-gallery-should-have-a-rating-system)?

@jaykul's responses seem like solid suggestions.  Paraphrased:

* Don't rely on social media.  Please.
* Tie to same auth as PowerShell Gallery
* Allow users to star a module (like GitHub)
* Allow users to list modules they've starred (via web, api/PowerShellGet, ideally)
* Allow users to create named lists of PowerShell modules ([qualify these by user](https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/15729702-provide-means-to-qualify-script-names-to-avoid-con), e.g. wframe/user-management)
* For each module, allow sorting on (via web, api/PowerShellGet)...
  * Stars
  * Count of lists including this module (1 user with module in 2 lists = count 2)
  * Count of users with at least one list including this module (1 user with module in 2 lists = count 1)

Until then, you'll get various folks trying to set up alternatives to what should (IMHO) be built in.

At the very least, let us star modules and sort by stars.  Social media is not viable for this (see various comments).

Cheers!

**Comment by bmanikm** [comment]
Cc: @JKeithB

**Comment by edyoung** [comment]
See https://github.com/PowerShell/PowerShellGallery/issues/33 - I will close this one, please add any other proposals/comments there
