### ISSUE TITLE
Means to aquire metadata of Gallery Item

### ISSUE THREAD

**Issue by lipkau** [PowerShell/PowerShellGetv2#161]
## Expected Behavior
I would like to show information from my module that is publish in the gallery on my homepage - in particular the # of downloads of my module.
I would like to query this kind of information using javascript.

## Current Behavior
It is currently not possible to do this

## Possible Solution
create a rest interface with which this can be done
`GET /api/rest/:module/downloads`

**Comment by bmanikm** [comment]
Cc: @JKeithB @KrishnaV-MSFT

**Comment by ghost** [comment]
Interesting proposal. Question: would a REST API that provided that data be sufficient? 
We will be monitoring this to see how many reactions it gets from others.

**Comment by lipkau** [comment]
Yes. It would be sufficient for me :-)

**Comment by ghost** [comment]
FYI: This information IS available from Find-Module. The AdditionalMetadata property contains VersionDownloadCount. Of course, that's per version, which means you would need to sum the information across the versions you care about.

**Comment by lipkau** [comment]
Thank you for pointing that out, @JKeithB .
But my intention was to use that with an ajax query for a webpage; thus `Find-Module` doesn't help me

**Comment by edyoung** [comment]
Everything Find-Module goes boils down to REST api queries. Try GET /api/v2/FindPackagesById()id='powershellget' and look at the XML in the response for VersionDownloadCount

**Comment by lipkau** [comment]
Cool!
thanks
