### ISSUE TITLE
Specifying version requirements for REQUIREDSCRIPTS

### ISSUE THREAD

**Issue by wooseung-sim** [PowerShell/PowerShellGetv2#164]
# Expected Behavior

For some reasons, scripts or modules might require specific versions of dependency modules and/or scripts. And publish module/script should validate and packaging it with proper dependency version condition.

## Current Behavior
Script/Module author can specify version requirements for dependency modules, but cannot for dependency script, as format of REQUIREDSCRIPTS accepts only script names.

## Possible Solution
Having nuspec version format support on REQUREDSCRIPTS format.
Like, 
>.REQUIREDSCRIPTS \<ScriptName\>:\<Version\>
Format in version
Parentheses '(', ')' exclusive, Brakets '[', ']' inclusive
Between parentheses/brackets : \<MinVersion\>,\<MaxVersion\>

Need to update ValidateAndGet-ScriptDependencies cmdlet.

## Context
Notice that this cannot resolve any version conflictions in dependencies. But it is already existing issue even for modules. So it can be separated issue track.

**Comment by ThomasNieto** [comment]
@bmanikm Shouldn't this issue be closed since the PR was merged and released in PSGet 1.5.0?

**Comment by ThomasNieto** [comment]
@SydneyhSmith can you close this issue?
