### ISSUE TITLE
Install-Module should optionally install missing RequiredModules

### ISSUE THREAD

**Issue by Blackbaud-ShaydeNofziger** [PowerShell/PowerShellGetv2#169]
This is an enhancement request, one I'd be happy to implement and PR if accepted.

## Expected Behavior

`Install-Module` should install everything required for the module to be successfully imported.

I propose an enhancement to the `Install-Module` function to (optionally) install `RequiredModules` missing from the local machine.

## Current Behavior

Currently, `Import-Module` fails when a module listed in `RequiredModules` of the `psd1` file is not installed in the local environment.

IMO, a user should be able to expect that a module's dependencies listed in `RequiredModules` are included with their `Install-Module` call.

## Possible Solution

Such a command might look something like this:
```PowerShell
Install-Module -Name My-Module -WithRequiredModules
```
I believe the default behavior should install `RequiredModules`, however I'm open to installing them with an optional switch for compatibility's sake.

## Context

The current implementation requires users to know the `RequiredModules` for a module they intend to import. Generally, module consumers aren't aware of the required modules until they run `Import-Module` and the command fails.

This would also help when PowerShell modules are used as part of automation. The individual modules could be installed separately, of course, but being able to install a single module with all its `RequiredModules` enables more general scripts and build automation to be created. In this case, the automation doesn't need to know anything about the module it is installing in order for it to be imported successfully.

**Comment by Jaykul** [comment]
I don't understand. 

Installing dependencies is _already_ built-in to Install-Module and even Save-Module. It's just not optional.  Are you proposing to make it optional?

**Comment by Blackbaud-ShaydeNofziger** [comment]
...Well that's embarrassing. Sorry - I must be having a local issue that isn't installing the requiredmodules. I'll close this issue
