### ISSUE TITLE
Documentation link in changelog is broken

### ISSUE THREAD

**Issue by BrunoMacias** [PowerShell/PowerShellGetv2#176]
https://github.com/PowerShell/PowerShellGet/blob/development/CHANGELOG.md has the link below. But it doesn't go anywhere. 

https://docs.microsoft.com/en-us/powershell/gallery/psget/module/RequireLicenseAcceptance

**Comment by bmanikm** [comment]
Please take a look https://github.com/PowerShell/PowerShell-Docs/pull/1620 , this PR has been merged. It looks like the documentation is not yet deployed to live documentation site.

**Comment by bmanikm** [comment]
https://docs.microsoft.com/en-us/powershell/gallery/psget/module/RequireLicenseAcceptance is live now.
