### ISSUE TITLE
[Test-ScriptFileInfo] Fails on *NIX newlines (LF vs. CRLF)

### ISSUE THREAD

**Issue by Velocet** [PowerShell/PowerShellGetv2#18]
`Test-ScriptFileInfo` fails if the file has _LF_ line endings to indicate a newline.
## Expected Behavior

Validates a comment block for a script.
## Current Behavior

Validation fails when _LF_ for a newline is used:

> Script 'script.ps1' is missing required metadata properties. Verify that the script file has Version, Guid, Description and Author properties. You can use the Update-ScriptFileInfo or New-ScriptFileInfo cmdlet to add or update the PSScriptInfo to the script file.
## Possible Solution
- Open an Issue on GitHub
- Complain that you can't fix it for yourself
- Hope that someone at MSFT can do it 👍 
## Steps to Reproduce
1. Download [Test-ScriptFileInfo Line Ending Test Files](https://gist.github.com/Velocet/5799ec0b6c4e8c463b2da4bdf8dab4d6)
2. Valid: `Test-ScriptFileInfo .\Test-ScriptFileInfo_Newline-CRLF.ps1`
3. Fails: `Test-ScriptFileInfo .\Test-ScriptFileInfo_Newline-LF.ps1`
## Context

None.
## Environment

``` PowerShell
> $PSVersionTable

PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by Velocet** [comment]
Updated the Issue with a more correct name.

**Comment by bmanikm** [comment]
Hi @Velocet, Could you please verify whether this issue got fixed with the latest builds of PowerShellCore? I believe this issue got fixed along with other code changes for PowerShellCore.

**Comment by Velocet** [comment]
@bmanikm Verified working on Windows 10 Enterprise LTSB 2016 Version 1607 (Build 14393.1198).

```PowerShell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.1198
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1198
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by bmanikm** [comment]
Thanks for verifying the fix.
