### ISSUE TITLE
HTTPS PowerShellGet Repository invalid web uri

### ISSUE THREAD

**Issue by BatmanAMA** [PowerShell/PowerShellGetv2#180]
## Expected Behavior
Register-PSRepository should complete without error

## Current Behavior
Register-PSRepository : The specified Uri 'https://pkg.contoso.local/nuget/PowerShell' for parameter 'SourceLocation' is an invalid Web Uri. Please ensure that it meets the Web Uri requirements.

## Steps to Reproduce (for bugs)
1. Create nuget repo on https url
2. `Register-PSRepository -Name testing -SourceLocation https://pkg.contoso.local/nuget/PowerShell`

Note - below works as expected
`Register-PSRepository -Name testing -SourceLocation http://pkg.contoso.local/nuget/PowerShell`

## Context
My security department requires internal communication be done via https as much as possible. I will need to get a security exception for this.

## Your Environment
```PowerShell

> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14409.1012
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1012
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


> Get-Module

ModuleType Version    Name
---------- -------    ----
Manifest   3.1.0.0    Microsoft.PowerShell.Management
Manifest   3.0.0.0    Microsoft.PowerShell.Security
Manifest   3.1.0.0    Microsoft.PowerShell.Utility
Manifest   3.0.0.0    Microsoft.WSMan.Management
Script     1.1.6.0    PackageManagement
Script     1.5.0.0    PowerShellGet

> Get-Module -ListAvailable PowerShellGet,PackageManagement

ModuleType Version    Name
---------- -------    ----
Script     1.1.6.0    PackageManagement
Binary     1.0.0.1    PackageManagement
Script     1.5.0.0    PowerShellGet
Script     1.0.0.1    PowerShellGet

> Get-PackageProvider

Name                     Version
----                     -------
msi                      3.0.0.0
msu                      3.0.0.0
NuGet                    2.8.5.210
PowerShellGet            1.5.0.0
Programs                 3.0.0.0

> Get-PackageProvider -ListAvailable

Name                     Version
----                     -------
msi                      3.0.0.0
msu                      3.0.0.0
nuget                    2.8.5.208
NuGet                    2.8.5.210
PowerShellGet            1.5.0.0
PowerShellGet            1.0.0.1
Programs                 3.0.0.0
```

**Comment by Benny1007** [comment]
coming across this too, this was an issue way back here it would seem

https://github.com/OneGet/testbuild/issues/2

although I am not 100% certain OneGet became PowerShellGet

**Comment by MassimoSporchia** [comment]
Same thing happens to me, this fixed it: https://stackoverflow.com/questions/35296482/invalid-web-uri-error-on-register-psrepository (as referenced in the issue https://github.com/PowerShell/PowerShell/issues/5708 )

My URL is in this form: http://a.b.c.d/repository/PowerShellGallery_proxy/

**Comment by edyoung** [comment]
We support HTTPS in the general case (for example the default PSGallery URL is https://). I suspect this is related to what the actual form of the URL, and probably whether an SSL handshake will succeed. If it's not private, Massimo, what is a.b.c.d in your case? If you run Invoke-WebRequest -Uri http://a.b.c.d/repository/PowerShellGallery_proxy/ does it work?

Regarding @BatmanAMA  's issue, .local is kind of a special case for SSL- since anyone can obtain any .local certificate, it doesn't offer the usual protection against MITM attacks that a certificate for foo.bar.com would offer. That might be related.

**Comment by MassimoSporchia** [comment]
@edyoung hi there, the host name is as following: nexus.devops.mycompany.local

The URL works because after using the fix I was able to import the a nuget module via Nexus

I'll update with the command's result as soon as I can get my hands on the machine

FYI I tried different variations of the URL and what seemed to break the registerrepository command was the triple subdomain

**Comment by MassimoSporchia** [comment]
@edyoung it was a case-sensitivity issue.
the endpoint I inserted into the code was: "*/PowerShellGallery_proxy/"
What was executed was: "*/**p**ower**s**hell**g**allery_proxy/" which results in 404 ( I didn't know Sonatype Nexus docker image was case-sensible).
 Sorry for the trouble :)

Lesson learned: think twice before posting on an issue on fridays 😄

**Comment by Geogboe** [comment]
@MassimoSporchia +1, just want to second your statement here and say I'm using ProGet and this issue was the exact same for me.

**Comment by BatmanAMA** [comment]
Just to put this to bed - not sure if there was a fix put in, but I am no longer having this issue on the latest version. I did verify that changing casing doesn't break it for me (proget) so I don't think that was the issue.

```powershell
ModuleType Version Name
---------- ------- ----
    Script 1.1.7.2 PackageManagement
    Script 1.6.6   PowerShellGet
```

**Comment by jzabroski** [comment]
@BatmanAMA  I took your suggestion and upgraded to 1.6.7 and still have issues here. Moreover, while the recommended idea to use https:// worked in previous versions of PowerShellGet, it no longer works on 1.6.7 - Please re-open this ticket.

1. I was able to successfully publish a package to our internal ProGet feed, but had a warning when doing so.
This worked previously, with a warning:
```powershell
> Register-PSRepository -Name Example-Development -SourceLocation "https://packages.example.local/nuget/Example-Development/api/v2" -PublishLocation http://packages.example.local/nuget/Example-Development/api/v2/package
```
```
WARNING: Unable to resolve package source 'https://packages.example.local/nuget/Example-Development/api/v2'.
```
This now completely fails on 1.6.7:
```powershell
> Register-PSRepository -Name Example-Development -SourceLocation "https://packages.example.local/nuget/Example-Development/api/v2" -PublishLocation http://packages.example.local/nuget/Example-Development/api/v2/package
```
```
Register-PSRepository : The specified Uri 'https://packages.example.local/nuget/Example-Development/api/v2' for parameter 'SourceLocation' is an invalid Web Uri. Please ensure that it meets the Web Uri requirements.
At line:1 char:1
+ Register-PSRepository -Name Example-Development -SourceLocation "http ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (https://package...elopment/api/v2:String) [Register-PSRepository], ArgumentException
    + FullyQualifiedErrorId : InvalidWebUri,Register-PSRepository
```

In previous versions of PowerShellGet, I could upload to a repository, I just couldn't Install-Module from the repository.

RANT
I am beyond frustrated with how terrible PowerShellGet is.  Every time I use it I get indescribably awful error messages and spend hours googling trying to solve problems related to getting my packages available for others to consume. If PowerShell was not forced down the throat of every Microsoft employee, who the hell would use it with such a painful package management experience? Even calling New-ModuleManifest with just -Path parameter does not give you a complete manifest to then call Publish-Module on. You have to then put a Description in. *Literally, everything takes at least one extra step more than it should, **nothing is cohesive**. If Satya Nadella is reading this, please improve the morale of your employees by fixing how non-productive PowerShell is.*
END RANT

**Comment by jzabroski** [comment]
@BatmanAMA  I have since discovered what I think the problem is, and a general clue why it magically started working for you: The real problem is PowerShellGet is `"Unable to find type [System.Net.Http.HttpClient]"`

```powershell
PS C:\WINDOWS\system32> $Error
PS C:\WINDOWS\system32>  Register-PSRepository -Name Example-Development -SourceLocation "http://packages.example.local/nuget/Example-Development/api/v2" -PublishLocation http://packages.example.local/nuget/Example-Development/api/v2/package
Register-PSRepository : The specified Uri 'http://packages.example.local/nuget/Example-Development/api/v2' for parameter 'SourceLocation' is an invalid Web Uri. Please ensure that it meets the Web Uri requirements.
At line:1 char:2
+  Register-PSRepository -Name Example-Development -SourceLocation "http: ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (http://packages...elopment/api/v2:String) [Register-PSRepository], ArgumentException
    + FullyQualifiedErrorId : InvalidWebUri,Register-PSRepository

PS C:\WINDOWS\system32> $Error
Register-PSRepository : The specified Uri 'http://packages.example.local/nuget/Example-Development/api/v2' for parameter 'SourceLocation' is an invalid Web Uri. Please ensure that it meets the Web Uri requirements.
At line:1 char:2
+  Register-PSRepository -Name Example-Development -SourceLocation "http: ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (http://packages...elopment/api/v2:String) [Register-PSRepository], ArgumentException
    + FullyQualifiedErrorId : InvalidWebUri,Register-PSRepository

Unable to find type [System.Net.Http.HttpClient].
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.6.7\PSModule.psm1:3020 char:9
+         [System.Net.Http.HttpClient]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.Http.HttpClient:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Get-Variable : Cannot find a variable with the name 'PackageManagementProvider'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.6.7\PSModule.psm1:11275 char:16
+ ...          if(Get-Variable -Name PackageManagementProvider -ErrorAction ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (PackageManagementProvider:String) [Get-Variable], ItemNotFoundException
    + FullyQualifiedErrorId : VariableNotFound,Microsoft.PowerShell.Commands.GetVariableCommand
```
