### ISSUE TITLE
Sign binaries for release build

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PowerShellGetv2#181]
authenticode all binaries in the release builds of the module.

**Comment by bmanikm** [comment]
@TravisEz13 PowerShellGet and PackageManagement module contents are always authenticode/strongname signed when released to the PowerShell Gallery. Could you please let us know what work is involved here?

**Comment by TravisEz13** [comment]
It's probably showing up as not properly signed in the tool because you are using sha1 signing.  SHA256 is required.  Speak to me offline on how to update your build.
