### ISSUE TITLE
Confusing output from Update-Module -whatif

### ISSUE THREAD

**Issue by ghost** [PowerShell/PowerShellGetv2#186]
Ran update-module -whatif, saw output for PackageManagement twice:
What if: Performing the operation "Update-Module" on target "Version '1.1.6.0' of module 'PackageManagement', updating to version '1.1.7.0'". 
What if: Performing the operation "Update-Module" on target "Version '1.5.0.0' of module 'PackageManagement', updating to version '1.1.7.0'".
With Verbose on, it seems that PackageManagement is repeated when PowerShellGet is scanned. 

## Expected Behavior

I expect to see 1 report for PackageManagement needing to be updated

## Steps to Reproduce (for bugs)

Here's output with -verbose
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Azure.Storage'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'Azure.Storage'.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='AzureRM.Profile'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'AzureRM.Profile'.
VERBOSE: Skipping installed module Azure.Storage 3.4.1.
VERBOSE: Skipping installed module AzureRM.profile 3.4.1.
VERBOSE: Checking for updates for module 'AzureRM.profile'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'False'; IsRegistered = '
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='AzureRM.profile'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'AzureRM.profile'.
VERBOSE: Skipping installed module AzureRM.profile 3.4.1.
VERBOSE: Checking for updates for module 'PackageManagement'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'False'; IsRegistered = '
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PackageManagement'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'PackageManagement'.
What if: Performing the operation "Update-Module" on target "Version '1.1.6.0' of module 'PackageManagement', updating to version '1.1.7.0'".
VERBOSE: Checking for updates for module 'posh-git'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'False'; IsRegistered = '
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='posh-git'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'posh-git'.
VERBOSE: Skipping installed module posh-git 0.7.1.
VERBOSE: Checking for updates for module 'PowerShellGet'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'False'; IsRegistered = '
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'PowerShellGet'.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PackageManagement'' for ''.
VERBOSE: Total package yield:'6' for the specified package 'PackageManagement'.
VERBOSE: Skipping installed module PowerShellGet 1.5.0.0.
What if: Performing the operation "Update-Module" on target "Version '1.5.0.0' of module 'PackageManagement', updating to version '1.1.7.0'".

**Comment by edyoung** [comment]
This just doesn't seem all that important. Please reactivate if you disagree
