### ISSUE TITLE
Remove dependencies on $IsCoreCLR on PowerShell Core

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShellGetv2#187]
The powershell core committee has decided to remove the variable `$IsCoreCLR` from PowerShell Core.
Here is the related comment in the discussion of https://github.com/PowerShell/PowerShell/issues/4904: https://github.com/PowerShell/PowerShell/issues/4904#issuecomment-341258168

The fact whether it's running on CoreCLR can be checked by
```
$PSVersionTable.ContainsKey('PSEdition') -and $PSVersionTable.PSEdition -eq 'Core'
```

**Comment by daxian-dbw** [comment]
@bmanikm Thanks! Will a new module package be published soon?

**Comment by bmanikm** [comment]
@daxian-dbw We are planning to release a new version with Prerelease version support in couple weeks and before end of this month.
