### ISSUE TITLE
Need to update the CI builds to use the latest powershell-beta.9 package for tests on PowerShell Core

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PowerShellGetv2#189]
I find that the CI builds are still using powershell-6.0.0-beta.5 for test runs on PowerShell Core.
PowerShell Core has some breaking changes in the recent 2 releases, and currently the latest release is beta.9. PowerShell Core is going to have the RC release on 11/15, so PowerShellGet should update its CIs to run on powershell core beta.9 as soon as possible, so that if there are any issues coming up we still have time to fix them before RC.

/cc @bmanikm @PowerShell/powershell-maintainers

**Comment by bmanikm** [comment]
Resolved with https://github.com/PowerShell/PowerShellGet/pull/190.
