### ISSUE TITLE
Ignore files when using `Publish-Module`

### ISSUE THREAD

**Issue by aaronpowell** [PowerShell/PowerShellGetv2#191]
When I publish a module using the `Publish-Module` command to the PowerShellGallery it will automatically generate a `nuspec` file for me, and in turn a NuGet package is generated.

I'd like a way to mark files to be excluded from the package that I'm uploading so that I don't publish unneeded files, such as my Pester test scripts.

Currently my workaround for this is to have a step that copies all the files I want packaged into a new folder and then run the `Publish-Module` from there instead of my repository root.

My thought is that if you had a file like a `.psget-files.json` in the root of the folder you would then use file glob that allows you to either specify the files to include or exclude. Example file:

```json
{
     "include": "*.psm1;*.psd1",
     "exclude": ".vscode;*.tests.*"
}
```

Then when the `nuspec` is being generated it can create `<file />` XML nodes for it using the glob patterns.

**Comment by SteveL-MSFT** [comment]
If the only concern is Pester test scripts, I think it's actually a best practice to include them.  In the future, maybe PowerShellGallery can leverage included test scripts.  However, if you have some other files you want excluded, perhaps PSGet can borrow something like .gitignore

**Comment by aaronpowell** [comment]
I was using Pester as an example of something that's common, but it's not the old thing. I have `.gitignore`/`.gitattributes`/`.editorconfig` in the repo, a `.vscode` folder for launch/tasks, etc.

I also accidentally published a version of my module with a few hundred extra files because I hadn't cleaned up the repo from testing (the module is a [node.js version manager](https://github.com/aaronpowell/ps-nvmw) and I had some installed versions of node.js that got automatically picked up and put in the NuGet package).

Another scenario that I've come across is when I'm using .NET to create a library to invoke from PowerShell (to wrap some logic that was easier for me to write in F# than PowerShell) I don't want to publish the source code with the module, only the dll. In this scenario a `.gitignore` file wouldn't be useful for finding the ignored files because the source would be in my repo, but I don't want it in the published module.

**Comment by SteveL-MSFT** [comment]
I think a current workaround would be to have a PowerShel script to build and copy only the files you want to publish to a different folder in your $PSModulePath and use that to publish.

**Comment by aaronpowell** [comment]
Yep that's essentially the approach I take at the moment.

**Comment by Benny1007** [comment]
A recent refactor has made this enhancement achievable. Take a look at the branch above. Using the Files tag in the nuspec is a departure from convention based packaging and requires explicitly defining all files. I have made the assumption of a single <file> entry with a pattern matching  all files as before (**/*.*) but reading in the 'exclude' patterns from user input.

**Comment by kburetta** [comment]
Can you explain how one would use the -exclude flag to exclude all the files within a directory, but still retain the empty directory?
