### ISSUE TITLE
Publish-Module with extra files

### ISSUE THREAD

**Issue by Archdeacon** [PowerShell/PowerShellGetv2#193]
PSVersion: 5.0.10586.117; Windows 7 Pro.
I have created a module needing more than one file, ie Help.chm, icon.jpeg and an XAML file. How do I include all this with the manifest psd1 in Publish-Module please?

**Comment by bmanikm** [comment]
You need to place the required files under the module folder (the location of module manifest file).
- https://msdn.microsoft.com/en-us/library/dd878310(v=vs.85).aspx 
- https://docs.microsoft.com/en-us/powershell/gallery/psgallery/creating-and-publishing-an-item
