### ISSUE TITLE
Errors with Get/Set-PSRepository on Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by devblackops** [PowerShell/PowerShellGetv2#197]
## Expected Behavior
Getting / setting PowerShell repositories should behave the same in WSL as they do in Windows.

## Current Behavior
We're getting odd errors getting and setting PowerShell repositories here https://github.com/psake/psake/issues/237 where we are setting the PSGallery repository installation policy to `Trusted` if needed. This works fine on Windows but in WSL (Ubuntu) it is throwing errors.

In WSL, run `Get-PSRepository` with no parameters. Works as expected.
```powershell
PS /> Get-PSRepository                                                                                                                                                  
Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2/
```

Run `Get-PSRepostory -Name PSGallery` throws an error.
```powershell
PS /> Get-PSRepository -Name PSGallery                                                                                                                                  Exception calling "GetIsNetworkAvailable" with "0" argument(s): "An error was encountered while querying information from the operating system."
At /opt/microsoft/powershell/6.0.0-rc/Modules/PowerShellGet/1.5.0.0/PSModule.psm1:6264 char:9
+         $connected = [System.Net.NetworkInformation.NetworkInterface] ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : NetworkInformationException
```

Running `Set-PSRepository` throws an error but still appears to set the repository to trusted.
```powershell
PS /> Set-PSRepository -Name PSGallery -InstallationPolicy Trusted                                                                                                      Exception calling "GetIsNetworkAvailable" with "0" argument(s): "An error was encountered while querying information from the operating system."
At /opt/microsoft/powershell/6.0.0-rc/Modules/PowerShellGet/1.5.0.0/PSModule.psm1:6264 char:9
+         $connected = [System.Net.NetworkInformation.NetworkInterface] ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : NetworkInformationException

PS /> Get-PSRepository

Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Trusted              https://www.powershellgallery.com/api/v2/
```

## Steps to Reproduce (for bugs)
1. Setup WSL and install PowerShell 6.0.0-rc.
2. Run `Get-PSRepository` with no parameters. Works as expected
3. Run `Get-PSRepository -Name PSGallery`. Observe errors
4. Run `Set-PSRepository -Name PSGallery -InstallationPolicy Trusted`. Observe errors

## Context
As part of developing and testing the [psake](https://github.com/psake/psake) project, it would be great if this process worked in WSL as well.

## Your Environment

```PowerShell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-rc
PSEdition                      Core
GitCommitId                    v6.0.0-rc
OS                             Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

> Get-Module -ListAvailable PowerShellGet,PackageManagement
ModuleType Version Name
---------- ------- ----
    Script 1.1.7.0 PackageManagement
    Script 1.5.0.0 PowerShellGet

> Get-PackageProvider
Name          Version
----          -------
NuGet         2.8.5.210
PowerShellGet 1.5.0.0

> Get-PackageProvider -ListAvailable
Name          Version
----          -------
NuGet         2.8.5.210
PowerShellGet 1.5.0.0
```

**Comment by kilasuit** [comment]
@devblackops  - whilst I understand what the issue that you've raised is, I am struggling to understand (through looking at the code) why this error comes up, let alone exactly why there is a requirement to check for network access at all (a PSRepository can be a Local folder afterall)

However I now understand the flow and required fix here. 

Thanks for reporting!

**Comment by kilasuit** [comment]
Further investigation into this seems like an issue in the WSL (tested on Ubuntu 16.04 WSL image) as it is throwing an error complaining about being unable query information on the network state from the OS

Although this error seems to be on that is more WSL than being PowerShellGet, and is one that I think that you can completely ignore as the command actually seems to go though as per this below 

![image](https://user-images.githubusercontent.com/6355225/37124206-298a36e8-221c-11e8-8918-cae16c969cba.png)

Obviously, my suggestion isn't ideal, but to "ignore" this error output I would suggest that you add to the `Set-PSRepository` function the `ErrorAction` parameter with a value of `SlientlyIgnore` as this is more WSL related than PowerShellGet related from what I've tested.

PS - I also tested this against an Ubuntu 16.04 image that I have running in Azure where this doesn't fail with the error that you are getting, which points to it being a WSL issue

**Comment by edyoung** [comment]
This issue is fixed by the changes made to simplify the connectivity checks powershellget does.
