### ISSUE TITLE
[PowerShell] - Make Install-Module automatically install in CurrentUser scope for non admin users

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShellGetv2#2]
As per issue https://github.com/PowerShell/PowerShell/issues/2292 - Reported by @ffeldhaus - moving this here as the home for PowerShellGet module for possible further discussion.

This is a feature request. Currently Install-Module gives a warning in Windows PowerShell if it is not run with admin privileges and -Scope CurrentUser is not specified.

As many users just expect Install-Module to work and as the ability to install Modules in the current users scope is one of the key advantages of PowerShell, it would be a great enhancement if the default behaviour of Install-Module would be to automatically install the Module in the current user scope if it is run with non admin privileges.

cc @bmanikm @JKeithB @andschwa

**Comment by Velocet** [comment]
But sometimes it happens that you forget to fire up a shell with admin rights...

So a warning message is a good thing in this case...

**Comment by Jaykul** [comment]
Tt's possible to distinguish between a non-elevated administrator and a non-administrator, right? So perhaps a warning (or the current behavior) for non-elevated administrators, and silently doing the right thing for other users?

**Comment by bmanikm** [comment]
As discussed in https://github.com/PowerShell/PowerShell/issues/2292 I have improved the error message in #4 to detect and throw proper error message in Linux and Mac.
