### ISSUE TITLE
"Cannot convert value" Error Installing Latest Version

### ISSUE THREAD

**Issue by rmegal** [PowerShell/PowerShellGetv2#216]
I'm trying to upgrade to 1.6.0 so I run this:

install-module -Name PowerShellGet -Force

And get this:

PackageManagement\Install-Package : Cannot convert value "1.2.0-preview" to type "System.Version". Error: "Input string was not in a
correct format."
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocation,New-PSGetItemInfo,Microsoft.PowerShell.PackageManagement.Cmdlets.Inst
   allPackage

What am I missing?

**Comment by bmanikm** [comment]
@rmegal 
I am unable to reproduce this issue. 
Please ensure that your machine has the latest version of NuGet provider, you can install it using `Install-PackageProvider NuGet -Force` then restart the PS Console.

Please provide [more details](https://github.com/PowerShell/PowerShellGet/issues/new) to reproduce this issue.

**Comment by rmegal** [comment]
Updating the NuGet provider resolved the problem:

```
Install-PackageProvider NuGet -Force

Name                           Version          Source           Summary
----                           -------          ------           -------
nuget                          2.8.5.208        https://onege... NuGet provider for the OneGet meta-package manager
```

I ran the install again after this without any problems. Then I ran:

```
Get-Module -ListAvailable -Name PowerShellGet


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.6.0      PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
```

Thanks.

Ray
