### ISSUE TITLE
Publish-Module is doing a string comparison and not a version comparision

### ISSUE THREAD

**Issue by KevinMarquette** [PowerShell/PowerShellGetv2#217]
When my published version was "0.4.9.310" and when I tried to publish version "0.4.10.1", I got this error message:

    Publish-Module : Module 'MyModule' with version '0.4.10.1' cannot be published. The version must exceed the current version '0.4.9.310' that exists in the repository or you must specify -Force.

Debugging the publish took me to this line where a string comparison was performed when I expected to see a [version] comparison.

https://github.com/PowerShell/PowerShellGet/blob/8726e194ad3eb513cb53a6d50bd34de8d814cd82/PowerShellGet/PSModule.psm1#L1409

**Comment by bmanikm** [comment]
Resolved with https://github.com/PowerShell/PowerShellGet/pull/219.
