### ISSUE TITLE
Microsoft-signed Modules like Pester Fail Updates by Default

### ISSUE THREAD

**Issue by potatoqualitee** [PowerShell/PowerShellGetv2#233]
## Expected Behavior

If the publisher is trusted even if the publishing cert changed, PowerShellGet shouldn't stop the install, perhaps a warning is okay (wording taken from @SteveL-MSFT in this [Pester issue](https://github.com/pester/Pester/issues/999#issuecomment-368260237)).

## Current Behavior
Install fails if cert publisher changes. This has a severe impact on Pester and modules that list Pester as a RequiredModule, like [dbachecks](https://dbachecks.io).

![image](https://user-images.githubusercontent.com/8278033/36690655-4a8df324-1b33-11e8-8aae-0551f6e29db1.png)

We then have to educate people in every post to

```powershell
Install-Module Pester -SkipPublisherCheck -Force
Import-Module Pester -Force
````

## Possible Solution
Allow install it without warning or allow it with warning.

## Steps to Reproduce (for bugs)
1. Install Win 10 or Windows 2016
2. `Install-Module dbachecks`
3. Fail

## Context

We include Pester as a required module in dbachecks and have to explicitly say everywhere how to first update Pester the manual way. 

`Install-Module Pester -SkipCatalogCheck -Force`

Even though we state this everywhere, we still get questions.

This is also a "known issue" and recurring issue for the Pester project. Pester is signed by Microsoft out of the box, but cannot be signed by Microsoft subsequently. 

## Your Environment

> $PSVersionTable

```
Name                           Value
----                           -----
PSVersion                      5.1.16299.248
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.248
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by edyoung** [comment]
Hi, we understand the issue but have not yet worked out the appropriate solution. The 'publisher check' exists to reduce the risk of someone hijacking an important package (like Pester) and publishing their own malicious version of it. In this instance it's obviously not having the desired effect, but we need to be careful not to make it easier to hijack packages in the process.

**Comment by SteveL-MSFT** [comment]
It seems to me that if the cert is trusted, but different from the original, it should be safe to install (since it's trusted) and just have a warning that the signer cert is different from the previous installed version.

**Comment by edyoung** [comment]
This is partially resolved by changes in PowerShellGet 1.6.5, released today. 

This release implements a whitelist, containing Pester and PSReadLine. A module in the whitelist **which is signed by somebody, even if not Microsoft** will be accepted in place of the Microsoft module, even without -SkipPublisherCheck. 

Once signed versions of Pester and PSReadLine are published, this issue can hopefully be resolved. 

FYI @dlwyatt , @lzybkr

**Comment by kilasuit** [comment]
cc @nohwnd - as per my mention in https://github.com/pester/Pester/issues/999 see response from @edyoung above

**Comment by nohwnd** [comment]
@kilasuit thanks for the reminder, will try to look at this till the weekend (which usually means that I will do it during the weekend :) )

**Comment by nohwnd** [comment]
@edyoung Pester is signed since `4.4.3`. I think you can close this.

**Comment by edyoung** [comment]
Sweet!

**Comment by potatoqualitee** [comment]
Thanks for this, everyone!
