### ISSUE TITLE
PowerShellGet should be able to filter results to signed items only, and who signed them

### ISSUE THREAD

**Issue by ghost** [PowerShell/PowerShellGetv2#239]
I want to be able to do something like
Find-Item -SignedOnly -SignatureContains Microsoft

For highest degree of knowledge around who actually published an item, I may choose to only trust signed items, and if so, I want to know that the certificate is linked to the person/company I trust.

## Current Behavior

Today, I must locally save all the items I might be interested in, then check to see if they are signed, and by whom using some fairly complex PS code.

**Comment by SydneyhSmith** [comment]
Closing as inactive, will open if this is still a request
