### ISSUE TITLE
Find-Module error when updating PowerShellGet - Package Provider still loads 1.0.0.1

### ISSUE THREAD

**Issue by gaelcolas** [PowerShell/PowerShellGetv2#246]
When updating PowerShellGet module to latest (1.6.0) from 1.0.0.1, and unloading 1.0.0.1, `Find-Module -Name ModuleName` starts to fail with:
```
Find-Package : A parameter cannot be found that matches parameter name 'AllowPrereleaseVersions'. At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.6.0\PSModule.psm1:1609 char:34
+         PackageManagement\Find-Package @PSBoundParameters | Microsoft ...
```

## Expected Behavior
```PowerShell
PS C:\src> get-module PowerShellGet -list


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-M...


PS C:\src> install-module PowerShellGet -Force
PS C:\src> Remove-module PowerShellGet
PS C:\src> import-module PowerShellGet -PassThru

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.6.0      PowerShellGet                       {Find-Command, Find-DscResource, Fin...


PS C:\src> find-module PackageManagement

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.7.0    PackageManagement                   {Find-Package, Find-PackageProvider,...

PS C:\src> Get-PackageProvider -Name PowerShellGet

Name                     Version          DynamicOptions
----                     -------          --------------
PowerShellGet            1.6.0.0          PackageManagementProvider, Type, Scope, AllowClobber...

```

## Current Behavior
```PowerShell
PS C:\src> get-packageProvider

Name                     Version          DynamicOptions
----                     -------          --------------
Chocolatey               2.8.5.130        SkipDependencies, ContinueOnFailure, ExcludeVersion,... 
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
NuGet                    2.8.5.208        Destination, ExcludeVersion, Scope, SkipDependencies... 
PowerShellGet            1.0.0.1          PackageManagementProvider, Type, Scope, AllowClobber... 
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent


PS C:\src> get-module PowerShellGet
PS C:\src> get-module PowerShellGet -list


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-M...


PS C:\src> install-module PowerShellGet

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change  its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to
install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y
WARNING: Version '1.0.0.1' of module 'PowerShellGet' is already installed at 'C:\Program
Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1'. To install version '1.6.0', run
Install-Module and add the -Force parameter, this command will install version '1.6.0' in
side-by-side with version '1.0.0.1'.
PS C:\src> install-module PowerShellGet -Force
PS C:\src> import-module PowerShellGet -Force
PS C:\src> Get-module PowerShellGet

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.0.1    PowerShellGet                       {Find-Command, Find-DscResource, Fin... 
Script     1.6.0      PowerShellGet                       {Find-Command, Find-DscResource, Fin...


PS C:\src> remove-module PowerShellGet
PS C:\src> import-module PowerShellGet
PS C:\src> Get-module PowerShellGet

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.6.0      PowerShellGet                       {Find-Command, Find-DscResource, Fin...


PS C:\src> find-module PackageManagement
Find-Package : A parameter cannot be found that matches parameter name 'AllowPrereleaseVersions'. At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.6.0\PSModule.psm1:1609 char:34
+         PackageManagement\Find-Package @PSBoundParameters | Microsoft ...
+                                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Find-Package], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.PackageManagement.Cmdl
   ets.FindPackage

PS C:\src> Get-PackageProvider

Name                     Version          DynamicOptions
----                     -------          --------------
Chocolatey               2.8.5.130        SkipDependencies, ContinueOnFailure, ExcludeVersion,... 
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
NuGet                    2.8.5.208        Destination, ExcludeVersion, Scope, SkipDependencies... 
PowerShellGet            1.0.0.1          PackageManagementProvider, Type, Scope, AllowClobber... 
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent


PS C:\src> Import-PackageProvider -Name PowerShellGet -Force -RequiredVersion 1.6.0

Name                     Version          DynamicOptions
----                     -------          --------------
PowerShellGet            1.6.0.0          PackageManagementProvider, Type, Scope, AllowClobber...


PS C:\src> find-module PackageManagement

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.1.7.0              PackageManagement                   PSGallery            PackageManagemen...


```

## Possible Solution
I found that the PackageProvider is not re-loaded, so one way to fix (**for current session only**) is to do:
`Import-PackageProvider -Name PowerShellGet -Force -RequiredVersion 1.6.0`.

It seems that the PowerShellGet PackageProvider will still be defaulting to 1.0.0.1 for every process spun up from parent session (i.e. Start - Run - PowerShell).

Also, as long as PowerShellGet module v1.0.0.1 is installed, when loading PowerShellGet 1.6.0, Package Management, or leaving to Module autoloading, the Package Provider PowerShellGet 1.0.0.1 will always be loaded. And _**that**_ is the worst part ;)

## Steps to Reproduce (for bugs)
See the current behaviour section.

## Context
This happened when updating the latest module of PackageManagement & PowerShellGet. It was relatively hard to troubleshoot because the error only refer to the Module(s), and when you check PackageManagement or PowerShellGet modules version they have the right Parameter. It does not mention the PowerShellGet PackageProvider.

The fact that the PackageProvider is persisted from the parent Session somehow made it harder to troubleshoot.
When logging on a machine, I'd have the error when doing `Windows -> Start -> Runas /u:user PowerShell`, even if I'd had removed the PowerShellGet module v 1.0.0.1.
If I then did Start PowerShell from there, it would pick up the latest (on only installed) PowerShellGet module.

## Your Environment
Tested on a Windows 7 with PSversion 5.1.14409.1012 and reproduced on the Windows 10 - Insider Preview Fast Ring system below

```PowerShell

> PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.17107.1000
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17107.1000
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

> Get-Module
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        chocolateyProfile                   {TabExpansion, Update-SessionEnviron... Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoi... Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variabl... Binary     1.0.0.1    PackageManagement                   {Find-Package, Find-PackageProvider,... Script     1.1.7.0    PackageManagement                   {Find-Package, Find-PackageProvider,... Script     1.6.0      
PowerShellGet                       {Find-Command, Find-DscResource, Fin... Script     1.2        
PSReadline                          {Get-PSReadlineKeyHandler, Get-PSRea...


> Get-Module -ListAvailable PowerShellGet,PackageManagement


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.7.0    PackageManagement                   {Find-Package, Get-Package, Get-Pack... 
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-Pack... 
Binary     1.0.0.0    PackageManagement                   {Find-Package, Get-Package, Get-Pack... 
Script     1.6.0      PowerShellGet                       {Install-Module, Find-Module, Save-M... 
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-M...


> Get-PackageProvider

Name                     Version          DynamicOptions
----                     -------          --------------
Chocolatey               2.8.5.130        SkipDependencies, ContinueOnFailure, ExcludeVersion,... 
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
NuGet                    2.8.5.208        Destination, ExcludeVersion, Scope, SkipDependencies... 
PowerShellGet            1.6.0.0          PackageManagementProvider, Type, Scope, AllowClobber... 
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent

> Get-PackageProvider -ListAvailable

Name                     Version          DynamicOptions
----                     -------          --------------
Chocolatey               2.8.5.130        SkipDependencies, ContinueOnFailure, ExcludeVersion,... ChocolateyGet            1.0.0.1          AdditionalArguments
ContainerImage           0.6.4.0
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
NuGet                    2.8.5.208        Destination, ExcludeVersion, Scope, SkipDependencies... 
PowerShellGet            1.6.0.0          PackageManagementProvider, Type, Scope, AllowClobber... PowerShellGet            1.0.0.1
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent

```

**Comment by bmanikm** [comment]
@gaelcolas 
- In the current session where you install the latest of PowerShellGet module
Yes, it is required to import the PowerShellGet provider in addition to reimporting the PowerShellGet module. 
`Import-Module -Name PowerShellGet -Force; Import-PackageProvider -Name PowerShellGet -Force` 
This is not recommended as the older version of PackageManagement is already loaded into the current process, its newer version may not work side-by-side as expected. It is recommended to install the latest version of PowerShellGet in a separate process prior to importing it in the current process.
--> https://github.com/PowerShell/PowerShellGet#get-powershellget-module

- *It seems that the PowerShellGet PackageProvider will still be defaulting to 1.0.0.1 for every process spun up from parent session (i.e. Start - Run - PowerShell)*
From the output you provided above in 'Your Environment', I found that 1.6.0 version of PowerShellGet is loaded properly. Are we missing anything here?

```powershell
> Get-Module
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.6.0      PowerShellGet                       {Find-Command, Find-DscResource, Fin... 

> Get-PackageProvider
Name                     Version          DynamicOptions
----                     -------          --------------
PowerShellGet            1.6.0.0          PackageManagementProvider, Type, Scope, AllowClobber... 
```

**Comment by gaelcolas** [comment]
Thanks @bmanikm for looking into this.

This mostly works, only slight difference is that I have to specify the `-RequiredVersion`:
```PowerShell
remove-module PowerShellGet,PackageManagement -force
Import-Module -Name PowerShellGet -Force;
Import-PackageProvider -Name PowerShellGet -Force -RequiredVersion 1.6.0
```

> PackageManagement is already loaded into the current process, its newer version may not work side-by-side as expected. It is recommended to install the latest version of PowerShellGet in a separate process prior to importing it in the current process

I can't see any recommendation to that effect in the docs? (for wmf 5/5.1)
Also, this is unpractical as this occurs during a Build process, do you have an example as to how you recommend doing it within an automated process?

Please ignore my comment saying: 
> It seems that the PowerShellGet PackageProvider will still be defaulting to 1.0.0.1 for every process spun up from parent session (i.e. Start - Run - PowerShell)

It was a wrong conclusion to my misunderstanding of the behaviour of PackageProvider, and another issue that I'll raise separately. 
It would be great to [update the documentation here.](https://docs.microsoft.com/en-us/powershell/gallery/psget/get_psget_module), or better, handle that directly within `Import-Module PowerShellGet -force`, even if it's just a warning message telling the user to do it.

If you feel that the `-RequiredVersion 1.6.0` is 'by design' feel free to close this issue ;)

**Comment by bmanikm** [comment]
Please take a look at `exit` usage in [documentation](https://docs.microsoft.com/en-us/powershell/gallery/psget/get_psget_module#for-systems-with-powershell-50-or-newer-you-can-install-the-latest-powershellget). You are right, we need to improve this documentation with more details.

Before running any cmdlet from the PowerShellGet or PackageManagement modules in your build process, please add below line to install the latest version of PowerShellGet.
`PowerShell.exe -Command {Install-Module PowerShellGet -Force}`
If you already have a latest version of this module, you might have add the conditional logic to not re-install the same version again on your development machine. If you have multiple repositories, please specify the -Repository parameter.




I have created https://github.com/OneGet/oneget/issues/348 for `-RequiredVersion 1.6.0` issue and closing this here.

**Comment by gaelcolas** [comment]
I cannot Install the module (even in user scope) to avoid polluting the environments, so I assume the `Save-Module` should be done the same way, in a separate process?
Then you say:
>  If you have multiple repositories, please specify the -Repository parameter

Is that necessary if both repositories are configured for that user, and the module only available in one of them?
Any undocumented reason behind this? (I'll open an issue later today that could be related, hence me asking).

**Comment by bmanikm** [comment]
> I cannot Install the module (even in user scope) to avoid polluting the environments, so I assume the `Save-Module` should be done the same way, in a separate process?

Separate process is required when a newer version of PowerShellGet module depends on the newer version of PackageManagement module. Since the older version of PackageManagement module is currently loaded into the current process, importing the newer version of PackageManagement may not work as expected.
Save-Module approach within the current process should work if the newer version of PowerShellGet is compatible with the currently imported version of PackageManagement module, in that case, we just have to re-import the PowerShellGet module along with its provider with -RequiredVersion parameter as we discussed above.

> Is that necessary if both repositories are configured for that user, and the module only available in one of them?

It is not required to specify the repository parameter when the specified module is available in only one of the registered repositories.
