### ISSUE TITLE
Connect-PnPOnline   -UseWebLogin not closing

### ISSUE THREAD

**Issue by ITFO** [PowerShell/PowerShellGetv2#247]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

```PowerShell

Connect-PnPOnline : Object reference not set to an instance of an object.
At line:1 char:1
+ Connect-PnPOnline  -Url  http://sharepointO365/sites/subsite -UseWebLog ...
```

**Comment by erwinvanhunen** [comment]
@billyperalta89 This is not the correct repo for this issue. Please move it to https://github.com/sharepoint/pnp-powershell/issues.

**Comment by bmanikm** [comment]
This issue was moved to SharePoint/PnP-PowerShell#1464
