### ISSUE TITLE
Unable to access package, are you missing 'Credential' parameter in the cmdlet?

### ISSUE THREAD

**Issue by dmittal01** [PowerShell/PowerShellGetv2#248]
We are able to register the repository with PowerShell, however when we run Find-module, we are getting error Are you missing 'Credential' parameter in the cmdlet?

steps to repro:
a) register the repository:
Register-PSRepository -Name NPMPkgTest -SourceLocation https://abc.pkgs.visualstudio.com/_packaging/NPMPkgTest/nuget/v2 -InstallationPolicy Trusted -Credential $credential

It got registered successfully.
b) PS D:\CredentialProviderBundle> Get-PSRepository

Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2/
NPMPkgTest                Trusted              https://dmittal.pkgs.visualstudio.com/_packaging/NPMPkgTest/nuget/v2

However when we run Find-Module, it throws the error are you missing 'Credential' parameter in the cmdlet?

PS D:\CredentialProviderBundle> Find-module -Name "NPMPkgTest" -Credential $Credential
WARNING: Cannot access 'https://abc.pkgs.visualstudio.com/_packaging/NPMPkgTest/nuget/v2'. Are you missing 'Credential' parameter in the cmdlet?

**Comment by bmanikm** [comment]
@dmittal01 how are you constructing the credential object? please take a look at the steps mentioned [here](https://github.com/PowerShell/PowerShell-Docs/issues/1200#issue-227526581) to work with the VSTS packaging feeds.

**Comment by wgv-srbrills** [comment]
```
$patToken = "abcdefghijklmnopqrstuvwxyz";
$secure = ConvertTo-SecureString -String $patToken -AsPlainText -Force;
$cred = New-Object System.Management.Automation.PSCredential("johndoe@gmail.com", $secure);

Find-Module -Name "NPMPkgTest" -Credential $cred;
```

When authenticating against a feed in VSTS/Azure DevOps, be sure to use a PAT token instead of a password.  Your PAT token should have access to read from the package feed.  This is because PowerShellGet only supports NuGet v2, which only supports PAT tokens.
