### ISSUE TITLE
Enable Publish-Module and Publish-Script cmdlets on PowerShell Core Edition

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShellGetv2#25]
_From @raghushantha on August 8, 2016 18:50_

These cmdlets in PowerShellGet module take dependency on nuget.exe which is windows full sku specific

We need to rework the logic to use Nuget Client APIs so that the publish-\* cmdlets work on CorePowerShell

_Copied from original issue: PowerShell/PowerShell#1678_

**Comment by pcgeek86** [comment]
Any thoughts on prioritization for this? Would love to see the ability to publish modules from PowerShell Core. @bmanikm @SteveL-MSFT

**Comment by waffleshop** [comment]
+1

**Comment by SteveL-MSFT** [comment]
cc @KrishnaV-MSFT

**Comment by vors** [comment]
I'm amazed that it's still an issue.

I want to publish a new version of ZLocation https://ci.appveyor.com/project/vors/zlocation/build/0.2.0.104 and I have a build from a CI windows machine, but I don't have windows to publish it.
Current behavior is not only nuget, but essentially a 4+ Gb image of the windows OS.

**Comment by SteveL-MSFT** [comment]
I just did a simple test removing the check for $IsCoreCLR and also defining $IsNanoServer = $false (the current check is incorrect and should be changed to [this](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/CoreCLR/CorePsPlatform.cs#L78)).  Some problem with `Get-DSCResource` so I made `Get-ExportedDscResources` just return an empty array.  After this, `publish-module` worked just fine on PSCore6 Beta.5.

If I find some time from PSCore6 issues, maybe I'll submit a PR for this.

**Comment by SteveL-MSFT** [comment]
@vors unfortunately my fix only makes it work on PSCore6 on Windows, still not supported on non-Windows due to dependency on nuget.exe

**Comment by SteveL-MSFT** [comment]
Looks like my change only enables it for PSCore on Windows, so not a complete fix for non-Windows platforms.  No longer working on this.

**Comment by pcgeek86** [comment]
Is someone else taking ownership of this @SteveL-MSFT? What does this mean for the first launch version of PowerShell Core Edition?

**Comment by SteveL-MSFT** [comment]
@KrishnaV-MSFT can you comment on whether we will get support by the time 6.0.0 is done?

**Comment by bmanikm** [comment]
@SteveL-MSFT Could you please let us know the timelines for 6.0.0 release?
I will discuss with @KrishnaV-MSFT  to prioritize this work item for the first launch version of PowerShell Core Edition.

**Comment by SteveL-MSFT** [comment]
@bmanikm per our [blog](https://blogs.msdn.microsoft.com/powershell/2017/07/14/powershell-6-0-roadmap-coreclr-backwards-compatibility-and-more/), we're targeting release by end of this calendar year

**Comment by larssb** [comment]
Mayn. Dang! I guess I have to bootup a Docker Container (when Linux/MacOS can run Windows containers) or a VM or something like that on my non-Windows so that I can publish modules and script to a private package management server I've setup. I really hope that the publish-module and publish-script cmdlets will become available in the RTM release of PS v6.

Fingers crossed :-)

**Comment by vors** [comment]
Common, it's like been a year since the issue is opened :(

**Comment by bmanikm** [comment]
Community, please help us by contributing to this.

**Comment by larssb** [comment]
Hi community and @bmanikm 

Now, PowerShellGet is a pretty big PowerShell project. In regards to lines of code. But I thought, what the heck. Let me give it a look.

So here is my cup of "wisdom":
_The issue is with PowerShellGet relying on nuget.exe. NuGet is available on MacOS (I think on Linux as well) and looks to have the same commands as the version for Windows. Meaning:_

- We should be able to use much the same logic for locating nuget on MacOS as for Windows.
-- Just need to change some nuts and bolts in regards to MacOS specifics.
-- Need to update and use $IsMacOS variable for deriving OS.
- Then, when the correct nuget is found simply use that with:
-- no "-" (hyphen) on the parameters when on MacOS (likely the same for Linux)
-- still use "-" (hyphen) on the parameters when on Windows

I could give it a go. However, I'm pretty new to pull requests and this repo. in general, so besides reading the contribution guidelines is there anything else I should be aware of?

Thank you.

**Comment by bmanikm** [comment]
Thanks @larssb, when you submit a pull request, you will have to complete the Contribution License Agreement at https://cla.microsoft.com.

Yes, NuGet can also be run on Mac OSX and Linux using [Mono](https://docs.microsoft.com/en-us/nuget/guides/install-nuget#nuget-cli), or through the [.NET Core CLI (dotnet)](https://docs.microsoft.com/en-us/nuget/tools/dotnet-commands). I think, for PowerShell Core we need to use [dotnet commands](https://docs.microsoft.com/en-us/nuget/tools/dotnet-commands) for pack and push operations.

**Comment by larssb** [comment]
Hi @bmanikm et. al.

I've had a solid look at this the today and yesterday. It is not as easy peasy as I hoped. Some issues has been pacthed (in a raw way) others worked around in order to use dotnet on MacOS and Linux with PowerShellGet. However, there is still ways to go. But. I don't have the required knowledge of dotnet core, .csproj files and such. Currently the exact status is that dotnet pack fails (see: [L8793](https://github.com/larssb/PowerShellGet/blob/21f38cefc7717d3c183606a811845b6e059ff08c/PowerShellGet/PSModule.psm1#L8793) as it does not accept .nuspec files directly. 
So I need help here. On:

- How to attack this.
- The creation of a .csproj file to use together with the .nuspec file (if that is the right approach)

Please have a look at > [Raw dotnet core compatibility commit](https://github.com/larssb/PowerShellGet/commit/21f38cefc7717d3c183606a811845b6e059ff08c#diff-a0fd27dd308ebc43f1fa495f0ec95d05R8793) --- give feedback on the code and feel free to assist me on this. 

Thank you very much.

N.B. If I need to explain in greater detail, please let me know.

**Comment by bmanikm** [comment]
Thanks @larssb! Yes, this is not a simple work item.
Yes, the creation of a .csproj file to use together with the .nuspec file is the right approach.

There are few other scenarios we need to handle here. 
In my fork, I have made the required changes to enable the publish cmdlets on PWSH using dotnet commands. Please take a look at my 'in-progress' changes at https://github.com/bmanikm/PowerShellGet/commit/12a18df79b2df18984a928fb31d1e9c2ae477b21 .

I have tested the changes on Windows PWSH. If possible, please try out on MacOS or Linux, and let me know the issues, if any.

**Work pending**:
- Validate Publish cmdlets on Linux and MacOS
- Add checks for dotnet command availability
- Update prompt logic for NuGet.exe to include dotnet command availability
- Enable dotnet command usage on Windows PowerShell too.
- Enable all the publish tests on PWSH


**Question to the community**:
Should we enable bootstrapping of dotnet on PWSH after user accepting the bootstrap prompt?
For now I am thinking that user will have to manually install the dotnet. In future, based on the community feedback, we can enable automatic bootstrapping of dotnet.

**Comment by bmanikm** [comment]
Thanks @larssb! Yes, this is not a simple work item.
Yes, the creation of a .csproj file to use together with the .nuspec file is the right approach.

There are few other scenarios we need to handle here. 
In my fork, I have made the required changes to enable the publish cmdlets on PWSH using dotnet command. Please take a look at my 'in-progress' changes at https://github.com/bmanikm/PowerShellGet/commit/12a18df79b2df18984a928fb31d1e9c2ae477b21 .

I have tested the changes on Windows PWSH. If possible, please try out on MacOS or Linux, and let me know the issues, if any.

**Work pending**:
- Validate Publish cmdlets on Linux and MacOS
- Add checks for dotnet command availability
- Update prompt logic for NuGet.exe to include dotnet command availability
- Enable dotnet command usage on Windows PowerShell too.
- Enable all the publish tests on PWSH


**Question to the community**:
Should we enable bootstrapping of dotnet on PWSH after user accepting the bootstrap prompt?
For now I am thinking that user will have to manually install the dotnet. In future, based on the community feedback, we can enable automatic bootstrapping of dotnet.

**Comment by vors** [comment]
I think a manual install step is totally fine as a first version. Ideally it should be a copy-pastable one-liner, but in dotnet world it always can break...

**Comment by larssb** [comment]
Hi @bmanikm,

Just had a go at your fork > [bmanikm fork](https://github.com/bmanikm/PowerShellGet/commit/12a18df79b2df18984a928fb31d1e9c2ae477b21).

- It works! Wonderful, fan-freaking-tastic 👍 I can now use publish-module on PWSH v6 beta 9.

Just needed to do theese two fixes:

<img width="1376" alt="screen shot 2017-11-15 at 21 53 56" src="https://user-images.githubusercontent.com/5261530/32859760-b8d55f32-ca4f-11e7-8681-1f5bbb42b975.png">

- So basically parenthesis around the two Join-Path cmdlets. In order for the call to System.Management.Automation.Platform to be performed and typecasted to a string that the Join-Path cmdlet can handle.

So if all tests come through I guess we can soon see an updated PowerShellGet on PSGallery?

Thank you and as @vors I also think a manual install step is okay for now.

And an updated version of your to-do list:
- [X] Validate Publish cmdlets on MacOS
- [ ] Validate Publich cmdlets on Linux
- [ ] Add checks for dotnet command availability
- [ ] Update prompt logic for NuGet.exe to include dotnet command availability
- [ ] Enable dotnet command usage on Windows PowerShell too.
- [ ] Enable all the publish tests on PWSH

**Comment by bmanikm** [comment]
@larssb thanks for validating the changes on MacOS. I have incorporated the above suggested change.
Yes, once the above to-do list is complete, we can publish the newer version of PowerShellGet to the PSGallery.

**Comment by bmanikm** [comment]
Submitted PR https://github.com/PowerShell/PowerShellGet/pull/196 for this.
