### ISSUE TITLE
Probably Small Feature Request: allow to install an already downloaded local nupkg file

### ISSUE THREAD

**Issue by schittli** [PowerShell/PowerShellGetv2#253]
## Expected Behavior
Hello
Because PowerShellGet is very limited on supported endpoints (anonymous and non-anonymous webdav, sftp, other https-Services), please allow us to:
1. download the .nupkg File ourselves
2. pass an array of the downloaded .nupkg full FileNames to PowerShellGet, so that it can install them
Something like:
```
Install-Package [<full .nupkg FileName[]>] -Scope <local|machine>
```
I don't know the internals. If there are e.g. missing dependencies, then please just return a list of those modules, so that we know which modules we have download and deliver additionally.

## Context
We have different customers and no one allows to use external PowerShell repositories and they decide which transfer protocol we can use to transfer and install packages. 

Therefore, we would like to use PowerShellGet but just replace the way nupkg files are transmitted.

## Your Environment
Windows. PowerShell 5.x

**Comment by dchauran** [comment]
If I understand your ask correctly, you can do this:

    Register-PackageSource -Name MySource -Location \\some\file\share -ProviderName NuGet
    Install-Module MyModule -Source MySource

**Comment by schittli** [comment]
Thank you very much, @dchauran, for your help!,

unfortunately, this does not solve the problem, because our customers and users are not willing to provide a Network-Share just to install a nupkg file:
- The End users do not know how to do this and almost never have the access rights, to do it. Therefore we have to ask the central IT:
- The central IT usually have complicated approval processes to set up network shares, and they will reject the request to set up a NuGet share, because it is a security risk and must be maintained - just for one Software manufacturer who needs it 3 times a year. 

Therefore, it would be great if we could ask NuGet to setup packages from a local directory.

**Comment by dchauran** [comment]
You can do the same for a local folder. How are you proposing that the users are going to get the nuget packages 3 times a year if they are not stored in a central location? You've ruled out websites and shares. What is the original source of the package then?

**Comment by schittli** [comment]
### Ohhh!, great!, I tried to register `C:\Temp` as a PackageSource location:
```
Register-PackageSource -Name LocalTemp -Location c:\Temp -ProviderName NuGet
```
and the registration works! (I was not yet able to test if the installation of a NuGet package really works).

### It's sad that this feature is not documented,
I'm pretty sure I always have read that self hosted Nuget package always must be a network share.
I guess that many other PowerShellGet Users would be happy to see that a local Directroy is supported, too.

### To answer your question: 
1. We are allowed to create 3-4 releases per year.
2. All releases are installed manually by our senior scientists, because we usually use this task to maintain the servers and databases.
3. It depends on the customer, how our Software gets to the target computer. In hospitals, for example, we transfer the installation files to their IT department, who check the packages and then copy it to the target computer for us so that we can install them.

Therefore it's great if we can use PowerShell and a local Repository like C:\Temp to automagically (or just: PowerShell :-)) provide tasks, and at the end, to just remove the local Repository again.


**Thank you very much, @dchauran, for your support.**
