### ISSUE TITLE
Let Register-PsRepository correctly wrap NuGet

### ISSUE THREAD

**Issue by RemcoKapinga** [PowerShell/PowerShellGetv2#254]
`Register-PsRepository` can work with multiple PackageProviders. The current usage scenario for `NuGet` based repositories is not complete. 
- Users must manually register the underlying NuGet repository (`nuget sources add`) when attempting to use `Publish-Module'. 
- When Credentials are provided to `Register-PsRepository`, they are not passed on for later use, but must be provided again when using `Find-Module`, `Install-Module` etc...

## Expected Behavior
`Register-PsRepository` should "just work", no extra work required when using NuGet or needing Credentials.

`Register-PsRepository -PackageManagementProvider 'NuGet' -Credential $credential` should completely wrap the underlying NuGet repository creation, including storing of supplied credentials (passing them on to NuGet when using `Find-Module` etc..).

After using `Register-PsRepository`, the PowerShell repository can be used like any other. `Find-Module`, 'Install-Module`, `Publish-Module` etc.. work correctly, without requiring extra work or passing on the earlier specified repository credentials.

## Current Behavior
Using PowerShell repositories based on NuGet require a lot of extra work and it doesn't work as intended or expected.

This case is prevalent when using VSTS package management, which is based on NuGet and requires credentials (a personal access token). When trying to use `Publish-Module`, the user must manually register the NuGet source to be able to publish.

When using multiple repositories, potentially requiring different credentials, searching over these repositories using `Find-Module` becomes impossible.

The errors that are generated when the user did not complete the manual setup are confusing, not helpful.

## Possible Solution
- Let `Register-PsRepository` register the underlying NuGet repository correctly, including storing credentials locally and with NuGet.
- Let commands that use a NuGet bases repository re-add the NuGet source when it is missing or registration is incorrect (based on earlier stored settings).
- Let `Register-PsRepository` store the credentials when specified, and pass them on to NuGet when later using `Find-Module` etc..
- Make this symmetrical with `Unregister-Psrepository`

## Steps to Reproduce (for bugs)
Note the issues with VSTS package management, for example #245 and issues linked from there.

## Context

```
> $PsVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.2125
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2125
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

> Get-Module -ListAvailable PowerShellGet,PackageManagement

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.7.0    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}
Script     1.6.0      PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
Script     1.5.0.0    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
Script     1.1.3.2    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
Script     1.1.3.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
Script     1.1.2.0    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
Script     1.1.1.0    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
Script     1.1.0.0    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}

> Get-PackageProvider

Name                     Version          DynamicOptions
----                     -------          --------------
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFile, SkipVali...
PowerShellGet            1.6.0.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate, AllowPrereleaseVersions, Fil...
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent

> Get-PackageProvider -ListAvailable

Name                     Version          DynamicOptions
----                     -------          --------------
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
nuget                    2.8.5.208
nuget                    2.8.5.207
nuget                    2.8.5.206
nuget                    2.8.5.205
nuget                    2.8.5.204
nuget                    2.8.5.202
nuget                    2.8.5.201
nuget                    2.8.5.127
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFile, SkipVali...
PowerShellGet            1.6.0.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate, AllowPrereleaseVersions, Fil...
PowerShellGet            1.5.0.0
PowerShellGet            1.1.3.2
PowerShellGet            1.1.3.1
PowerShellGet            1.1.2.0
PowerShellGet            1.1.1.0
PowerShellGet            1.1.0.0
PowerShellGet            1.0.0.1
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent
```

**Comment by jwittner** [comment]
Ran into this today. `Publish-Module` gave us a false positive when publishing to our VSTS package feed - it would log success, but the package would not show up on the feed. That led me to searching this repo and finding this issue. 

Using `nuget sources add` got me a step farther - now it would fail with a 401 despite us passing in credentials to Publish-Module. After using `nuget sources add -username -password` our modules are now properly being pushed to our VSTS package feed.

**Comment by JustinGrote** [comment]
Here's how I would ideally like to see this, and since it is up-for-grabs I may attempt an implementation.

No need to reinvent the wheel. Azure Artifacts provides a credential manager that automates the whole credential process and supports two-factor authentication: https://github.com/Microsoft/artifacts-credprovider

Unfortunately it requires nuget v3 API support, v2 can only do PAT, but the provider can still be called directly to fetch a PAT and that could be used in "normal" packagemanagement requests.

So short-term work would be cleaning up the v2 story, such that there should be no need to go down to `nuget sources add` for the repository

An interim solution is integrating the Azure Artifacts credential provider since it can be called standalone from nuget.exe, and use it for the purpose of fetching the PAT from a username/Password/2FA scenario, and storing it for the designated lifetime. This could also be done directly against the APIs but again, no need to reinvent the wheel.

Long-term would be gaining v3 support, which would be dependent on OneGet adding support, and integrating the Azure Artifacts credential provider at the oneget source so that dependency flows down to PowershellGet, I don't really see that realistically happening thought it would be the most sensible place for that to be integrated.

**Comment by alerickson** [comment]
Resolved with https://github.com/OneGet/oneget/pull/442
