### ISSUE TITLE
Update-Help doesn't work due to HTTPS in HelpInfoUri

### ISSUE THREAD

**Issue by favorini** [PowerShell/PowerShellGetv2#269]
Update-Help doesn't work due to HTTPS in HelpInfoUri. This was fixed in #82 and broken again in #195.

```
Update-Help : Failed to update Help for the module(s) :
'PowerShellGet'
The HelpInfoURI https://go.microsoft.com/fwlink/?linkid=855963 does not start with HTTP.
At line:1 char:1
+ Update-Help -Module PowerShellGet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (HelpInfoUri:Uri) [Update-Help], Exception
    + FullyQualifiedErrorId : InvalidHelpInfoUriFormat,Microsoft.PowerShell.Commands.UpdateHelpCommand
```

**Comment by bmanikm** [comment]
@favorini Please confirm whether this is happening on PS 3.0, 4.0, or 5.0. Update-Help with HTTPS in HelpInfoUri is working fine on PS 5.1 and newer versions.

@SteveL-MSFT As PowerShellGet module help needs to work on PS 3.0 and newer versions, it looks like we will have to specify HTTP in HelpInfoUri for this module. Please let us know if there are any other options.

**Comment by SteveL-MSFT** [comment]
@bmanikm I don't believe we require HTTPS, that's more of a matter of principle from a security standpoint (@adityapatwardhan to correct me if I'm wrong).  Might be ok to have it as HTTP for now if you need to support PSv3.

**Comment by ldjones316** [comment]
Error: Update-Help -Module DFSR -Verbose
Update-Help : Failed to update Help for the module(s) :
'DFSR'
The HelpInfoURI "https://aka.ms/winsvr-2022-pshelp does not start with HTTP.
At line:1 char:1
+ Update-Help -Module DFSR -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (HelpInfoUri:Uri) [Update-Help], Exception
    + FullyQualifiedErrorId : InvalidHelpInfoUriFormat,Microsoft.PowerShell.Commands.UpdateHelpCommand

OS Info:
WnOS = Windows Server 2022 Standard v.10.0.20348.2227
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.20348.2227
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.20348.2227}
BuildVersion                   10.0.20348.2227
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
