### ISSUE TITLE
Display ReleaseNotes from module manifest after successful installation

### ISSUE THREAD

**Issue by cormacpayne** [PowerShell/PowerShellGetv2#277]
To improve discoverability of features in new versions of a module, it would be nice if, when the user installs (or updates to) some version of a module, the `ReleaseNotes` field from that module's manifest file is displayed to the screen. This allows the user to easily see what was added/changed/removed in the version of the module they just installed. Currently, as far as I'm aware, the only way for the user to access this information is to view it in the PowerShell Gallery or from the `.psd1` file installed as a part of the command execution.

This can be something that the user opts into with a `IncludeReleaseNotes` switch parameter on the `Install-Module` and `Update-Module` commands:

```powershell
PS C:\> Install-Module -Name AzureRM.Profile -RequiredVersion 5.0.1 -Repository PSGallery

PS C:\> Install-Module -Name AzureRM.Profile -RequiredVersion 5.0.1 -Repository PSGallery -IncludeReleaseNotes

Release Notes
* Fix issue where default environments weren't being retrieved without a default context set
```

**Comment by bmanikm** [comment]
@cormacpayne Have you tried using Get-InstalledModule cmdlet? You can also find this info on Find-Module output.
`(Get-InstalledModule AzureRM.Profile).ReleaseNotes`

**Comment by cormacpayne** [comment]
@bmanikm my concern is about discoverability for new users, or even PowerShell users who may not be familiar with these commands. Someone who just updated to a new version of `AzureRM` may want to know what was added/changed/removed, and it seems like that information should appear for them when they install the module rather than them having to go out of their way to obtain that information (be it from a separate cmdlet call or on the PowerShell Gallery).

I think having a check for the switch parameter mentioned above after [this line](https://github.com/PowerShell/PowerShellGet/blob/development/PowerShellGet/public/psgetfunctions/Install-Module.ps1#L260) to display the corresponding release notes would be beneficial for users who may not know that the release notes exist in the `.psd1` file or how to get that information.

```powershell
...
$null = PackageManagement\Install-Package @PSBoundParameters
if ($IncludeReleaseNotes.IsPresent)
{
    # Get module manifest of installed module and display release notes
}
```

**Comment by bmanikm** [comment]
Users would need to discover the details from Find-Module output then run Install-Module or Update-Module to get it. Install-Module and Update-Module won't return any output as user wanted to install or update the specified item. Let us see how many users want this functionality.

**Comment by ghost** [comment]
Hi Cormac - thanks for the suggestion, but as stated (doing it automatically) it's not one that fits within the main goals for PowerShellGet. Release notes can be extremely large blocks of text. PSGet cmdlets are heavily used, and largely targeted, at automation and CI/CD pipeline scenarios. 
In general, PowerShell encourages users to leverage things like pipelining to solve this class of problem. In this case (thanks, bmanikm) the command would be:

```PowerShell
Find-Module PowerShellGet | Format-List ReleaseNotes

```
