### ISSUE TITLE
The Nuget.exe that PowerShellGet installs is outdated and doesn't function with modern TLS suites

### ISSUE THREAD

**Issue by rsteenwyk** [PowerShell/PowerShellGetv2#288]
## Expected Behavior

When running PowershellGet for the first time and it determines it needs Nuget.exe CLI tool in C:\ProgramData\Microsoft\Windows\PowerShell\PowerShellGet\ it should download a more recent version of the binary, such as version 4.6.2.5055.

## Current Behavior
When you first run "Publish-Module" for example, and you don't already have a Nuget.exe in the path that PowerShellGet looks for it, it will give the user the option to automatically download the Nuget provider. When it does so, it downloads Nuget.exe version 2.8.60717.93.

## Possible Solution
Update the URL at https://github.com/PowerShell/PowerShellGet/blob/da8e09392bb52ae6512bfc9782ffdab85a35d0d4/PowerShellGet/private/modulefile/PartOne.ps1#L159 to point to a newer edition of Nuget.exe.

## Steps to Reproduce (for bugs)
1. Run "Publish-Module" when it prompts you to automatically install Nuget.exe accept it.
2. Check the path where it downloaded to (in my Server 2016 environment that is C:\ProgramData\Microsoft\Windows\PowerShell\PowerShellGet\)
3. Check the version of Nuget.exe, you will see it is version 2.8.60717.93

## Context
This caused me a lot of pain over the past two days as I attempted to track down what was causing Publish-Module to fail with error:

"Publish-PSArtifactUtility : Failed to publish module 'MyModule': 'The request was aborted: Could not create SSL/TLS secure channel."

At first I thought something was wrong with my cipher suite setup on my Server 2016 box. But I have tracked it down to Nuget.exe being so old that it does not support more modern TLS ciphers. See: 
https://github.com/NuGet/NuGet.Client/pull/330 and https://github.com/NuGet/Home/issues/2253

## Your Environment
```PowerShell

> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.2248
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2248
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

> Get-Module -ListAvailable PowerShellGet,PackageManagement
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.7.2    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}
Script     1.6.5      PowerShellGet                       {Find-Command, Find-DSCResource, Find-Module, Find-RoleCapability...}
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}

> Get-PackageProvider -ListAvailable
Name                     Version          DynamicOptions
----                     -------          --------------
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
nuget                    2.8.5.208
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFile, Sk...
PowerShellGet            1.6.5.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate, AllowPrereleaseVersion...
PowerShellGet            1.0.0.1
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent
```

**Comment by rsteenwyk** [comment]
I have verified that manually replacing the old v2.8 version of Nuget.exe in C:\ProgramData\Microsoft\Windows\Powershell\PowerShellGet\ with Nuget.exe version 4.6.2.5055 does resolve the issue with Publish-Module.

**Comment by alerickson** [comment]
@rsteenwyk I'm working on this right now.

**Comment by rsteenwyk** [comment]
Awesome, glad to hear that @alerickson. Let me know if there is anything I can do to assist.

**Comment by alerickson** [comment]
@rsteenwyk  This is fixed in the new release-- https://www.powershellgallery.com/packages/PowerShellGet/1.6.6
