### ISSUE TITLE
Publishing module 0.10.0 fails

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShellGetv2#290]
Publishing the module `0.10.0` to PSGallery fails, if module `0.9.0` is already published.

## Expected Behavior

Publishing succeeds, `0.10.0` is the latest version.

## Current Behavior

```
Publish-Module : Module 'platyPS' with version '0.10.0' cannot be published. The version must exceed the current version '0.9.0' that exists in the repository 'https://www.powershellgallery.com/api/v2/', or you must specify -Force.
At line:1 char:1
+ Publish-Module -name platyPS -RequiredVersion 0.10.0 -Verbose -NuGetA ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Publish-Module], InvalidOperationException
+ FullyQualifiedErrorId : ModuleVersionShouldBeGreaterThanGalleryVersion,Publish-Module
```

## Possible Solution

Don't compare strings, compare version objects.

Workaround: use `-Force`, once the package is on the server everything works fine.

## Steps to Reproduce (for bugs)

1. Publish some package to the gallery with version `0.9.0`
2. Try to publish packag with version `0.10.0`

## Context

Tried to publish platyPS release https://github.com/PowerShell/platyPS/releases

## Your Environment

```PowerShell

> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.2
PSEdition                      Core
GitCommitId                    v6.1.0-preview.2
OS                             Darwin 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEAS...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by vors** [comment]
This is especially unexpected to see in the presence of issues like #88 that suggests that semantic versioning with `x.y.z` format is enforced in the publishing.

**Comment by bmanikm** [comment]
@vors  This issue got resolved with PR #219 for issue #217. Please try with [the latest version of PowerShellGet](https://www.powershellgallery.com/packages/PowerShellGet).

**Comment by vors** [comment]
👍

**Comment by vors** [comment]
@bmanikm hm, one thing I wanted to double-check: I'm using fairly recent pwsh package (6.1.0-preview.2). The issue been fixed in January. I wonder why the PowerShellGet version that is shipped in 6.1.0-preview.2 is so old?

**Comment by bmanikm** [comment]
@vors 1.6.0 is the expected and correct version of PowerShellGet in the pwsh package (6.1.0-preview.2).
1.6.5 version of PowerShellGet got released on May 17, 2018, and it will be included in the next release of the pwsh package.

**Comment by vors** [comment]
awesome, thank you!
