### ISSUE TITLE
dotnet.exe : Unrecognized command or argument 

### ISSUE THREAD

**Issue by ghost** [PowerShell/PowerShellGetv2#295]
```
dotnet.exe : Unrecognized command or argument '/p:StagingPath=C:\Users\AS_WZJR59\AppData\Local\Temp\2\1397200041\Osprey'
At C:\Program Files\WindowsPowerShell\Modules\PowershellGet\1.6.5\PSModule.psm1:5790 char:23
+             $output = & $script:DotnetCommandPath $arguments
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unrecognized co...7200041\Osprey':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Publish-PSArtifactUtility : Failed to generate the compressed file for module 'Specify --help for a list of available options and commands.'.
At C:\Program Files\WindowsPowerShell\Modules\PowershellGet\1.6.5\PSModule.psm1:10691 char:17
+ ...             Publish-PSArtifactUtility @PublishPSArtifactUtility_Param ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : FailedToCreateCompressedModule,Publish-PSArtifactUtility
 
```

**Comment by bmanikm** [comment]
@rachaeldeja Can you please provide more details to reproduce the reported issue? 
What version of dotnet you have on your machine?  `dotnet --version`

**Comment by ghost** [comment]
1.0.0-preview2-003131

**Comment by ghost** [comment]
Ok I updated that... now I get

``Publish-PSArtifactUtility` : Failed to generate the compressed file for module 'Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.6.5\PSModule.psm1:10691 char:17
+ ...             Publish-PSArtifactUtility @PublishPSArtifactUtility_Param ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : FailedToCreateCompressedModule,Publish-PSArtifactUtility``

**Comment by bmanikm** [comment]
Please try with the 2.0.0 version of dotnet or install NuGet.exe using one of the below commands on Windows.

```PowerShell
# Non-admin
Invoke-WebRequest -Uri https://aka.ms/psget-nugetexe -OutFile "$env:LOCALAPPDATA\Microsoft\Windows\PowerShell\PowerShellGet\NuGet.exe"
 
# Admin
Invoke-WebRequest -Uri https://aka.ms/psget-nugetexe -OutFile "$env:ProgramData\Microsoft\Windows\PowerShell\PowerShellGet\NuGet.exe"
```

**Comment by ghost** [comment]
I did see above

**Comment by bmanikm** [comment]
Can your retry after installing the NuGet.exe using one of command provided above?
To investigate further on the error from dotnet cli, please provide the consistent repro steps.

**Comment by ghost** [comment]
Now I'm getting ... (I can register the repository without issue and I can find modules without issue)

Publish-PSArtifactUtility : Failed to publish module 'Osprey': 'The underlying connection was closed: An unexpected error occurred on a send.
'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.6.0\PSModule.psm1:1447 char:17
+ ...             Publish-PSArtifactUtility @PublishPSArtifactUtility_Param ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : FailedToPublishTheModule,Publish-PSArtifactUtility

**Comment by bmanikm** [comment]
Can you get the verbose and debug messages from the publish-module command?
To which repository you are trying to publish your module? 

Take a look at https://stackoverflow.com/questions/26928191/the-underlying-connection-was-closed-an-unexpected-error-occurred-on-a-send .

**Comment by ghost** [comment]
PS C:\Users\wzjr59>         Publish-Module -Name $path -Repository "SPENGGallery" -NuGetApiKey VSTS -Force -Verbose -RequiredVersion 1.0.1 -Debug
DEBUG: 00:00:00.0000004 Calling New() : MethodName = 'ResolvePackageSources'
DEBUG: 00:00:00.0000800 ErrorVariable: ev
DEBUG: 00:00:00.0001304 Name: SPENGGallery
DEBUG: 00:00:00.0018309 INVOKING PowerShell Fn Resolve-PackageSource with args  that has length 0
DEBUG: 00:00:00.0038699 In PowerShellGet Provider - 'Resolve-PackageSource'.
DEBUG: 00:00:00.0093501 Yielding package source for SPENGGallery at location https://tfs.gm.com/tfs/EUE/_packaging/SPENGGalle
ry/nuget/v2
DEBUG: 00:00:00.0113173 Done calling powershell «Resolve-PackageSource» «PSModule»
DEBUG: 00:00:00.0231462 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0233198 ErrorVariable: ev
DEBUG: 00:00:00.0234482 Name: SPENGGallery
DEBUG: 00:00:00.0250281 INVOKING PowerShell Fn Get-DynamicOptions with args Provider that has length 1
DEBUG: 00:00:00.0268878 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0318830 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0490781 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0491429 ErrorVariable: ev
DEBUG: 00:00:00.0491877 Name: SPENGGallery
DEBUG: 00:00:00.0506584 INVOKING PowerShell Fn Get-DynamicOptions with args Source that has length 1
DEBUG: 00:00:00.0522437 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0753546 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:01.2354195 Calling New() : MethodName = 'ResolvePackageSources'
DEBUG: 00:00:01.2362659 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:01.2366848 ProviderName: PowerShellGet
DEBUG: 00:00:01.2398585 Name: SPENGGallery
DEBUG: 00:00:01.2407574 ErrorVariable: ev
DEBUG: 00:00:01.2419061 INVOKING PowerShell Fn Resolve-PackageSource with args  that has length 0
DEBUG: 00:00:01.2432587 In PowerShellGet Provider - 'Resolve-PackageSource'.
VERBOSE: Repository details, Name = 'SPENGGallery', Location = 'https://tfs.gm.com/tfs/EUE/_packaging/SPENGGallery/nuget/v2';
 IsTrusted = 'True'; IsRegistered = 'True'.
DEBUG: 00:00:01.2458318 Yielding package source for SPENGGallery at location https://tfs.gm.com/tfs/EUE/_packaging/SPENGGalle
ry/nuget/v2
DEBUG: 00:00:01.2473465 Done calling powershell «Resolve-PackageSource» «PSModule»
DEBUG: 00:00:01.2522343 Calling New() : MethodName = 'ResolvePackageSources'
DEBUG: 00:00:01.2531820 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:01.2540472 ProviderName: PowerShellGet
DEBUG: 00:00:01.2548915 Name: SPENGGallery
DEBUG: 00:00:01.2557457 ErrorVariable: ev
DEBUG: 00:00:01.2567274 INVOKING PowerShell Fn Resolve-PackageSource with args  that has length 0
DEBUG: 00:00:01.2582581 In PowerShellGet Provider - 'Resolve-PackageSource'.
VERBOSE: Repository details, Name = 'SPENGGallery', Location = 'https://tfs.gm.com/tfs/EUE/_packaging/SPENGGallery/nuget/v2';
 IsTrusted = 'True'; IsRegistered = 'True'.
DEBUG: 00:00:01.2637424 Yielding package source for SPENGGallery at location https://tfs.gm.com/tfs/EUE/_packaging/SPENGGalle
ry/nuget/v2
DEBUG: 00:00:01.2648407 Done calling powershell «Resolve-PackageSource» «PSModule»
VERBOSE: Publish Location:'https://tfs.gm.com/tfs/EUE/_packaging/SPENGGallery/nuget/v2'.
VERBOSE: Module 'Osprey' was found in 'C:\Users\wzjr59\Documents\WindowsPowerShell\Modules\Osprey\1.0.1'.
VERBOSE: Loading module from path 'C:\Users\wzjr59\AppData\Local\Temp\1027623738\Osprey\Osprey.psm1'.
DEBUG: 00:00:00.0000008 Calling New() : MethodName = 'ResolvePackageSources'
DEBUG: 00:00:00.0001583 Verbose: False
DEBUG: 00:00:00.0002588 Name: SPENGGallery
DEBUG: 00:00:00.0003515 ErrorVariable: ev
DEBUG: 00:00:00.0029944 INVOKING PowerShell Fn Resolve-PackageSource with args  that has length 0
DEBUG: 00:00:00.0118609 In PowerShellGet Provider - 'Resolve-PackageSource'.
DEBUG: 00:00:00.0170125 Yielding package source for SPENGGallery at location https://tfs.gm.com/tfs/EUE/_packaging/SPENGGalle
ry/nuget/v2
DEBUG: 00:00:00.0184767 Done calling powershell «Resolve-PackageSource» «PSModule»
DEBUG: 00:00:00.0277518 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0278067 Verbose: False
DEBUG: 00:00:00.0278375 Name: SPENGGallery
DEBUG: 00:00:00.0278666 ErrorVariable: ev
DEBUG: 00:00:00.0289436 INVOKING PowerShell Fn Get-DynamicOptions with args Provider that has length 1
DEBUG: 00:00:00.0301571 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0320562 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0405214 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0405760 Verbose: False
DEBUG: 00:00:00.0406043 Name: SPENGGallery
DEBUG: 00:00:00.0406268 ErrorVariable: ev
DEBUG: 00:00:00.0414757 INVOKING PowerShell Fn Get-DynamicOptions with args Source that has length 1
DEBUG: 00:00:00.0423249 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0449218 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:01.2422565 Calling New() : MethodName = 'ResolvePackageSources'
DEBUG: 00:00:01.2431853 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:01.2440419 ProviderName: PowerShellGet
DEBUG: 00:00:01.2448825 Verbose: False
DEBUG: 00:00:01.2457543 Name: SPENGGallery
DEBUG: 00:00:01.2461990 ErrorVariable: ev
DEBUG: 00:00:01.2473654 INVOKING PowerShell Fn Resolve-PackageSource with args  that has length 0
DEBUG: 00:00:01.2483484 In PowerShellGet Provider - 'Resolve-PackageSource'.
DEBUG: 00:00:01.2507902 Yielding package source for SPENGGallery at location https://tfs.gm.com/tfs/EUE/_packaging/SPENGGalle
ry/nuget/v2
DEBUG: 00:00:01.2518622 Done calling powershell «Resolve-PackageSource» «PSModule»
DEBUG: 00:00:01.2605289 Calling New() : MethodName = 'ResolvePackageSources'
DEBUG: 00:00:01.2613687 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:01.2622044 ProviderName: PowerShellGet
DEBUG: 00:00:01.2631201 Verbose: False
DEBUG: 00:00:01.2640641 Name: SPENGGallery
DEBUG: 00:00:01.2649166 ErrorVariable: ev
DEBUG: 00:00:01.2658946 INVOKING PowerShell Fn Resolve-PackageSource with args  that has length 0
DEBUG: 00:00:01.2670224 In PowerShellGet Provider - 'Resolve-PackageSource'.
DEBUG: 00:00:01.2746339 Yielding package source for SPENGGallery at location https://tfs.gm.com/tfs/EUE/_packaging/SPENGGalle
ry/nuget/v2
DEBUG: 00:00:01.2758474 Done calling powershell «Resolve-PackageSource» «PSModule»
DEBUG: 00:00:00.0000004 Calling New() : MethodName = 'ResolvePackageSources'
DEBUG: 00:00:00.0000894 Verbose: False
DEBUG: 00:00:00.0001481 Name: SPENGGallery
DEBUG: 00:00:00.0002018 ErrorVariable: ev
DEBUG: 00:00:00.0021316 INVOKING PowerShell Fn Resolve-PackageSource with args  that has length 0
DEBUG: 00:00:00.0038621 In PowerShellGet Provider - 'Resolve-PackageSource'.
DEBUG: 00:00:00.0090432 Yielding package source for SPENGGallery at location https://tfs.gm.com/tfs/EUE/_packaging/SPENGGalle
ry/nuget/v2
DEBUG: 00:00:00.0109275 Done calling powershell «Resolve-PackageSource» «PSModule»
DEBUG: 00:00:00.0242884 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0243696 Verbose: False
DEBUG: 00:00:00.0244209 Name: SPENGGallery
DEBUG: 00:00:00.0244685 ErrorVariable: ev
DEBUG: 00:00:00.0261583 INVOKING PowerShell Fn Get-DynamicOptions with args Provider that has length 1
DEBUG: 00:00:00.0279778 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0309805 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0459569 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0460361 Verbose: False
DEBUG: 00:00:00.0460923 Name: SPENGGallery
DEBUG: 00:00:00.0461460 ErrorVariable: ev
DEBUG: 00:00:00.0477875 INVOKING PowerShell Fn Get-DynamicOptions with args Source that has length 1
DEBUG: 00:00:00.0494047 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0548595 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:02.0005760 Calling New() : MethodName = 'ResolvePackageSources'
DEBUG: 00:00:02.0015638 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:02.0025522 ProviderName: PowerShellGet
DEBUG: 00:00:02.0035314 Verbose: False
DEBUG: 00:00:02.0045107 Name: SPENGGallery
DEBUG: 00:00:02.0049993 ErrorVariable: ev
DEBUG: 00:00:02.0067220 INVOKING PowerShell Fn Resolve-PackageSource with args  that has length 0
DEBUG: 00:00:02.0087655 In PowerShellGet Provider - 'Resolve-PackageSource'.
DEBUG: 00:00:02.0117780 Yielding package source for SPENGGallery at location https://tfs.gm.com/tfs/EUE/_packaging/SPENGGalle
ry/nuget/v2
DEBUG: 00:00:02.0130367 Done calling powershell «Resolve-PackageSource» «PSModule»
DEBUG: 00:00:02.0216635 Calling New() : MethodName = 'ResolvePackageSources'
DEBUG: 00:00:02.0226757 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:02.0237255 ProviderName: PowerShellGet
DEBUG: 00:00:02.0247232 Verbose: False
DEBUG: 00:00:02.0257079 Name: SPENGGallery
DEBUG: 00:00:02.0266896 ErrorVariable: ev
DEBUG: 00:00:02.0278117 INVOKING PowerShell Fn Resolve-PackageSource with args  that has length 0
DEBUG: 00:00:02.0290765 In PowerShellGet Provider - 'Resolve-PackageSource'.
DEBUG: 00:00:02.0319031 Yielding package source for SPENGGallery at location https://tfs.gm.com/tfs/EUE/_packaging/SPENGGalle
ry/nuget/v2
DEBUG: 00:00:02.0331569 Done calling powershell «Resolve-PackageSource» «PSModule»
DEBUG: 00:00:00.0000004 Calling New() : MethodName = 'ResolvePackageSources'
DEBUG: 00:00:00.0000787 ErrorAction: SilentlyContinue
DEBUG: 00:00:00.0001308 WarningAction: SilentlyContinue
DEBUG: 00:00:00.0001780 Source: SPENGGallery
DEBUG: 00:00:00.0002223 Debug: True
DEBUG: 00:00:00.0002666 Verbose: True
DEBUG: 00:00:00.0003109 Name: Osprey
DEBUG: 00:00:00.0018071 INVOKING PowerShell Fn Resolve-PackageSource with args  that has length 0
DEBUG: 00:00:00.0033874 In PowerShellGet Provider - 'Resolve-PackageSource'.
DEBUG: 00:00:00.0081563 Yielding package source for SPENGGallery at location https://tfs.gm.com/tfs/EUE/_packaging/SPENGGalle
ry/nuget/v2
DEBUG: 00:00:00.0098182 Done calling powershell «Resolve-PackageSource» «PSModule»
DEBUG: 00:00:00.0318666 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0319831 ErrorAction: SilentlyContinue
DEBUG: 00:00:00.0320705 WarningAction: SilentlyContinue
DEBUG: 00:00:00.0321493 Source: SPENGGallery
DEBUG: 00:00:00.0322309 Debug: True
DEBUG: 00:00:00.0323126 Verbose: True
DEBUG: 00:00:00.0323987 Name: Osprey
DEBUG: 00:00:00.0373977 INVOKING PowerShell Fn Get-DynamicOptions with args Provider that has length 1
DEBUG: 00:00:00.0395401 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0431905 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0682515 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0683565 ErrorAction: SilentlyContinue
DEBUG: 00:00:00.0684320 WarningAction: SilentlyContinue
DEBUG: 00:00:00.0685005 Source: SPENGGallery
DEBUG: 00:00:00.0685715 Debug: True
DEBUG: 00:00:00.0686416 Verbose: True
DEBUG: 00:00:00.0687405 Name: Osprey
DEBUG: 00:00:00.0708131 INVOKING PowerShell Fn Get-DynamicOptions with args Source that has length 1
DEBUG: 00:00:00.0730273 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0789411 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.1081842 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.1082683 ErrorAction: SilentlyContinue
DEBUG: 00:00:00.1083290 WarningAction: SilentlyContinue
DEBUG: 00:00:00.1083828 Source: SPENGGallery
DEBUG: 00:00:00.1084369 Debug: True
DEBUG: 00:00:00.1084915 Verbose: True
DEBUG: 00:00:00.1085448 Name: Osprey
DEBUG: 00:00:00.1104008 INVOKING PowerShell Fn Get-DynamicOptions with args Package that has length 1
DEBUG: 00:00:00.1124156 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.1303430 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:01.3003164 Calling New() : MethodName = 'ResolvePackageSources'
DEBUG: 00:00:01.3011734 ProviderName: PowerShellGet
DEBUG: 00:00:01.3016062 WarningAction: SilentlyContinue
DEBUG: 00:00:01.3020206 Type: Module
DEBUG: 00:00:01.3028550 Source: SPENGGallery
DEBUG: 00:00:01.3059057 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:01.3067734 Name: Osprey
DEBUG: 00:00:01.3071935 Debug: True
DEBUG: 00:00:01.3080276 Verbose: True
DEBUG: 00:00:01.3088784 AllowPrereleaseVersions: True
DEBUG: 00:00:01.3093244 ErrorAction: SilentlyContinue
DEBUG: 00:00:01.3103131 INVOKING PowerShell Fn Resolve-PackageSource with args  that has length 0
DEBUG: 00:00:01.3112706 In PowerShellGet Provider - 'Resolve-PackageSource'.
VERBOSE: Repository details, Name = 'SPENGGallery', Location = 'https://tfs.gm.com/tfs/EUE/_packaging/SPENGGallery/nuget/v2';
 IsTrusted = 'True'; IsRegistered = 'True'.
DEBUG: 00:00:01.3140112 Yielding package source for SPENGGallery at location https://tfs.gm.com/tfs/EUE/_packaging/SPENGGalle
ry/nuget/v2
DEBUG: 00:00:01.3155086 Done calling powershell «Resolve-PackageSource» «PSModule»
DEBUG: 00:00:01.3156682 Calling SearchForPackages. Name='Osprey'
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
DEBUG: 00:00:01.3193572 PackageProvider::FindPackage with name Osprey
DEBUG: 00:00:01.3195984 Calling SearchForPackages After Select 1
DEBUG: 00:00:01.3247607 Calling New() : MethodName = 'FindPackage'
DEBUG: 00:00:01.3256103 ProviderName: PowerShellGet
DEBUG: 00:00:01.3260309 WarningAction: SilentlyContinue
DEBUG: 00:00:01.3268760 Type: Module
DEBUG: 00:00:01.3277133 Source: SPENGGallery
DEBUG: 00:00:01.3281293 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:01.3289638 Name: Osprey
DEBUG: 00:00:01.3298171 Debug: True
DEBUG: 00:00:01.3306725 Verbose: True
DEBUG: 00:00:01.3315308 AllowPrereleaseVersions: True
DEBUG: 00:00:01.3319496 ErrorAction: SilentlyContinue
DEBUG: 00:00:01.3329416 INVOKING PowerShell Fn Find-Package with args System.String[], , ,  that has length 4
DEBUG: 00:00:01.3344263 In PowerShellGet Provider - 'Find-Package'.
DEBUG: 00:00:01.3350298 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:01.3355451 OPTION: WarningAction => SilentlyContinue
DEBUG: 00:00:01.3364649 OPTION: Type => Module
DEBUG: 00:00:01.3373962 OPTION: Source => SPENGGallery
DEBUG: 00:00:01.3380013 OPTION: MessageResolver => Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:01.3389420 OPTION: Name => Osprey
DEBUG: 00:00:01.3394860 OPTION: Debug => True
DEBUG: 00:00:01.3415357 OPTION: Verbose => True
DEBUG: 00:00:01.3421457 OPTION: AllowPrereleaseVersions => True
DEBUG: 00:00:01.3425420 OPTION: ErrorAction => SilentlyContinue
VERBOSE: Using the specified source names : 'SPENGGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://tfs.gm.com/tfs/EUE/_packaging/SPENGGallery/nuget/v2' and PackageManagementProvide
r is 'NuGet'.
DEBUG: 00:00:01.3524883 PackageProvider::FindPackage with name Osprey
DEBUG: 00:00:01.3569490 Calling 'NuGet'::'FindPackage' - name='Osprey', requiredVersion='',minimumVersion='', maximumVersion=
'''.
DEBUG: 00:00:01.3582036 Iterating 'Osprey'.
DEBUG: 00:00:01.3597359 There are '0' registered sources in 'NuGet' provider.
DEBUG: 00:00:01.3617991 Source 'https://tfs.gm.com/tfs/EUE/_packaging/SPENGGallery/nuget/v2' is not one of the registered sou
rces in 'NuGet' provider.
DEBUG: 00:00:03.5605495 Source 'https://tfs.gm.com/tfs/EUE/_packaging/SPENGGallery/nuget/v2' is validated.
DEBUG: 00:00:03.5720158 Calling 'NuGetRequest'::'GetPackageById', 'Osprey'.
DEBUG: 00:00:04.3808317 Calling 'HttpClientPackageRepository'::'FindPackagesById', 'Osprey'.
DEBUG: 00:00:04.3845105 Calling 'NuGetClient'::'FindPackage'.
VERBOSE: Searching repository 'https://tfs.gm.com/tfs/EUE/_packaging/SPENGGallery/nuget/v2/FindPackagesById()?id='Osprey'' fo
r ''.
DEBUG: 00:00:04.3922627 Downloading 'https://tfs.gm.com/tfs/EUE/_packaging/SPENGGallery/nuget/v2/FindPackagesById()?id='Ospre
y'&$skip=0&$top=40'.
DEBUG: 00:00:04.9441263 Completed downloading 'https://tfs.gm.com/tfs/EUE/_packaging/SPENGGallery/nuget/v2/FindPackagesById()
?id='Osprey'&$skip=0&$top=40'.
DEBUG: 00:00:04.9537050 '0' packages received in the last request.
VERBOSE: Total package yield:'0' for the specified package 'Osprey'.
DEBUG: 00:00:04.9583761 Completed iterating for 'Osprey'.
DEBUG: 00:00:04.9603068 PowerShell Script 'PSModule' Function 'Find-Package' returns null.
DEBUG: 00:00:04.9632422 Done calling powershell «Find-Package» «PSModule»
DEBUG: 00:00:04.9658851 unmatched package name='Osprey'
Publish-PSArtifactUtility : Failed to publish module 'Osprey': 'The underlying connection was closed: An unexpected error 
occurred on a send.
'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.6.0\PSModule.psm1:1447 char:17
+ ...             Publish-PSArtifactUtility @PublishPSArtifactUtility_Param ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : FailedToPublishTheModule,Publish-PSArtifactUtility

**Comment by bmanikm** [comment]
It looks like you are publishing to a VSTS feed. Take a look at [VSTS feed](https://github.com/PowerShell/PowerShell-Docs/issues/1200) for more details.
