### ISSUE TITLE
Publish-Module throws error "Failed to generate the compressed file for module 'Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core'"

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/PowerShellGetv2#303]
I'm currently putting together a demo that involves publishing a module using Publish-Module to a target NuGet server. I'm currently experiencing this on MacOS 10.12.6. The command and output I see are below:

Publish-Module -Path MyCustomSolution -NuGetApiKey $APIKey -Repository PublishTarget -Verbose

    VERBOSE: Repository details, Name = 'PublishTarget', Location = 'http://SERVERNAME/nuget/modules/'; IsTrusted = 'True'; IsRegistered = 'True'.
    VERBOSE: Repository details, Name = 'PublishTarget', Location = 'http://SERVERNAME/nuget/modules/'; IsTrusted = 'True'; IsRegistered = 'True'.
    VERBOSE: Repository details, Name = 'PublishTarget', Location = 'http://SERVERNAME/nuget/modules/'; IsTrusted = 'True'; IsRegistered = 'True'.
    VERBOSE: Publish Location:'http://SERVERNAME/nuget/modules/'.
    VERBOSE: Loading module from path '/codebuild/output/src484376618/src/git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/PowerShellDemo/MyCustomSolution/CoreCommands.psm1'.
    VERBOSE: Module 'MyCustomSolution' was found in '/codebuild/output/src484376618/src/git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/PowerShellDemo/MyCustomSolution'.
    VERBOSE: Loading module from path '/tmp/128535449/MyCustomSolution/CoreCommands.psm1'.
    VERBOSE: Repository details, Name = 'PublishTarget', Location = 'http://SERVERNAME/nuget/modules/'; IsTrusted = 'True'; IsRegistered = 'True'.
    VERBOSE: Using the provider 'PowerShellGet' for searching packages.
    VERBOSE: Using the specified source names : 'PublishTarget'.
    VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
    VERBOSE: The specified Location is 'http://SERVERNAME/nuget/modules/' and PackageManagementProvider is 'NuGet'.
    VERBOSE: Searching repository 'http://SERVERNAME/nuget/modules/FindPackagesById()?id='MyCustomSolution'' for ''.
    VERBOSE: Total package yield:'0' for the specified package 'MyCustomSolution'.
    VERBOSE: Performing the operation "Publish-Module" on target "Version '1.0.0.0' of module 'MyCustomSolution'".
    Publish-PSArtifactUtility : Failed to generate the compressed file for module 'Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core'.
    At /opt/microsoft/powershell/6.1.0~preview.2/Modules/PowerShellGet/1.6.0/PSModule.psm1:1447 char:17
    + ...             Publish-PSArtifactUtility @PublishPSArtifactUtility_Param ...
    +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : FailedToCreateCompressedModule,Publish-PSArtifactUtility

## Expected Behavior
Publish-Module should publish the module with no issues 

## Current Behavior
Getting error as described above

## Steps to Reproduce (for bugs)
I have just an example PowerShell module at the moment, it loads up and runs locally no issues. When I call the publish command shown above it gives the error.

## Context
This is about as bare of a solution as I can come up with right now, nothing complicated in the module itself, just trying to validate that publish-module will work from MacOS and then also from Ubuntu 14.04 once I get this going. 

## Your Environment
MacOS running PowerShell 6rc2, .net core 2.1 installed. Here's the output of PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

> Get-Module -ListAvailable PowerShellGet,PackageManagement

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.7.0    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}
Script     1.6.0      PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}

> Get-PackageProvider

Name                     Version          DynamicOptions
----                     -------          --------------
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFile, SkipValidate
PowerShellGet            1.6.0.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate, AllowPrereleaseVersions, Filter, Tag, Include...

```

**Comment by BrianFarnhill** [comment]
OK so I have no idea what the root cause is here, but I figured out what was breaking it. I was passing in the values to my Register-PSRepository and Publish-Module commands using two environment variables - `$env:APIKey` and `$env:TargetPath`. The second I changed those two variables for different variable names (same values) everything came good! I'm sure there is some reason for this if you dig in under the hood but for the time being I have a work around, which is good enough - so I'm closing this one off and hopefully if anyone happens to stumble across it that its useful!

**Comment by kwirkykat** [comment]
If anyone else runs into this issue, I was eventually able to fix it by starting a fresh PowerShell session and running this command to update the NuGet that was associated with my PowerShellGet module:

```Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile "$env:LOCALAPPDATA\Microsoft\Windows\PowerShell\PowerShellGet\NuGet.exe"```

Before that I had also tried updating my PowerShellGet module via Update-Module and updating NuGet in other ways (nuget update -self).
Not sure if I did that incorrectly or if I just needed to start a new session, but it didn't work until I ran the above line in a new session the next morning.

**Comment by cpolydorou** [comment]
The above command did the job for me. Thank you @kwirkykat!

**Comment by potatoqualitee** [comment]
@kwirkykat 's response put me on the right path as well. I reinstalled a new, updated version of PowerShellGet and was set 👍

**Comment by alekdavis** [comment]
Solved my problem, too. Thank you @kwirkykat!

**Comment by felixfbecker** [comment]
I have the same problem, locally (macOS) and in CI (Windows).
@kwirkykat How would that command look like for macOS?

```
Publish-PSArtifactUtility : Failed to generate the compressed file for module 'dotnet cli failed to pack Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
  Restoring packages for /var/folders/ty/5zr32vl56g916ptcd7jj3z640000gp/T/7cf5456e-7b3a-495e-91bb-3b29fd081429/Temp.csproj...
  Generating MSBuild file /var/folders/ty/5zr32vl56g916ptcd7jj3z640000gp/T/7cf5456e-7b3a-495e-91bb-3b29fd081429/obj/Temp.csproj.nuget.g.props.
  Generating MSBuild file /var/folders/ty/5zr32vl56g916ptcd7jj3z640000gp/T/7cf5456e-7b3a-495e-91bb-3b29fd081429/obj/Temp.csproj.nuget.g.targets.
  Restore completed in 203.62 ms for /var/folders/ty/5zr32vl56g916ptcd7jj3z640000gp/T/7cf5456e-7b3a-495e-91bb-3b29fd081429/Temp.csproj.
  Temp -> /var/folders/ty/5zr32vl56g916ptcd7jj3z640000gp/T/7cf5456e-7b3a-495e-91bb-3b29fd081429/bin/Debug/netcoreapp2.0/NotUsed.dll
/usr/local/share/dotnet/sdk/2.2.101/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(202,5): error : '
                                                                                                                      ', hexadecimal value 0x0C, is an invalid character. Line 9, position 1728. [/var/folders/ty/5zr32vl56g916ptcd7jj3z640000gp/T/7cf5456e-7b3a-495e-91bb-3b29fd081429/Temp.csproj]
'.
At /usr/local/microsoft/powershell/6/Modules/PowerShellGet/PSModule.psm1:10784 char:17
+ ...             Publish-PSArtifactUtility @PublishPSArtifactUtility_Param ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by felixfbecker** [comment]
Ah, for me the cause was an invalid module manifest. I had used string concatenation for `ReleaseNotes`:

```powershell
ReleaseNotes =
  "Line 1" +
  "Line 2"
```

apparently that is not legal, and it worked after I removed it.

**Comment by joeltimothyoh** [comment]
I had the issue described in #295 but I believe is now resolved by downloading the latest `nuget.exe` via the command from @kwirkykat .

**Comment by marckassay** [comment]
I had a similar error message. I tried @kwirkykat's recommendation (prior to the commands below) with no success. Afterwards, solved my issue by the following:
```
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
Install-PackageProvider -Name PowerShellGet -Force -Scope CurrentUser
```

**Comment by weiyentan** [comment]
@kwirkykat response  helped with my issue too
