### ISSUE TITLE
PowerShellGet and NuGet Repository

### ISSUE THREAD

**Issue by karezza** [PowerShell/PowerShellGetv2#306]
When publishing to an Artifactory NuGet Repository the message appears, "Client did not publish a checksum value." Three checksums are expected: SHA-256, SHA-1, MD5. SHA-256 is received successfully. How can "Publish-Module" be encouraged to provide all three checksums?

**Comment by bmanikm** [comment]
@karezza Publish-Module cmdlet uses NuGet.exe/dotnet cli for creating the nupkg file and publishing it to the registered NuGet-based repository. Do you know what version of NuGet.exe is required for publishing modules to your Artifactory NuGet Repository?

**Comment by karezza** [comment]
I'm told we are using Artifactory 5.9 and that it works with NuGet 2.0 .  6.0 will allow a newer version of NuGet, maybe that will fix this issue.  I'll do a wait and see and close for now.  Thank you.

**Comment by karezza** [comment]
I'm not positive what version of NuGet Artifactory requires.  I know we will be upgrading in a few months.  If Artifactory is the problem, then upgrading may be the solution.  At the moment, I have the latest NuGet running on my side.  It seems like this issue/fix would be part of the nuget command line or configuration file to me.  Could you help me to generate a bit of logging so that I can see if multiple hashes are being uploaded?  What is the full command being run when nuget is called?

**Comment by bmanikm** [comment]
I see below in your issue description, so NuGet.exe provided SHA-256 hash to the Artifictory feed.
'Three checksums are expected: SHA-256, SHA-1, MD5. SHA-256 is received successfully. '

You should work with the Artifiactory folks regarding your requirements. Additionally, you can also try publishing a nupkg file to your feed using [NuGet.exe](https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference)
