### ISSUE TITLE
Publish-Module doesn't report error but fails to publish module

### ISSUE THREAD

**Issue by TylerLeonhardt** [PowerShell/PowerShellGetv2#316]
I was attempting to publish a module to the Gallery via:
```
Publish-Module -Name Polaris -NuGetApiKey $apiKey
```

The cmdlet reports nothing back - so I assume it worked. I check the Gallery to see if it did and can't find my published module anywhere, unfortunately.

I thought it was because I was publishing on a mac... but I was able to repro on Windows too with the latest version of PowerShellGet.

## Expected Behavior
The module is published

## Current Behavior
It silently fails... Verbose logging shows:

```
VERBOSE: Acquiring providers for assembly: /Users/tylerleonhardt/.powershell-daily/Modules/PackageManagement/1.1.7.0/coreclr/netcoreapp2.0/Microsoft.PackageManagement.NuGetProvider.dll
VERBOSE: Acquiring providers for assembly: /Users/tylerleonhardt/.powershell-daily/Modules/PackageManagement/1.1.7.0/coreclr/netcoreapp2.0/Microsoft.PackageManagement.CoreProviders.dll
VERBOSE: Acquiring providers for assembly: /Users/tylerleonhardt/.powershell-daily/Modules/PackageManagement/1.1.7.0/coreclr/netcoreapp2.0/Microsoft.PackageManagement.ArchiverProviders.dll
VERBOSE: Acquiring providers for assembly: /Users/tylerleonhardt/.powershell-daily/Modules/PackageManagement/1.1.7.0/coreclr/netcoreapp2.0/Microsoft.PackageManagement.MetaProvider.PowerShell.dll
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Publish Location:'https://www.powershellgallery.com/api/v2/package/'.
VERBOSE: Module 'Polaris' was found in '/Users/tylerleonhardt/Downloads/Polaris'.
VERBOSE: Loading module from path '/var/folders/rg/g30_83v14m10px9z72kydv1m0000gn/T/238330691/Polaris/Public/New-ScriptblockCallback.ps1'.
VERBOSE: Loading module from path '/var/folders/rg/g30_83v14m10px9z72kydv1m0000gn/T/238330691/Polaris/lib/MimeTypes.Class.ps1'.
VERBOSE: Loading module from path '/var/folders/rg/g30_83v14m10px9z72kydv1m0000gn/T/238330691/Polaris/lib/PolarisRequest.Class.ps1'.
VERBOSE: Loading module from path '/var/folders/rg/g30_83v14m10px9z72kydv1m0000gn/T/238330691/Polaris/lib/PolarisResponse.Class.ps1'.
VERBOSE: Loading module from path '/var/folders/rg/g30_83v14m10px9z72kydv1m0000gn/T/238330691/Polaris/lib/PolarisMiddleware.Class.ps1'.
VERBOSE: Loading module from path '/var/folders/rg/g30_83v14m10px9z72kydv1m0000gn/T/238330691/Polaris/lib/Polaris.Class.ps1'.
VERBOSE: Loading module from path '/var/folders/rg/g30_83v14m10px9z72kydv1m0000gn/T/238330691/Polaris/Polaris.psm1'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/items/psscript/' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/items/psscript/FindPackagesById()?id='Polaris'' for ''.
VERBOSE: Total package yield:'0' for the specified package 'Polaris'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2/'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2/' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='Polaris'' for ''.
VERBOSE: Total package yield:'0' for the specified package 'Polaris'.
VERBOSE: Performing the operation "Publish-Module" on target "Version '0.1.0' of module 'Polaris'".
VERBOSE: Successfully published module 'Polaris' to the module publish location 'https://www.powershellgallery.com/api/v2/package/'. Please allow few minutes for 'Polaris' to show up in the search results.
```

The last line particularly strange:
```
VERBOSE: Successfully published module 'Polaris' to the module publish location 'https://www.powershellgallery.com/api/v2/package/'. Please allow few minutes for 'Polaris' to show up in the search results.
```
I would have expected the url to be `https://www.powershellgallery.com/api/v2/package/` but maybe not.

## Possible Solution

Not sure.

## Steps to Reproduce (for bugs)

1. Update to latest PowerShellGet
2. `Publish-Module -Name Polaris -NuGetApiKey $apiKey`

## Context

Can't publish my module at all :(

## Your Environment

```PowerShell

> $PSVersionTable
# on Mac I'm using a daily build

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-preview.10712
PSEdition                      Core
GitCommitId                    6.1.0-preview.10712
OS                             Darwin 18.0.0 Darwin Kernel Version 18.0.0: Sun Aug 12 14:04:39 PDT 2018; root:xnu-4903.201.1~14/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

# on Windows I tried both 6.1.0-Preview.2 and Windows PowerShell.

> Get-Module -ListAvailable PowerShellGet,PackageManagement

Get-Module -ListAvailable PowerShellGet,PackageManagement


    Directory: /usr/local/share/powershell/Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     1.6.7      PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Find-RoleCapability...}
Script     1.6.0      PowerShellGet                       Desk      {Install-Module, Find-Module, Save-Module, Update-Module...}


    Directory: /Users/tylerleonhardt/.powershell-daily/Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     1.1.7.0    PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}
Script     1.6.0      PowerShellGet                       Desk      {Install-Module, Find-Module, Save-Module, Update-Module...}

> Get-PackageProvider

Name                     Version          DynamicOptions
----                     -------          --------------
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFil...
PowerShellGet            1.6.7.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate, AllowPrereleaseVe...

> Get-PackageProvider -ListAvailable

Name                     Version          DynamicOptions
----                     -------          --------------
Gist                     1.6.0.0
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, ConfigFil...
PowerShellGet            1.6.7.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate, AllowPrereleaseVe...
PowerShellGet            1.6.0.0
TSD                      0.2.0.0          Destination
```

**Comment by bmanikm** [comment]
@tylerl0706 I found below error in the error logs.
```
There were errors extracting PowerShell metadata: Unexpected element encountered: ""$PSScriptRoot\Polaris.psm1"". Line numbers: 12-12.
```
https://github.com/PowerShell/Polaris/blob/master/Polaris.psd1#L12

Please let us know the version of dotnet CLI on your machine. It looks like the PowerShell Gallery has reported this error, somehow it is not reported by the dotnet CLI.

**Comment by TylerLeonhardt** [comment]
Sorry for the delay, Mani!

Is `$PSScriptRoot` not allowed in a module manifest?

Also, I have version 2.1.302 of the CLI tools.

**Comment by edyoung** [comment]
95% sure relative paths in module manifest are interpreted as relative to the module's base dir. So just "polaris.psm1" should work

**Comment by TylerLeonhardt** [comment]
Yeah, I can remove that and try again. The module imports just find though... but I think ` Test-ModuleManifest` is more strict than the actual module loader (which is a blessing and a curse 😄 )

**Comment by jzabroski** [comment]
I just ran into this same problem. Silently says it is published, but does not actually publish.

**Comment by bmanikm** [comment]
@jzabroski your scenario might be different as you were trying to publish a module to the ProGet feed (#317). You might need a specific version of the NuGet.exe or your ProGet server didn't return any error. Please try to push/publish a nupkg file to your ProGet feed using NuGet.exe and verify that your scenario is working fine.

**Comment by jzabroski** [comment]
@bmanikm I use my ProGet server regularly for publishing my C# .NET Core projects without any issues.  I tried setting up a PowerShell-only feed in ProGet, re-using my existing working feed, using `-NuGetApiKey anonymous:`, and a bunch of other combinations, but PowerShellGet always screws up.

What I can tell you, spying on PowerShellGet's behavior in Fiddler, is the PUT to the package endpoint is returning a 403 error and your PowerShellGet library is interpreting that as a success. The error is "Invalid API key". (I know, that seems easy enough for me to troubleshoot, but WOW!!, it's scary that PowerShellGet thinks 403 errors are successful publishing of packages.

Here is how I publish in .NET Core:
```xml
  <Target Name="Publish">
    <RemoveDir Directories="$(PublishDirectory)" />

    <MSBuild Projects="$(MSBuildProjectFile)"
             Targets="PublishCore"
             Properties="ProjectDirectory=%(Publish.ProjectDirectory);OutputDirectory=%(Publish.OutputDirectory)" />
  </Target>

  <Target Name="PublishCore">
    <Error Text="ProjectDirectory property is required!" Condition="$(ProjectDirectory) == ''" />
    <Error Text="OutputDirectory property is required!" Condition="$(OutputDirectory) == ''" />

    <Message Importance="High" Text="Publishing project $(ProjectDirectory) to $(OutputDirectory)"/>

    <Exec Command="dotnet publish $(ProjectDirectory) -c Release -o $(OutputDirectory)" />
  </Target>

  <Target Name="Package" DependsOnTargets="Publish">
    <Error Text="Version property is required!" Condition="$(Version) == ''" />

    <RemoveDir Directories="$(PackageDirectory)" />

    <MSBuild Projects="$(MSBuildProjectFile)"
             Targets="PackageCore"
             Properties="Id=%(Publish.Identity);Version=$(Version);InputDirectory=%(Publish.OutputDirectory);OutputDirectory=$(PackageDirectory);" />
  </Target>

  <Target Name="PackageCore" DependsOnTargets="InstallTools">
    <Error Text="Id property is required!" Condition="$(Id) == ''" />
    <Error Text="Version property is required!" Condition="$(Version) == ''" />
    <Error Text="InputDirectory property is required!" Condition="$(InputDirectory) == ''" />
    <Error Text="OutputDirectory property is required!" Condition="$(OutputDirectory) == ''" />

    <Message Importance="High" Text="Publishing project $(ProjectDirectory) to $(OutputDirectory)"/>

    <Exec Command="$(OctoExecutable) pack -id $(Id) --version $(Version) --basePath $(InputDirectory) -outFolder $(OutputDirectory)" />
  </Target>
```

**Comment by bmanikm** [comment]
@jzabroski Please note that PowerShellGet leverages the NuGet.exe or dotnet cli to push the nupkg file to the specified feed. 
You can check the error handling logic at https://github.com/PowerShell/PowerShellGet/blob/development/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1#L552
. It is likely that no error got reported by the NuGet.exe or dotnet cli.

Do you know what version of NuGet.exe is required to push the nupkg package to your ProGet feed?

**Comment by jzabroski** [comment]
Can you please add a -flag so I can dump the nupkg directly from Publish-Module?  The real problem with this library is it's 1,000's of lines to accomplish anything at all, and then it delegates all the actual work to dotnet or NuGet.exe

I ended up getting it to work - I'm not sure why, but with ProGet, the ApiKey did not have "Grant access to Feed API" checked.  The bottom line is you are using NuGet.exe and then scraping the output from the program to determine if it was successful, and it's totally insane!

Tangent: For those interested in getting further faster, here are some debugging tips:

1. Until PowerShellGet fixes it's error handling, assume log messages don't really mean much other than it got to some point down in the huge call stack.
2. Search for the last -Verbose message outputted via GitHub repository search. In my case, I searched for:
  a. First for "[Successfully published module](https://github.com/PowerShell/PowerShellGet/search?q=Successfully+published+module&unscoped_q=Successfully+published+module)"
  b. Then for "[publishedsuccessfully](https://github.com/PowerShell/PowerShellGet/search?q=publishedsuccessfully&unscoped_q=publishedsuccessfully)" to find the actual reference in the code
  c. In my case, it was https://github.com/PowerShell/PowerShellGet/blob/37f2a3f477213be79104695235c8b3ab5eae6e38/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1#L581
  d. I then looked at what immediately preceeded this, and found this AWFUL code:

https://github.com/PowerShell/PowerShellGet/blob/37f2a3f477213be79104695235c8b3ab5eae6e38/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1#L550-L554

The best part of this code is it logs standard output to $tempOutputFile, never looks at it, and then removes the file, so that if you actually wanted to see what happened, you can't.

**Comment by jzabroski** [comment]
@bnakim the immediate fix Microsoft needs to make is check the exitcode. I also recommend at least write-debug the $tempOutFile and $tempErrorFile , if not write-verbose. The fact this code just deletes temp data with no tracing or flag to control the behavior is just amateurish coding.

Please fix and include in 1.6.8

**Comment by TylerLeonhardt** [comment]
Hi @bmanikm I gave a new publish a try after removing all of the `$PSScriptRoot`s and I still get the same issue of a silent failure 😞 

Here's the module manifest: https://github.com/PowerShell/Polaris/blob/master/Polaris.psd1

perhaps I'm missing a required field or something?

**Comment by jzabroski** [comment]
Your FunctionsToExport looks incorrect. @(...) is a list constructor. Try
adding commas after each entry, except the last

What does Test-ModuleManifest give you?

**Comment by jzabroski** [comment]
@bmanikm after Tyler posted his example psd1 file, it's clear there are two problems. You fixed a really bad problem here, nice job. But the other problem is $PSModuleInfo silently didn't bind FunctionsToExport. My suggestion is to break up these enormous functions into smaller pieces you can test.

@tylerl0706

**Comment by jzabroski** [comment]
@tylerl0706 Any chance you confirm if this fixed your problem?  I feel as though your problem was related to an incorrect psd1 file.  I'm curious how Test-ModuleManifest even worked for your example...

**Comment by TylerLeonhardt** [comment]
@jzabroski Sorry for the delay!

The comma wasn't needed. `Test-ModuleManifest` worked fine. The problem was related to the version of the .NET Core SDK I had installed on my mac. I published the same package on Windows using the `nuget.exe`-based push and it worked fine.

**Comment by bqstony** [comment]
For me a simple '-Force' did the Job. I had the same behavior as descriped, without the $PSScriptRoot stuff
