### ISSUE TITLE
Updating to 2.0.0 results in error about PackageManagement update clobbering its own commands

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShellGetv2#329]
## Expected Behavior
That `install-module powershellget -force` from an admin prompt works without any errors.

## Current Behavior
PowerShellGet isn't updated and I get this error:
```
09-15 10:35:46 3> Install-Module PowerShellGet -Force
PackageManagement\Install-Package : The following commands are already available on this system:'Find-Package,Install-Package,Uninstall-Package'. This module 'PackageManagement' may override the existing commands. If you still want to install this module 'PackageManagement', use -AllowClobber parameter.
At C:\program files\powershell\6\Modules\PowerShellGet\PSModule.psm1:9491 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

## Possible Solution
It seems like there should be special case handling of PackageManagement installing (updating) to avoid the clobber error (and having to use -AllowClobber).

## Steps to Reproduce (for bugs)
1. Install PS Core 6.1 on a clean Windows 10 machine.
2. Start PS Core elevated
3. Try to `update-module PowerShellGet`
```

update-module : Module 'PowerShellGet' was not installed by using Install-Module, so it cannot be updated.
At line:1 char:1
+ update-module PowerShellGet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (PowerShellGet:String) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : ModuleNotInstalledUsingInstallModuleCmdlet,Update-Module
```
4. Try `install-module PowerShellGet`:
```
WARNING: Version '1.6.7' of module 'PowerShellGet' is already installed at 'C:\program files\powershell\6\Modules\PowerShellGet'. To install version '2.0.0', run Install-Module and add the -Force parameter, this command will install version '2.0.0' side-by-side with version '1.6.7'.
```
5. Ok, try `install-module PowerShellGet -force`:
```
PackageManagement\Install-Package : The following commands are already available on this system:'Find-Package,Install-Package,Uninstall-Package'. This module 'PackageManagement' may override the existing commands. If you still want to install this module 'PackageManagement', use -AllowClobber parameter.
At C:\program files\powershell\6\Modules\PowerShellGet\PSModule.psm1:9491 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```
6. Sigh, try `install-module PowerShellGet -force -allowClobber`:
```
WARNING: The version '1.1.7.2' of module 'PackageManagement' is currently in use. Retry the operation after closing the applications.
```

OK this is getting frustrating

7. Close and re-open PS Core as admin and run `install-module PowerShellGet -force -allowClobber` again:
```
WARNING: The version '1.1.7.2' of module 'PackageManagement' is currently in use. Retry the operation after closing the applications.
```
But at least this time 2.0.0 appears to have installed:
```
> gmo

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.1.4      ClipboardText                       {Get-ClipboardText, Set-ClipboardText, gcbt, scbt}
Script     1.0.0      DirColors                           {ConvertFrom-LSColors, ConvertTo-LSColors, Format-Colorize...
Manifest   6.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemPropert...
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.1.7.2    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     1.0.0.0    posh-git                            {Add-PoshGitToProfile, Expand-GitCommand, Format-GitBranch...
Script     2.0.0      PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCap...
Script     2.0.0      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...
Script     1.0.0      ZLocation                           {Get-ZLocation, Invoke-ZLocation, Pop-ZLocation, Remove-ZL...
```

## Context
I'm just trying to update to PowerShellGet 2.0.0 on PS Core 6.1 GA.

## Your Environment

```PowerShell

> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

> Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.1.4      ClipboardText                       {Get-ClipboardText, Set-ClipboardText, gcbt, scbt}
Script     1.0.0      DirColors                           {ConvertFrom-LSColors, ConvertTo-LSColors, Format-Colorize...
Manifest   6.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemPropert...
Manifest   6.1.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl...
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Manifest   6.1.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, En...
Script     1.1.7.2    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     1.0.0.0    posh-git                            {Add-PoshGitToProfile, Expand-GitCommand, Format-GitBranch...
Script     2.0.0      PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCap...
Script     2.0.0      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...
Script     1.0.0      ZLocation                           {Get-ZLocation, Invoke-ZLocation, Pop-ZLocation, Remove-ZL...

> Get-Module -ListAvailable PowerShellGet,PackageManagement

    Directory: C:\Users\Keith\Documents\PowerShell\Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     2.0.0      PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Fi...


    Directory: C:\Program Files\PowerShell\Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     2.0.0      PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Fi...


    Directory: C:\program files\powershell\6\Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     1.1.7.2    PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider,...
Script     1.6.7      PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Fi...

> Get-PackageProvider

Name                     Version          DynamicOptions
----                     -------          --------------
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag...
PowerShellGet            2.0.0.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, …

> Get-PackageProvider -ListAvailable

Name                     Version          DynamicOptions
----                     -------          --------------
NuGet                    2.8.5.210        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag...
PowerShellGet            2.0.0.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, ...
PowerShellGet            1.6.7.0
```

**Comment by bmanikm** [comment]
[2.0.1](https://www.powershellgallery.com/packages/PowerShellGet/2.0.1) version of PowerShellGet module includes the fix for this issue.

**Comment by X-Guardian** [comment]
I'm still getting this issue on a clean install of Server 2016:

```
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```
PS C:\WINDOWS\system32> Get-Module -ListAvailable


    Directory: C:\program files\powershell\6\Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Manifest   6.1.0.0    CimCmdlets                          Core      {Get-CimAssociatedInstance, Get-CimClass, Get-Ci...
Manifest   1.1.0.0    Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   6.1.0.0    Microsoft.PowerShell.Diagnostics    Core      {Get-WinEvent, New-WinEvent}
Manifest   6.1.0.0    Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   6.1.0.0    Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Clear-ItemProperty,...
Manifest   6.1.0.0    Microsoft.PowerShell.Security       Core      {Get-Acl, Set-Acl, Get-PfxCertificate, Get-Crede...
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        Core      {Format-List, Format-Custom, Format-Table, Forma...
Manifest   6.1.0.0    Microsoft.WSMan.Management          Core      {Disable-WSManCredSSP, Enable-WSManCredSSP, Get-...
Script     1.1.7.2    PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider,...
Script     1.6.7      PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Fi...
Script     0.0        PSDesiredStateConfiguration         Desk      {Generate-VersionInfo, Set-PSMetaConfigDocInsPro...
Script     6.1.0.0    PSDiagnostics                       Core      {Disable-PSTrace, Disable-PSWSManCombinedTrace, ...
Script     2.0.0      PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHand...
Binary     1.1.2      ThreadJob                           Desk      Start-ThreadJob
```
```
PS C:\WINDOWS\system32> install-module PowerShellGet -force
PackageManagement\Install-Package : The following commands are already available on this system:'Find-Package,Install-Package,Uninstall-Package'. This module 'PackageManagement' may override the existing commands. If you still want to install this module 'PackageManagement', use -AllowClobber parameter.
At C:\program files\powershell\6\Modules\PowerShellGet\PSModule.psm1:9491 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```
```
PS C:\WINDOWS\system32> install-module PowerShellGet -Force -AllowClobber
WARNING: The version '1.1.7.2' of module 'PackageManagement' is currently in use. Retry the operation after closing the applications.
```
Close and re-open PS Core
```
PS C:\WINDOWS\system32> install-module PowerShellGet -Force -AllowClobber
WARNING: The version '1.1.7.2' of module 'PackageManagement' is currently in use. Retry the operation after closing the applications.
PS C:\WINDOWS\system32> get-module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   6.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemPropert...
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.1.7.2    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     2.0.1      PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCap...
Script     2.0.0      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...
```

**Comment by bmanikm** [comment]
@X-Guardian As mentioned above, this issue got resolved in 2.0.1 version of PowerShellGet. This is a known issue when you try to install the latest version of PowerShellGet from its previous versions (<2.0.1). It looks like you are trying to install the latest version using 1.6.7 version. This issue should not happen when you install the future versions from >=2.0.1.

**Comment by pjamesburwell** [comment]
Get-Module -ListAvailable Power*| Select name | Out-String | % {$_ -replace "Name"}|% {$_ -replace "-"}|% {$_ -replace " "} |out-file -filepath .\ModulesbyName_Power.txt
Wait-Event -Timeout 5
Get-Module -ListAvailable Microsoft*| Select name | Out-String | % {$_ -replace "Name"}|% {$_ -replace "-"}|% {$_ -replace " "} |out-file -filepath .\ModulesbyName_Microsoft.txt
Wait-Event -Timeout 5
Get-Content -Path C:\scripts\ModulesbyName_Microsoft.txt | Import-Module -verbose
Wait-Event -Timeout 5
Get-Content -Path C:\scripts\ModulesbyName_Power.txt | Import-Module -verbose
Get-Module -ListAvailable PowerShellGet,PackageManagement
Update-Help -Module PowerShellGet -Verbose

**Comment by pjamesburwell** [comment]
Anyone have the UPDATED PowerShellGet.psd1?

**Comment by SydneyhSmith** [comment]
The most updated psd1 can be found here: https://github.com/PowerShell/PowerShellGet/blob/development/src/PowerShellGet/PowerShellGet.psd1 And the most recently published psd1 can be found here: https://www.powershellgallery.com/packages/PowerShellGet/2.0.3/Content/PowerShellGet.psd1

**Comment by pjamesburwell** [comment]
Why didn't that update all this time? I ran the update and it's still 1.0.

**Comment by SydneyhSmith** [comment]
@pjamesburwell I want to make sure I understand the issue. Can you please share the output (maybe a screenshot) when you run: `Update-Module PackageManagement, PowerShellGet` ,
 `Get-InstalledModule PackageManagement, PowerShellGet` , and `$PSVersionTable`

**Comment by crypticsorr0w** [comment]
`PS C:\WINDOWS\system32> Install-Module -Name PowerShellGet -RequiredVersion 2.0.3 -Force
WARNING: The version '1.2.4' of module 'PackageManagement' is currently in use. Retry the operation after closing the
applications.`

**Comment by pjamesburwell** [comment]
PS C:\scripts> Update-Module PackageManagement

PS C:\scripts> Update-Module PackageManagement -verbose
VERBOSE: Checking for updates for module 'PackageManagement'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'False'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PackageManagement'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'PackageManagement'.
VERBOSE: Skipping installed module PackageManagement 1.2.4.

PS C:\scripts> Update-Module PowerShellGet -verbose
VERBOSE: Checking for updates for module 'PowerShellGet'.
VERBOSE: Repository details, Name = 'PSGallery', Location = 'https://www.powershellgallery.com/api/v2'; IsTrusted = 'False'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'PSGallery'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'PowerShellGet'.
VERBOSE: Performing the operation "Update-Module" on target "Version '2.0.3' of module 'PowerShellGet', updating to version '2.0.4'".
VERBOSE: The installation scope is specified to be 'AllUsers'.
VERBOSE: The specified module will be installed in 'C:\Program Files\WindowsPowerShell\Modules'.
VERBOSE: An update for the module 'PowerShellGet' was found with version '2.0.4'.
VERBOSE: The specified Location is 'NuGet' and PackageManagementProvider is 'NuGet'.
VERBOSE: Downloading module 'PowerShellGet' with version '2.0.4' from the repository 'https://www.powershellgallery.com/api/v2'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'' for ''.
VERBOSE: Package 'PackageManagement' is already installed.
VERBOSE: Package 'PackageManagement' is already installed.
VERBOSE: InstallPackage' - name='PowerShellGet', version='2.0.4',destination='C:\Users\pburwell\AppData\Local\Temp\1208887312'
VERBOSE: DownloadPackage' - name='PowerShellGet', version='2.0.4',destination='C:\Users\pburwell\AppData\Local\Temp\1208887312\PowerShellGet.2.0.4\PowerShellGet.2.0.4.nupkg', uri='https://www.powershellgallery.com/api/v2/pack
age/PowerShellGet/2.0.4'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/PowerShellGet/2.0.4'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/PowerShellGet/2.0.4'.
VERBOSE: Completed downloading 'PowerShellGet'.
VERBOSE: Hash for package 'PowerShellGet' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='PowerShellGet', version='2.0.4',destination='C:\Users\pburwell\AppData\Local\Temp\1208887312'
VERBOSE: Validating the 'PowerShellGet' module contents under 'C:\Users\pburwell\AppData\Local\Temp\1208887312\PowerShellGet.2.0.4' path.
VERBOSE: Test-ModuleManifest successfully validated the module manifest file 'C:\Users\pburwell\AppData\Local\Temp\1208887312\PowerShellGet.2.0.4'.
VERBOSE: Validating the authenticode signature and publisher of the catalog file or module manifest file of the module 'PowerShellGet'.
VERBOSE: Found the catalog file 'PowerShellGet.cat' in the module 'PowerShellGet' contents.
VERBOSE: Valid authenticode signature found in the catalog file 'PowerShellGet.cat' for the module 'PowerShellGet'.
VERBOSE: Validating the 'PowerShellGet' module files for catalog signing using the catalog file 'PowerShellGet.cat'.
VERBOSE: The catalog signature in 'PowerShellGet.cat' of the module 'PowerShellGet' is valid and matches with the hash generated from the module contents.
VERBOSE: For publisher validation, current module 'PowerShellGet' with version '2.0.4' with publisher name 'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' from root certificate authority 'CN
=Microsoft Root Certificate Authority 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US'. Is this module signed by Microsoft: 'True'.
VERBOSE: For publisher validation, using the previously-installed module 'PowerShellGet' with version '2.0.3' under 'C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.0.3' with publisher name 'CN=Microsoft Corporatio
n, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' from root certificate authority 'CN=Microsoft Root Certificate Authority 2011, O=Microsoft Corporation, L=Redmond, S=Washington, C=US'. Is this module signed by Micro
soft: 'True'.
VERBOSE: Authenticode issuer 'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' of the new module 'PowerShellGet' with version '2.0.4' matches with the authenticode issuer 'CN=Microsoft Corpora
tion, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' of the previously-installed module 'PowerShellGet' with version '2.0.3'.
VERBOSE: Checking for possible command collisions for the module 'PowerShellGet' commands.
VERBOSE: Module 'PowerShellGet' was installed successfully to path 'C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.0.4'.

PS C:\scripts> Get-InstalledModule PackageManagement -verbose

Version              Name                                Repository           Description                                                                                                                                       
-------              ----                                ----------           -----------                                                                                                                                       
1.2.4                PackageManagement                   PSGallery            PackageManagement (a.k.a. OneGet) is a new way to discover and install software packages from around the web....                                  



PS C:\scripts> Get-InstalledModule PowerShellGet -verbose

Version              Name                                Repository           Description                                                                                                                                       
-------              ----                                ----------           -----------                                                                                                                                       
2.0.4                PowerShellGet                       PSGallery            PowerShell module with commands for discovering, installing, updating and publishing the PowerShell artifacts like Modules, DSC Resources, Role...



PS C:\scripts>

**Comment by pjamesburwell** [comment]
I think I fixed the problem...
    /--------------------/
    Register-PSRepository -Default -Verbose
    set-location C:\scripts
    .\Set-ISEColors.ps1
    $host.PrivateData.ErrorForegroundColor = 'White'
    $PSEmailServer = 'smtp.office365.com'
    .\Set-ISEColors.ps1
    Get-Module -ListAvailable PowerShellGet,PackageManagement
    Update-Help -Module PowerShellGet -Verbose
    gmo
    \/--------------------\

**Comment by TomLongAshfords** [comment]
> I think I fixed the problem...
> /--------------------/
> Register-PSRepository -Default -Verbose
> set-location C:\scripts
> .\Set-ISEColors.ps1
> $host.PrivateData.ErrorForegroundColor = 'White'
> $PSEmailServer = 'smtp.office365.com'
> .\Set-ISEColors.ps1
> Get-Module -ListAvailable PowerShellGet,PackageManagement
> Update-Help -Module PowerShellGet -Verbose
> gmo
> /--------------------\

I'm too thick to understand why, but updating help for PowerShellGet seemed to fix it for me too.
