### ISSUE TITLE
Version property on output of Find-Module is a string

### ISSUE THREAD

**Issue by RamblingCookieMonster** [PowerShell/PowerShellGetv2#330]
Whether this is intentional or the byproduct of an intentional change, the cersion property on output of Find-Module is now a string, and not a version.  This is painful : )

## Expected Behavior

Version property from Find-Module is a `System.Version`

## Current Behavior

Version property from Find-Module is a `System.String`

## Possible Solution

No idea.  Might be intentional.

## Steps to Reproduce (for bugs)

Use the latest PowerShellGet, look at output from Find-Module

## Context

BuildHelpers is a module for helping builds.  [Some folks](https://github.com/search?q=Get-NextPSGalleryVersion&type=Code) use `Get-NextPSGalleryVersion` to determine the next version for their module, if they want to auto-increment.  Previously, this used a little logic to bump whatever the lowest increment would be (1.0.0 to 1.0.1, 1.0 to 1.1, etc.).  Now?  It returns `1.0`.  Always.    So [PSDeploy](https://www.powershellgallery.com/packages/PSDeploy/) went from 0.2.6 to 1.0, for example.

I suspect some folks might be using appveyor images that don't include the new powershellget module (i.e. they might be saved from this), but... once they fix that, if I don't patch BuildHelpers, they're going to be publishing a lot of version `1.0` modules : )

I'll be patching BuildHelpers, and many folks don't pin versions so might avoid some pain.

Yeah, folks should probably manually bump things, but we tend to avoid manual work : )

## Your Environment

AppVeyor `image: Visual Studio 2017` at least.  Likely other systems using the latest PowerShellGet

**Comment by bmanikm** [comment]
@RamblingCookieMonster Yes, version property type got changed to string to enable prerelease versioning. For more details, please take a look at https://github.com/PowerShell/PowerShellGet/pull/185 .

**Comment by RamblingCookieMonster** [comment]
Makes sense - thanks!
