### ISSUE TITLE
Split PSModule.psm1 to move all functions to seperate files 

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/PowerShellGetv2#37]
This should help to make development much easier going forward - I have what I think is almost fully working that includes
- [x] Separates all functions to separate files
- [x] Renames PSModule.psm1 to PowerShellGet.psm1
- [x] Renames PSGetFormat.ps1xml to PowerShellGet.Format.ps1xml
- [x] Renames PSGet.Resource.psd1 to PowerShellGet.Resource.psd1
- [x] Updates PowerShellGet.psd1 version
- [x] Updates PowerShellGet.psd1 references for files renamed to new names
- [x] Separates the script variables to an initialize.ps1 script

@bmanikm - let me know if you'd like this idea and I'll raise a PR for this

**Comment by bmanikm** [comment]
@kilasuit I agree, these changes will make the development much easier.

When I started this project, I tried to create separate file for each function and ran into some issues.

Here are some details.
- There are some limitations in splitting into multiple files like using the nestedmodule (siblings) functions in other nested modules (siblings).
- It is not possible to separate all functions into separate files, for example: all PackageManagement provider functions should be in one single file.
- Some files can have the state, if we import those files into different sibling files, I found different state in different siblings.
- Re-importing the different versions of PowerShellGet module with -Force in the same session/runspace, should work fine. 
- For dropping the stable version of PowerShellGet module from Git Repo, with these changes, into Windows (in-box) release requires good amount of setup related work. I will work with the inbox release management to see if we can make this change for the next immediate release. I will inform accordingly.
- For the inbox release, there is a localization impact with renaming the PSGet.Resource.psd1 file.
- We also need to ensure that PowerShellGet cmdlet help works fine after renaming the PSModule.psm1 file.
- We need to ensure that PowerShellGet module, with these changes, works fine on all supported PS Versions.
- We haven't yet integrated with AppVeyor for downlevel PS Versions (Currently AppVeyor doesn't support this, do you have any inputs on this?) and also Travis CI for Linux and Mac. Can we do this work after enabling the automatic test validation for all supported platforms?

**Comment by bmanikm** [comment]
@JKeithB, @KrishnaV-MSFT Please take a look at this proposal. This has a servicing impact for the inbox release if we rename and create new files.

**Comment by kilasuit** [comment]
referencing PR #229 & @Benny1007 - I did start this (albeit in early 2017) using a framework that I had built for this - would be worthwhile syncing up on this as I had number of potentially breaking changes that had been identified along the way - Glad to see this has been picked up!

**Comment by Benny1007** [comment]
Yep for sure, there are certainly some intricacies with this module ;)



On 22 Feb 2018, at 9:26 pm, Ryan Yates <notifications@github.com<mailto:notifications@github.com>> wrote:


referencing PR #229<https://github.com/PowerShell/PowerShellGet/pull/229> & @Benny1007<https://github.com/benny1007> - I did start this (albeit in early 2017) using a framework that I had built for this - would be worthwhile syncing up on this as I had number of potentially breaking changes that had been identified along the way
