### ISSUE TITLE
Update-ModuleManifest does not preserve original file encoding

### ISSUE THREAD

**Issue by lpatalas** [PowerShell/PowerShellGetv2#372]
Hello all.

`Update-ModuleManifest` always saves file with default encoding. This is problematic because if you have any non-ASCII characters in manifest then PSScriptAnalyzer will require you to have BOM otherwise it reports warning `UseBOMForUnicodeEncodedFile`.

The current workaround I use is:

```powershell
$manifestContent = Update-ModuleManifest -Path $manifestPath -PassThru
$manifestContent | Set-Content $manifestPath -Encoding UTF8BOM
```

I think the easiest solution would be to add optional `-Encoding` parameter to this cmdlet. In fact I would be willing to provide pull request for this if you think that's the way to go.

**Comment by alerickson** [comment]
I think adding an `-Encoding` parameter is a solid and straightforward solution.  Please feel free to send in a PR!

**Comment by SydneyhSmith** [comment]
@lpatalas Thanks for submitting this issue, are you still thinking of submitting a PR?

**Comment by lpatalas** [comment]
Yes, I'm still interested although I haven't started working on it yet. I plan to implement it as soon as I have some free time which should be sometime during coming week I hope. :)

**Comment by lpatalas** [comment]
Hello again.

While working on this issue I found following information:

* `UseBOMForUnicodeEncodedFile` rule is not included any more in any default PSScriptAnalyzer presets, for example `Invoke-ScriptAnalyzer -Path $manifestPath -Settings PSGallery` does not return this error. It is only reported when no `-Settings` parameter is provided. It's described in this issue: https://github.com/PowerShell/PSScriptAnalyzer/issues/810.
* [RFC0020-DefaultFileEncoding](https://github.com/PowerShell/PowerShell-RFC/blob/master/5-Final/RFC0020-DefaultFileEncoding.md) document says that by default files should not contain BOM for cross-platform compatibility. It can be controlled by `$PSDefaultEncoding` variable which automatically changes behavior of `Set-Content` cmdlet.

Taking the above into account I don't think that adding new parameter to `Update-ModuleManifest` is really necessary. So I guess this issue can be closed. :)

**Comment by edyoung** [comment]
Makes sense, thanks
