### ISSUE TITLE
[PowerShellGet 2.0.3] Three platforms, three different default behaviors

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShellGetv2#376]
When you run Install-Module without specifying a scope:

Windows PowerShell, non-admin session:
CurrentUser scope is used.

Windows PowerShell, admin session:
AllUsers scope is used.

PowerShell Core on Windows, non-admin session:
CurrentUser scope is used.

PowerShell Core on Windows, admin session:
CurrentUser scope is used.

PowerShell Core on Linux, non-sudo:
Error message:
```
PS /home/aleksandar> install-module psnotifysend -Repository psgallery -Verbose 
install-module : Administrator rights are required to install modules in '/usr/local/share/powershell/Modules'. Log on to the computer with an account that has Administrator rights, and then try again, or install '/home/aleksandar/.local/share/powershell/Modules' by adding "-Scope CurrentUser" to your command. You can also try running the Windows PowerShell session with elevated rights (Run as Administrator).
```

**Comment by edyoung** [comment]
The Linux behavior is not expected. We don't currently plan to change the Windows PowerShell behavior.

**Comment by bergmeister** [comment]
What about the PowerShell Core on Windows behaviour @edyoung

**Comment by alerickson** [comment]
@bergmeister  We had a [breaking change](https://github.com/PowerShell/PowerShellGet/blob/development/CHANGELOG.md) with the release of 2.0.0:
```

- Default installation scope for Install-Module, Install-Script, and Install-Package has changed. For Windows PowerShell (version 5.1 or below), the default scope is AllUsers when running in an elevated session, and CurrentUser at all other times.
  For PowerShell version 6.0.0 and above, the default installation scope is always CurrentUser.
```

**Comment by alexandair** [comment]
@alerickson My point is--why that breaking change is not consistent?

**Comment by alexandair** [comment]
@edyoung I cannot repro anymore on PowerShell Core on Linux (WSL).
Now I get this every time I try to install a module:
```
PS /home/aleksandar> install-module psnotifysend -Verbose -Repository psgallery
VERBOSE: Acquiring providers for assembly: /usr/local/share/powershell/Modules/PackageManagement/1.2.3/coreclr/netcoreapp2.0/Microsoft.PackageManagement.ArchiverProviders.dll
VERBOSE: Acquiring providers for assembly: /usr/local/share/powershell/Modules/PackageManagement/1.2.3/coreclr/netcoreapp2.0/Microsoft.PackageManagement.CoreProviders.dll
VERBOSE: Acquiring providers for assembly: /usr/local/share/powershell/Modules/PackageManagement/1.2.3/coreclr/netcoreapp2.0/Microsoft.PackageManagement.MetaProvider.PowerShell.dll
VERBOSE: Acquiring providers for assembly: /usr/local/share/powershell/Modules/PackageManagement/1.2.3/coreclr/netcoreapp2.0/Microsoft.PackageManagement.NuGetProvider.dll
```

And, module is not even installed at all.

**Comment by alerickson** [comment]
We wanted PowerShell Core to be consistent across platforms and be in alignment with Linux behavior, but we wanted to mitigate breaking changes by keeping the old expected behavior on Windows PowerShell.

**Comment by iricigor** [comment]
As being cross-platfrom this part of the message should be updated also: `You can also try running the Windows PowerShell session with elevated rights (Run as Administrator)`

**Comment by edyoung** [comment]
I'd like to use this issue to track the issue regarding running install-module on linux. To debate the desired behavior, please use #236

**Comment by alerickson** [comment]
@iricigor That's fair.  That message was included as an alternate option for those using Core on Windows, but it is a misleading message if you're not on Windows.

**Comment by edyoung** [comment]
Installed psnotifysend successfully on Ubuntu 18.04 using pwsh 6.1.1 and PowerShellGet 2.0.3, it used currentuser scope by default. Haven't had a chance to try WSL yet - have you seen this outside WSL @alexandair ?

**Comment by alexandair** [comment]
@edyoung 
It worked as expected (used CurrentUser scope by default) on Ubuntu 18.04 VM with pwsh 6.1.1 and PowerShellGet 2.0.3.

**Comment by edyoung** [comment]
I could also install successfully on ubuntu 18.04 inside WSL (also pwsh 6.1.1 and PowerShellGet 2.0.3). I suspect something odd has happened on the environment where you have reproduced this. Try running with -debug and see if that produces any more info?

**Comment by edyoung** [comment]
Can't repro the linux issue, so closing. Feel free to reactivate if you can. As noted above, if you think the behavior is incorrectly designed, please add your comments to #236 instead.
