### ISSUE TITLE
[Question] When do you plan to publish v 2.0.4?

### ISSUE THREAD

**Issue by OCram85** [PowerShell/PowerShellGetv2#380]
Hey folks,

just wanted to know when the 2.0.4 version will be released?

> I'm asking because the versions `1.6.0` - `2.0.3` are still blocking any interaction with the PSGallery gepo.  -> And this  also affects any other environments with non transparent proxies or disabled ICMP messages.

**Comment by SydneyhSmith** [comment]
Hi @OCram85 , this is in regards to the PR #374  you submitted/merged in, correct?

**Comment by OCram85** [comment]
Yes, you're absolutely right.

I'm really wondering why this wasn't noticed earlier. I really thought this would affect more enterprise environments ^^

**Comment by alerickson** [comment]
@OCram85 I can release by tomorrow. Thanks for being patient with us!

**Comment by OCram85** [comment]
Awesome :D

> btw.: My question was not meant to be impolite ore rude :smile:

**Comment by alerickson** [comment]
@OCram85 no worries it wasn't taken as such!
Just wanted to update you that it's going to take a bit longer than anticipated, so release likely won't happen until next week or so at the earliest.

**Comment by alerickson** [comment]
@OCram85 2.0.4 is out now 😃

**Comment by OCram85** [comment]
@alerickson : Awesome, thanks!
Just updated the module on my production systems and it works again :grinning:
