### ISSUE TITLE
Update-ModuleManifest -CmdletsToExport, -AliasesToExport, and -FunctionsToExport empty array not allowed

### ISSUE THREAD

**Issue by natescherer** [PowerShell/PowerShellGetv2#409]
Is there a design reason that you can't provide an empty array to -CmdletsToExport and -AliasesToExport for Update-ModuleManifest?

Best practice for these two values in the manifest is to set an empty array for these if there aren't any to export, but it doesn't seem possible to do via Update-ModuleManifest.

Looking in the code I see both parameters have [ValidateNotNullOrEmpty()] set.

If there isn't a design reason for this, I'll fork and see if I can get this working.

Thanks!

**Comment by natescherer** [comment]
This also applies to -FunctionsToExport now that I think about it. Title updated.

**Comment by alerickson** [comment]
Don't believe there's a design reason for this, feel free to work on it.

**Comment by natescherer** [comment]
@pougetat Beat me to the punch on this, looks like. Closing.
