### ISSUE TITLE
PSModule: Code cleanup against DSC Resource Kit HQRM

### ISSUE THREAD

**Issue by johlju** [PowerShell/PowerShellGetv2#418]
I suggest we update the DSC resource `PSModule` to align more towards being a Highly Quality Resource Module (HQRM), as set in the guidelines in the [DSC Resource Kit](https://github.com/PowerShell/DscResources/blob/master/HighQualityModuleGuidelines.md). There are some limitation since we must align toward this repositories style guideline (the VS Code workspace settings), but we should make sure the common tests of the DscResource.Tests test framework should not be skipped as much as we can. 

I happy to put in the work to make the resource as much "HQRM" that we can.

**Comment by alerickson** [comment]
@johlju please feel free to work on this!

**Comment by johlju** [comment]
I’m been working on this since I submitted the issue, and have a PR in the works
https://github.com/johlju/PowerShellGet/tree/cleanup-psmodule
