### ISSUE TITLE
Update-ModuleManifest isn't parsing RequiredModules correctly

### ISSUE THREAD

**Issue by ebekker** [PowerShell/PowerShellGetv2#43]
When I try to use Update-ModuleManifest to update the module version, it fails complaining about the format of my `RequiredModules` element.  This may be a problem only with PowerShell v5.1, because I don't run into this issue on my local PowerShell 5.0 environment.

An example of this can be seen at:  https://ci.appveyor.com/project/ebekker/acmesharp/build/0.8.5.244#L2595

I've tried it using the simple string format (i.e. just the name of the required module) as well as the more complex hashtable format that specifies a name, version and Guid, but it seems to fail no matter what as long as the RequiredModules element is non-empty.

**Comment by ebekker** [comment]
You can reproduce this problem with just a couple steps:

``` PowerShell
PS> New-ModuleManifest -Path .\foo.psd1 -ModuleVersion 1.0.0 -RequiredModules ACMESharp
PS> Update-ModuleManifest -Path .\foo.psd1 -ModuleVersion 2.0.0
```

**Comment by bmanikm** [comment]
@ebekker
There are some improvements in Test-ModuleManifest cmdlet on PowerShell v5.1. 
From the error message, it looks like ACMESharp module is not available on your local machine under any of the module paths specified in $env:PSModulePath .

Ensure that **Test-ModuleManifest -Path .\foo.psd1** works fine before using the Update-ModuleManifest cmdlet.

**Comment by ebekker** [comment]
Thanks -- this fixed the issue once I resolved the availability issue.
