### ISSUE TITLE
 "Install-Module -Name AzureRM" fails

### ISSUE THREAD

**Issue by regulator-g** [PowerShell/PowerShellGetv2#443]
Steps to reproduce
------------------
OS: Ubuntu 18.04

after installing powershell, trying to download the AzureRM module fails. 

command:
Install-Module -Name AzureRM -AllowClobber

Expected behavior
-----------------

```success

```

Actual behavior
---------------

PS /root> Install-Module -Name AzureRM -AllowClobber

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its 
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from 
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
PackageManagement\Install-Package : The member 'TypesToProcess' in the module manifest is not valid: Cannot find path '/tmp/1449695378/Azure.Storage.4.6.1/.\Microsoft.WindowsAzure.Commands.Storage.Types.ps1xml' because it does not exist.. Verify that a valid value is specified for this field in the '/tmp/1449695378/Azure.Storage.4.6.1/Azure.Storage.psd1' file.                                                                                                          At /opt/microsoft/powershell/6/Modules/PowerShellGet/PSModule.psm1:9491 char:21                                      + ...          $null = PackageManagement\Install-Package @PSBoundParameters                                          +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                          + CategoryInfo          : ResourceUnavailable: (/tmp/1449695378...re.Storage.psd1:String) [Install-Package], Exception                                                                                                                    + FullyQualifiedErrorId : Modules_InvalidManifest,Microsoft.PowerShell.Commands.TestModuleManifestCommand,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage                                                                                                                                                                                        PS /root>                  

```

Environment data
----------------

<!-- If relevant to your issue, please paste output from the following commands -->

Recently aware there is an "Az" module but the AzureRM module is more commonly referenced. 

```

**Comment by edyoung** [comment]
What versions of PowerShell and PowerShelGet do you have?
($psversiontable; get-module powershellget -listavailable)

**Comment by regulator-g** [comment]
Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Linux 4.18.0-16-generic #17~18.04.1-Ubuntu SM...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Name              : PowerShellGet
Path              : /opt/microsoft/powershell/6/Modules/PowerShellGet/PowerShel
                    lGet.psd1
Description       : PowerShell module with commands for discovering, 
                    installing, updating and publishing the PowerShell 
                    artifacts like Modules, DSC Resources, Role Capabilities 
                    and Scripts.
Guid              : 1d73a601-4a6c-43c5-ba3f-619b18bbb404
Version           : 1.6.7
ModuleBase        : /opt/microsoft/powershell/6/Modules/PowerShellGet
ModuleType        : Script
PrivateData       : {SupportedPowerShellGetFormatVersions, 
                    PackageManagementProviders, PSData}
AccessMode        : ReadWrite
ExportedAliases   : {[inmo, inmo], [fimo, fimo], [upmo, upmo], [pumo, pumo]}
ExportedCmdlets   : {}
ExportedFunctions : {[Find-Command, Find-Command], [Find-DSCResource, 
                    Find-DSCResource], [Find-Module, Find-Module], 
                    [Find-RoleCapability, Find-RoleCapability]...}
ExportedVariables : {}
NestedModules     : {}

**Comment by alerickson** [comment]
@regulator-g can you first try updating to the latest version of PowerShellGet and PackageManagement.   If you're still encountering this issue can run the command with -verbose?

**Comment by regulator-g** [comment]
@alerickson all I did was add the powershell repo, install powershell, then try to install AzureRM

https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6#ubuntu-1804

Another guy posted this issue in the main powershell git and got told the problem is with PowersShellGet..

https://github.com/PowerShell/PowerShell/issues/8093

**Comment by SydneyhSmith** [comment]
@regulator-g This is likely happening becuase AzureRM is only for Windows, whereas Az is cross plat, try running: 
```Install-Module -Name Az -force```

**Comment by edyoung** [comment]
As Syndey says, the AzureRM module will not work on Linux but the Az module should.
