### ISSUE TITLE
DefaultCommandPrefix not honoured by Test-ModuleManifest Cmdlet

### ISSUE THREAD

**Issue by rufer7** [PowerShell/PowerShellGetv2#45]
Rebecca Roenitz suggested to open a bug on this project for the following problem.

We received the following mail from PowerShell Gallery after the last release of our PowerShell module `biz.dfch.PS.Appclusive.Client`:

 

> Thank you for contributing to the PowerShell Gallery.
 
> Item biz.dfch.PS.Appclusive.Client 4.9.1.20161024 failed during Install: A command with name 'Get-Job' is already available on this system. This module 'biz.dfch.PS.Appclusive.Client'
 may override the existing commands. If you still want to install this module 'biz.dfch.PS.Appclusive.Client', use -AllowClobber parameter.
 
> By default and for security reasons, Install-Module blocks installation of modules and scripts that override commands that are already present on the system. This is done to ensure that users who acquire code from the PowerShell Gallery are made aware of the conflict, while allowing them the opportunity to install if they choose to do so.
 
> You should consider renaming your command. If there is a requirement to keep this name, you should modify the description to explain the over-ride to users as they will receive this error message, and installation will fail. You should include information about how to install the module, which is described in the error message.
 
> If you have any questions about this, please reply to this mail or use the Contact Us page.
 
> Thank you for your cooperation,
 
> PowerShell Gallery Administrators

We are aware of the fact, that the Cmdlet has the same name like a command, which is already available on the system. That's the reason why we defined a "DefaultCommandPrefix" in .psd1 file. For us it's not clear, why the installation of the module fails even if we explicitly defined the "DefaultCommandPrefix"?

**Comment by ebekker** [comment]
This could also be a potential security hole if the fully resolved name is not already being evaluated.

For example if I define a cmdlet `Get-ificate` and the module manifest has a `DefaultCommandPrefix` of `Cert` then the naked cmdlet name won't be in conflict, but the fully resolved name will be.

**Comment by SydneyhSmith** [comment]
Closing as its already tracked in https://github.com/PowerShell/PowerShell/issues/2590
