### ISSUE TITLE
Publish-Module and Authenticated Feeds

### ISSUE THREAD

**Issue by jianyunt** [PowerShell/PowerShellGetv2#47]
_From @whatatripp on July 6, 2016 15:39_

Our customers seem to have a lot of issues with Publish-Module when they use authenticated feeds.

Windows Integrated Authentication doesn't work at all (the 401/challenge isn't recognized), and trying to use ProGet's "name:pass" convention as the API key for doesn't work, because OneGet/PowerShellGet/something is encoding the ":" and non-alpha characters incorrectly.

Is this, or can this be supported? Currently, it's entirely unusable with authenticated feeds.

Here's an example thread from our support forums: [http://inedo.com/support/questions/4964](http://inedo.com/support/questions/4964)

_Copied from original issue: OneGet/oneget#192_

**Comment by bmanikm** [comment]
As mentioned in http://inedo.com/support/questions/4964 latest version of PowerShellGet has support for authenticated feeds.
