### ISSUE TITLE
OneGet team should work with PSScriptAnalyzer team to show report cards to authors and users

### ISSUE THREAD

**Issue by jianyunt** [PowerShell/PowerShellGetv2#49]
_From @KirkMunro on February 2, 2016 21:21_

I wanted to share this issue because this really needs buy-in from both PSScriptAnalyzer and OneGet.  See here: https://github.com/PowerShell/PSScriptAnalyzer/issues/436

_Copied from original issue: OneGet/oneget#168_

**Comment by edyoung** [comment]
We'd like to make more psscriptanalyzer warnings available inPowerShellGallery.com. No plans to do it in OneGet or PowerShellGet.
