### ISSUE TITLE
Add support for Uninstall

### ISSUE THREAD

**Issue by kittholland** [PowerShell/PowerShellGetv2#5]
Chocolatey has support for uninstalls but PowershellGet does not, could add support for the chocolatey uninstall functionality? 

https://github.com/chocolatey/choco/wiki/CommandsUninstall

**Comment by bmanikm** [comment]
@kittholland PowerShellGet is an in-box PowerShell Module. If newer versions of this module are installed from the PSGallery, you can uninstall those versions using Uninstall-Module cmdlet.

**Comment by kilasuit** [comment]
@kittholland - There is the Uninstall-Module and Uninstall-Script functions that should provide the functionality that you are asking for
