### ISSUE TITLE
Add support for installing the catalog signed modules on downlevel PS versions.

### ISSUE THREAD

**Issue by bmanikm** [PowerShell/PowerShellGetv2#52]
PowerShellGet support catalog signed module verification during install and update operations on PowerShell Version 5.1 or newer.

Test-FileCatalog cmdlet is not available on PowerShell Versions 5.0 and lower versions. 

Options:
      - Ensure the Microsoft.PowerShell.Security module gets published to the PSGallery. Add Microsoft.PowerShell.Security module as a dependency. OR
      - Add Test-FileCatalog cmdlet functionality in PowerShellGet

**Comment by rkeithhill** [comment]
Please do NOT do this until someone fixes the PSGallery to not allow packages to be published that result in this user experience:
```
06-04 19:03:04 20> install-module psscriptanalyzer -Scope CurrentUser
PackageManagement\Install-Package : The module 'PSScriptAnalyzer' cannot be installed because the catalog signature in 'PSScriptAnalyzer.cat' does not match the hash generated from the module.
At C:\program files\powershell\6-preview\Modules\PowerShellGet\1.6.0\PSModule.psm1:2057 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : InvalidCatalogSignature,ValidateAndGet-AuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```
This module was published last week by Microsoft.

**Comment by edyoung** [comment]
We do scan modules which are uploaded and the scan did detect this issue, but it runs asynchronously from the upload process and requires a manual step to remove the module. Will see if I can work out want went wrong in the publishing process. To be honest, I don't expect to get to this particular issue any time soon.

**Comment by rkeithhill** [comment]
I get it - everyone is real busy.  But it is too bad that every time this happens and folks run into errors like this, it erodes the confidence in the PSGallery and the PowerShell module ecosystem in general.  :-(

**Comment by edyoung** [comment]
We don't plan to backport this functionality to be compatible with older versions of PowerShell
