### ISSUE TITLE
Issues when older nuget.exe installed in Program Files

### ISSUE THREAD

**Issue by bwright86** [PowerShell/PowerShellGetv2#556]
## Issue Description:
Publish-Module favors any `nuget.exe` file found in Program Files, even if it doesn't meet the minimum version requirement.

I am experiencing this, as a non-admin user on my desktop, an older version of `nuget.exe` is installed in Program Files. But if I download a newer version from Microsoft and place it in my `AppData Local` path, the logic does not allow it to be discovered, but instead prompts me to install `nuget.exe` in one of the following locations:

1. Program Files
2. User's App Data local path
3. A location available from $env:PATH

Here is the location that this is happening:
https://github.com/PowerShell/PowerShellGet/blob/712d6d3b64980bba1a46f20e5e843aef8319de53/src/PowerShellGet/private/functions/Install-NuGetClientBinaries.ps1#L96

### Recommended fix:
``` Powershell
if( (Microsoft.PowerShell.Management\Test-Path -Path $programDataExePath) -and ($programDataExePath | Microsoft.PowerShell.Core\Get-Command).Version -ge $script:NuGetExeMinRequiredVersion )
```

https://github.com/PowerShell/PowerShellGet/blob/712d6d3b64980bba1a46f20e5e843aef8319de53/src/PowerShellGet/private/functions/Install-NuGetClientBinaries.ps1#L100

### Recommended fix:
``` powershell
elseif( (Microsoft.PowerShell.Management\Test-Path -Path $applocalDataExePath) -and ($applocalDataExePath | Microsoft.PowerShell.Core\Get-Command).Version -ge $script:NuGetExeMinRequiredVersion )
```

**Comment by SydneyhSmith** [comment]
@bwright86 thanks for opening this issue and for proposing a solution...would you be interested in submitting this as a PR? If not we still should be able to make this fix before our final patch release.
Thanks!

**Comment by bwright86** [comment]
Thank you Sydney, I have created a PR with the fixes, and formatted it similar to other code.
