### ISSUE TITLE
Documentation link in readme is a 404

### ISSUE THREAD

**Issue by sandersaares** [PowerShell/PowerShellGetv2#559]
I am trying to find out what is the proper process to install/upgrade PowerShellGet. There is a Documentation link in the readme that leads to https://msdn.microsoft.com/en-us/powershell/gallery/psget/overview

This page is a 404, howerver!

**Comment by SydneyhSmith** [comment]
Thanks for letting us know--we will update the link. For now, this should be correct: 
https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-6

**Comment by ChrisMenning** [comment]
It's still 404ing.

**Comment by SydneyhSmith** [comment]
Should be fixed by https://github.com/PowerShell/PowerShellGet/pull/578

**Comment by he852100** [comment]
@SydneyhSmith 


 My Packages > xxxx > Edit

Read more

<https://aka.ms/psgallery-managing-items>

My Packages > xxxx > Unlist

You can control how your packages are listed using the checkbox below. As per policy

<https://docs.microsoft.com/en-us/powershell/gallery/how-to/publishing-items/deleting-items>
