### ISSUE TITLE
Unable to find module providers (PowerShellGet) on Linux

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShellGetv2#56]
_From @shaolinint on November 4, 2016 8:21_

Expected behavior
-----------------
Successfully install psscriptanalyzer module

Actual behavior
---------------
**Failed to install the selected module. Error below:**
```
> PS /home/shaolinint/powershell> Install-Module psscriptanalyzer                                                            PackageManagement\Install-Package : Unable to find module providers (PowerShellGet).
> At /opt/microsoft/powershell/6.0.0-alpha.12/Modules/PowerShellGet/PSModule.psm1:1823 char:21
> + ...          $null = PackageManagement\Install-Package @PSBoundParameters
> +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
>     + FullyQualifiedErrorId : UnknownProviders,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

Environment data
----------------
```
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
GitCommitId                    v6.0.0-alpha.12
CLRVersion
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

_Copied from original issue: PowerShell/PowerShell#2614_

**Comment by bmanikm** [comment]
@shaolinint This issue got fixed with [the latest version of PowerShellGet](https://www.powershellgallery.com/packages/PowerShellGet).

**Comment by ghost** [comment]
I'm using PowerShell on centOS 7 and I've got the problem when install module as follows:

PS /home/OneDrive/scripts> Install-Module -Name OneDrive -Scope CurrentUser  
PackageManagement\Install-Package : Unable to find module providers (PowerShellGet).
At /home/OneDrive/PowerShellGet/PowerShellGet/PSModule.psm1:1809 char:21
- ...          $null = PackageManagement\Install-Package @PSBoundParameters
-                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidArgument: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
  - FullyQualifiedErrorId : UnknownProviders,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by bmanikm** [comment]
@tewgup Could you please try after installing the latest version of PowerShellGet from PSGallery? Use below command to update the PowerShellGet module:
- Launch PowerShell with Sudo permissions

``` powershell
Install-Package -Name PowerShellGet -Source https://www.powershellgallery.com/api/v2/ -ProviderName NuGet -ExcludeVersion -Destination $PSHome/Modules
```

**Comment by ghost** [comment]
I was trying to install the latest version from PowerShell Gallery but got the error. 

PS /home/tew> Install-Module -Name PowerShellGet -Force  
PackageManagement\Install-Package : Unable to find module providers 
(PowerShellGet).
At /opt/microsoft/powershell/6.0.0-alpha.12/Modules/PowerShellGet/PSModule.psm1
:1823 char:21
- ...          $null = PackageManagement\Install-Package @PSBoundParameters
-                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidArgument: (Microsoft.Power....InstallPack 
    age:InstallPackage) [Install-Package], Exception
  - FullyQualifiedErrorId : UnknownProviders,Microsoft.PowerShell.PackageMan 
    agement.Cmdlets.InstallPackage

PS /home/tew> Install-Package -Name PowerShellGet -Source https://www.powershellgallery.com/api/v2/ -ProviderName NuGet -ExcludeVersion -Destination $PSHome/Modules  
Install-Package : Unable to find package providers (NuGet).
At line:1 char:1
- Install-Package -Name PowerShellGet -Source https://www.powershellgal ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidArgument: (Microsoft.Power....InstallPack 
    age:InstallPackage) [Install-Package], Exception
  - FullyQualifiedErrorId : UnknownProviders,Microsoft.PowerShell.PackageMan 
    agement.Cmdlets.InstallPackage

**Comment by bmanikm** [comment]
PackageManagement module is completely broken on non-Windows platforms in Alpha12 release. Please use the Alpha11 release. OneGet/oneget#239

**Comment by ghost** [comment]
Thanks for your supporting. I can install OneDrive Module now but there is another problem when used "Get-Command -Module OneDrive", there came out **nothing on CentOS 7** compare to Windows.

For example I got list of commands on Windows as follows:
PS C:\Users\Admin> Get-Command -Module OneDrive

CommandType     Name                                               Version    Source

---

Function        Add-ODItem                                         0.9.2      OneDrive
Function        Format-ODPathorIDString                            0.9.2      OneDrive
Function        Get-ODAuthentication                               0.9.2      OneDrive
Function        Get-ODChildItems                                   0.9.2      OneDrive
Function        Get-ODDrives                                       0.9.2      OneDrive
Function        Get-ODItem                                         0.9.2      OneDrive
Function        Get-ODItemProperty                                 0.9.2      OneDrive
Function        Get-ODWebContent                                   0.9.2      OneDrive
Function        New-ODFolder                                       0.9.2      OneDrive
Function        Remove-ODItem                                      0.9.2      OneDrive
Function        Search-ODItems                                     0.9.2      OneDrive

**Comment by bmanikm** [comment]
Hi @tewgup , could you please provide the output of following on **CentOS 7** to understand the issue?

``` powershell
$env:PSModulePath
Get-InstalledModule OneDrive | fl *
Get-Module OneDrive -ListAvailable
$PSVersionTable
```

**Comment by ghost** [comment]
Please find the output attached.

[output.pdf](https://github.com/PowerShell/PowerShellGet/files/586707/output.pdf)

**Comment by bmanikm** [comment]
It looks like OneDrive is not compatible for non-Windows platforms. 

``` powershell
PS /home/manikb> ipmo OneDrive -Verbose                                         
VERBOSE: Loading module from path 
'/home/manikb/.local/share/powershell/Modules/OneDrive/1.0.3/OneDrive.psd1'.
VERBOSE: Populating RepositorySourceLocation property for module OneDrive.
ipmo : The given assembly name or codebase was invalid. (Exception from 
HRESULT: 0x80131047)
At line:1 char:1
+ ipmo OneDrive -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadExcep 
   tion
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell 
   .Commands.ImportModuleCommand 

```

Refer below URLs to find the compatible modules:
https://msdn.microsoft.com/en-us/powershell/gallery/psget/module/modulewithpseditionsupport
https://msdn.microsoft.com/en-us/powershell/gallery/psgallery/psgallery_pseditions
