### ISSUE TITLE
Issues generating call reports with "Get-SfBOCallData"

### ISSUE THREAD

**Issue by vdmartos** [PowerShell/PowerShellGetv2#568]
Hi,

We're generating a call report with this script "Get-SfBOCallData" and there're some issues in the generated report that I need to review and solve.

This script generates various CSV files and we're working with the info contanied in the file named "AllAudioCalls".

The issues encountered are the following:

1. The date and time has a 9-hour lag despite the fact that, according to Office 365 information, the data is hosted in Europe.

2. Internal calls appears twice (repeated) in the report. External calls with the PSTN or with federated users are displayed correctly, that is, once.

3. Some calls appears with the source (From) and destination (To) reversed. That is, the From appears as To and viceversa.

4. Is it possible to establish a relationship of a transferred call with the original call?

5. Is it possible to establish a relationship on calls to the same meeting (conference call)?

Regards.

**Comment by SydneyhSmith** [comment]
@vdmartos thanks for opening this issue, unfortunately we do not own this cmdlet/module so we can not be of much help please forward your issue to the module owner...sorry for any confusion
