### ISSUE TITLE
Allow including source control metadata in Publish-Module

### ISSUE THREAD

**Issue by davidroberts63** [PowerShell/PowerShellGetv2#576]
Is it reasonable to allow Publish-Module to include source control metadata? That is the following:
* type (git|tfs|svn|etc...)
* url
* branch
* commit

The nuspec allows for including this [metadata](https://github.com/NuGet/NuGet.Client/blob/522acd2ad8120003abf5bf7c21fe468526c22ae7/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd#L79) in the nuspec.

If so, I've two overall ideas.

1. Pull this data from the PSData, in a similar manner as the LicenseUri.
   This would require changes to [New-NuSpecFile](https://github.com/PowerShell/PowerShellGet/blob/development/src/PowerShellGet/private/functions/New-NuspecFile.ps1) and [Publish-PSArtifactUtility](https://github.com/PowerShell/PowerShellGet/blob/development/src/PowerShellGet/private/functions/Publish-PSArtifactUtility.ps1). And I *think* that's all. Developers would have to find their own process for injecting that into their PSData, however if they are using CI/CD process then they may be able to do this within a reasonable amount of effort.
1. Allow this to be specified as a parameter to Publish-Module.
    This would require changes to the same functions as above, along with [Publish-Module](https://github.com/PowerShell/PowerShellGet/blob/development/src/PowerShellGet/public/psgetfunctions/Publish-Module.ps1) itself. Though this option would be easier for a CI/CD process to integrate with.

I also have a third idea, but that is allowing developers to specify their own nuspec and adjusting as needed during the Publish-Module process. However I think the changes that would require would be too large. But I wanted to mention it as an idea.

**Comment by ThomasNieto** [comment]
PowerShellGet is currently being redesigned. You should place your comment in https://github.com/PowerShell/PowerShell-RFC/pull/237 for your feature be heard.

**Comment by davidroberts63** [comment]
Will do. Thank you.
