### ISSUE TITLE
Enable Non-PAT based authentication with VSTS PackageManagement feeds

### ISSUE THREAD

**Issue by mmaitre314** [PowerShell/PowerShellGetv2#59]
Is it possible to host PowerShell modules in VSTS Nuget repoes?

I hit two issues trying to do that:
- VSTS uses Nuget V3 instead of V2 (ex: https://xxx.pkgs.visualstudio.com/_packaging/yyy/nuget/v3/index.json)
- VSTS requires user authentication

**Comment by bmanikm** [comment]
@mmaitre314 
- Yes, you can host the PowerShell modules in a VSTS PackageManagement feeds. 
- VSTS PackageManagement also provides the NuGet v2 based URL. [More details](https://www.visualstudio.com/en-us/docs/package/nuget/nuget-2x) 
- NuGet V2 Source location is https://xxx.pkgs.visualstudio.com/_packaging/yyy/nuget/v2/
- You will have to use the -Credential parameter on PowerShellGet cmdlets to work with the authenticated feeds.

**Comment by maitre-matt** [comment]
Thanks! I could not get authentication to work:

```
> Register-PSRepository -Name aaa -SourceLocation  "https://xxx.pkgs.visualstudio.com/_packaging/yyy/nuget/v2/" -Credential (Get-Credential -UserName "user@domain.com" -Message "Authenticate")

Register-PSRepository : The specified Uri 'https://xxx.pkgs.visualstudio.com/_packaging/yyy/nuget/v2/' for parameter 'SourceLocation' is an invalid Web Uri. Please ensure that it meets the Web Uri requirements.
```

The Uri looks correct (opens in browser), so I assume the error is actually due to auth failing. In VSTS docs I see PATs mentioned for auth with Nuget v2 instead of regular AAD user auth. Is that the only option? I don't mind using PATs to publish modules, but for my users that want to consume modules this is a non starter.

**Comment by mmaitre314** [comment]
Per offline discussion, VSTS PackageManagement feed authentication is not working in PowerShellGet without PAT tokens.

**Comment by alerickson** [comment]
Please go to Azure Dev Ops and under Security > Alternative credentials, click on the "Enable alternate authentication credentials" in order to use non-PAT credentials.
