### ISSUE TITLE
Publish-Module does not work against repository with basic authentication

### ISSUE THREAD

**Issue by cpolydorou** [PowerShell/PowerShellGetv2#60]
When using a nuget server repository with basic authentication to publish a module the command fails with exception:

Publish-PSArtifactUtility : Failed to publish module '*******': 'Cannot prompt for input in non-interactive mode
.
'.
At C:\Users\admin\Desktop\PowershellGet\PowerShellGet\PSModule.psm1:1227 char:17
+                 Publish-PSArtifactUtility -PSModuleInfo $moduleInfo `
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : FailedToPublishTheModule,Publish-PSArtifactUtility

1. Use a repository protected with Basic Authentication
2. Install PowershellGet 1.1.2.0 (I've tried with previous versions too.)
3. Try to publish a module 

This happens with many versions of nuget.exe except version 3.4.4 where there is a 401 http error code but the module get's published. Moreover, when uploading a module that has depended modules from the same repository the command does not find the existing modules and fails. Perhaps this is related to the authentication issue.

> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

> Get-Module
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0        GroupSet                            {BuildResourceCommonParameters, BuildResourceString, Group...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, En...
Script     1.1.0.0    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     1.1.2.0    PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCap...
Script     1.0        ProcessSet                          {BuildResourceCommonParameters, BuildResourceString, Proce...
Manifest   1.1        PSDesiredStateConfiguration         {Invoke-DscResource, Publish-DscConfiguration, Set-DscLoca...
Script     1.2        PSReadline                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PS...
Script     1.0        ServiceSet                          {BuildResourceCommonParameters, BuildResourceString, Servi...
Script     1.0        WindowsFeatureSet                   {BuildResourceCommonParameters, BuildResourceString, Windo...
Script     1.0        WindowsOptionalFeatureSet           {BuildResourceCommonParameters, BuildResourceString, Windo...
> Get-Module -ListAvailable PowerShellGet,PackageManagement

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.0.0    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...
Binary     1.0.0.0    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packa...
Script     1.1.1.0    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}

> Get-PackageProvider
PS C:\Users\admin\Desktop\PowershellGet> Get-PackageProvider

Name                     Version          DynamicOptions
----                     -------          --------------
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
NuGet                    2.8.5.207        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag...
PowerShellGet            1.1.1.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, ...
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent
> Get-PackageProvider -ListAvailable
Name                     Version          DynamicOptions
----                     -------          --------------
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
NuGet                    2.8.5.207        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag...
PowerShellGet            1.1.1.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, ...
PowerShellGet            1.0.0.1
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent

**Comment by bmanikm** [comment]
@cpolydorou your authenticated feed needs to be registered with NuGet.exe with credentials to publish.

**Comment by cpolydorou** [comment]
Hi bmanikm,

Shouldn't this be covered by the -Credential parameter?

**Comment by bmanikm** [comment]
@cpolydorou 
- By default NuGet.exe prompts for the username and password for authenticated feeds during Push operation. 
- And there is no option for providing the username and password as an input during push operation. 
- If authenticated feed is added to the NuGet sources list with username and password, it wont prompt for username and password during Push operation.

``` powershell
PS C:\WINDOWS\system32> C:\NuGet.exe push -help
push: invalid arguments.
usage: NuGet push <package path> [API key] [options]

Pushes a package to the server and publishes it.
NuGet's default configuration is obtained by loading %AppData%\NuGet\NuGet.config, then loading any nuget.config or .nuget\nuget.config starting from root of drive and ending in current directory.

     Specify the path to the package and your API key to push the package to the server.

options:

 -Source                (src)  Specifies the server URL. If not specified, nuget.org is used unless DefaultPushSource config value is set in the NuGet config file.
 -ApiKey                       The API key for the server.
 -Timeout                      Specifies the timeout for pushing to a server in seconds. Defaults to 300 seconds (5 minutes).
 -DisableBuffering             Disable buffering when pushing to an HTTP(S) server to decrease memory usage. Note that when this option is enabled, integrated windows authentication might
                               not work.
 -Help                  (?)    help
 -Verbosity                    Display this amount of details in the output: normal, quiet, detailed.
 -NonInteractive               Do not prompt for user input or confirmations.
 -ConfigFile                   The NuGet configuration file. If not specified, file %AppData%\NuGet\NuGet.config is used as configuration file.

For more information, visit http://docs.nuget.org/docs/reference/command-line-reference

PS C:\WINDOWS\system32> C:\NuGet.exe sources -help
usage: NuGet sources <List|Add|Remove|Enable|Disable|Update> -Name [name] -Source [source]

Provides the ability to manage list of sources located in %AppData%\NuGet\NuGet.config

options:

 -Name                                 Name of the source.
 -Source                        (src)  Path to the package(s) source.
 -UserName                             UserName to be used when connecting to an authenticated source.
 -Password                             Password to be used when connecting to an authenticated source.
 -StorePasswordInClearText             Enables storing portable package source credentials by disabling password encryption.
 -Format                               Applies to the list action. Accepts two values: Detailed (the default) and Short.
 -Help                          (?)    help
 -Verbosity                            Display this amount of details in the output: normal, quiet, detailed.
 -NonInteractive                       Do not prompt for user input or confirmations.
 -ConfigFile                           The NuGet configuration file. If not specified, file %AppData%\NuGet\NuGet.config is used as configuration file.

For more information, visit http://docs.nuget.org/docs/reference/command-line-reference
```

**Comment by cpolydorou** [comment]
@bmanikm 

I'm not quite sure I follow...

Let's say that I register the feed with nuget.exe using the credentials. This source will not be available as a Powershell repository, how am I going to publish using the Publish-Module command?

**Comment by cpolydorou** [comment]
Moreover, at the module's page on the gallery ([https://www.powershellgallery.com/packages/PowerShellGet/1.1.1.0](url)), under the release notes of version 1.1.1.0 it is stated that this version supports authenticated feeds. What kind of authentication is supported?

**Comment by godefroi** [comment]
@bmanikm I am having this same issue, and though I registered my source with NuGet.exe with the credentials, it still doesn't work (fails with the exact same error message). Do you have any other suggestions? Should we re-open this issue?

**Comment by bmanikm** [comment]
@godefroi Could you please let us know whether your repro steps are different from https://github.com/PowerShell/PowerShellGet/issues/91 ? If yes, could you please create a new issue with the repro steps along with instructions for authenticated feed setup, so that we can ensure that your scenario is validated/verified/tested with the fix?

**Comment by godefroi** [comment]
@bmanikm same steps, except I'm using an Artifactory feed and not a VSTS one. Other than that, same steps, same results.

**Comment by godefroi** [comment]
@bmanikm In fact, I'm now getting this same error from the command line in interactive mode:
```
PS C:\BuildAgent\work\d2c37705563fe286> publish-module -path MyModules\MyModule -repository MyRepository -nugetapikey "$($un):$($pw)"
Publish-PSArtifactUtility : Failed to publish module 'MyModule': 'Cannot prompt for input in non-interactive mode.
'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.1.2.0\PSModule.psm1:1227 char:17
+                 Publish-PSArtifactUtility -PSModuleInfo $moduleInfo `
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : FailedToPublishTheModule,Publish-PSArtifactUtility
```

**Comment by godefroi** [comment]
@bmanikm It seems that replacing NuGet.exe version 2.8 with NuGet.exe version 3.5 has solved the problem.

**Comment by Geogboe** [comment]
@godefroi Can you elaborate on how you did this? My understanding is that PowerShellGet uses the Nuget Provider Assembly, not the plain old nuget.exe binary. Thanks!

**Comment by godefroi** [comment]
@Geogboe I'm not sure what you're asking. NuGet.exe is definitely present; when I updated it, the problem was solved.

**Comment by JVimes** [comment]
Updating PowerShellGet fixed the "cannot prompt for input in non-interactive mode" error in my environment.

Since it was on the non-PowerShellGet version of PowerShellGet, I used Install-Module instead of Update-Module:

```powershell
Install-Module PowerShellGet -Force
```
