### ISSUE TITLE
Q: Intended behavior for   Parameters  "-Force"  "-Confirm" in Install-PackageProvider (and others)

### ISSUE THREAD

**Issue by WernerMairl** [PowerShell/PowerShellGetv2#62]
Hi
Please help me to understand the intended behavior for -Force and -Confirm!

My Usecase: "Install-PackageProvider"
Requirements:
1. ensure a certain minimumversion of a provider (-MinimumVersion)
2. no confirmation dialog needed (assuming answer YES) (-Confirmation:$false)
  - not for trust in download source
  - not for overriding existing version
3. No Download/install needed if just installed (-Force:$false)
4. do all of that with one commandlet (Usability/nice to have)

Sample
on my machine the Version 2.8.5.**127** of the Nuget Packageprovider is installed.
my script should "ensure" that Version 2.8.5.**201** (-Minimumversion) is installed 

in our first try we are using the following call:

Install-PackageProvider -Name "NuGet" -MinimumVersion "2.8.5.201" -Scope "CurrentUser" 

result: PS-ISE shows a Confirmation Dialog for a not trusted Repository (https://oneget.org)
After a click on OK it installs the Packageprovider => OK and expected behavior

My next challange: how suppress that Confirmation Warning ?
proposed solution by Powershell (general)
use "-Confirmation:$false"

BUT: this does not helps!
It seems that "Install-PackageProvider" ignores the -Confirmation Settings for that security question!

Workaround: with the -Force Switch i'm able to work around this problem... the Confirmation-Dialog does NOT shows up.

My question about this:
In my understanding the "-Force" switch has another meaning
it should solve/override questions about versioning/overriding installed versions.

But here the -Force switch is used for 2 different purposes => conflict.
purpose 1: security/trust on download sources 
purpose 2: install-behavior (override or not)

Is this a bug in the Install-PackageProvider Cmdlet?
(some other PowerShellGet cmdlet seems to have the same behavior)

regards
Werner

**Comment by WernerMairl** [comment]
A good discussion about the same PS-Guidelines/Pattern Problem from the Azure-PS team:

https://github.com/Azure/azure-powershell/issues/475

**Comment by SydneyhSmith** [comment]
@WernerMairl going through older issues and you are correct on the behaviors of -Force and -Confirm, -Confirm is $false by default, and adds a layer of confirmation...-Force skips checks on both installation conflicts, and installation trust--tracking this here: #461
