### ISSUE TITLE
"Get-PackageProvider" API surface improvements (Feature Request)

### ISSUE THREAD

**Issue by WernerMairl** [PowerShell/PowerShellGetv2#63]
## Summary
PackageProvider are versioned/have versions.

Cmdlets like "Install-PackageProvider" have a lot of  version features (MinVerion,MaxVersion, requiredversion)

Get-PackageProvider has NO XXXVersion Arguments!

## Expected Behavior
the user should be able to verify if a CERTAIN version of provider is installed or not

## Current Behavior
Get-PackageProvider returns the installed version. the compare operation (less, greather, equal) must be done by the user => error prone

## Possible Solution
Solution 1: Add  -MinVersion -MaxVersion -RequiredVersion on "Get-PackageProvider"
Solution 2: implement a (new) cmdlet "Get-InstalledPackageProvider with all that feature
Solution 3: export (=make public available) "Validate-VersionParameters" to avoid error-prone re-implements on the user side

## Your Environment
PowershellGet 1.1.1.0 on Windows 10/PS 5

**Comment by ThomasNieto** [comment]
@edyoung This issue should be moved to [OneGet](https://github.com/oneget/oneget)
