### ISSUE TITLE
Did I get the right version?

### ISSUE THREAD

**Issue by Ofer-Gal** [PowerShell/PowerShellGetv2#637]
I do  Update-Module -Name PnP.PowerShell
and
Install-Module -Name PnP.PowerShell -RequiredVersion 1.2.0

but get-Module PnP.PowerShell Shows version 0.3.28 

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   0.3.28     PnP.PowerShell                      {Add-PnPAlert, Add-PnPApp, Add-

So did it update or not? 
Thank you for a great Module

**Comment by alerickson** [comment]
Hi @Ofer-Gal, I transferred this issue to this repository because this looks like an issue with PowerShellGet, not the PnP.PowerShell module.  It doesn't look like version 1.2.0 is installing.  Could you try running 
`Install-Module -Name PnP.PowerShell -RequiredVersion 1.2.0 -Debug -Verbose`

**Comment by Ofer-Gal** [comment]
That worked Thanks
