### ISSUE TITLE
Unable to resolve package

### ISSUE THREAD

**Issue by ErikMathijsen** [PowerShell/PowerShellGetv2#641]
<!--
If this is a bug report, make sure you are able to reproduce it with the latest PowerShellGet module from master branch.
- Search the [existing issues](https://github.com/PowerShell/PowerShellGet/issues?utf8=%E2%9C%93&q=is%3Aissue).
- Fill out the following template:

PS C:\Windows\system32> Connect-MsolService

PS C:\Windows\system32> Install-Module -name MicrosoftPowerBIMgmt -force -debug -verbose
DEBUG: 00:00:00.0000004 Current running environment: Windows PowerShell.
DEBUG: 00:00:00.2469522 Trying provider assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr\
Microsoft.PackageManagement.MsiProvider.dll
DEBUG: 00:00:00.2469478 Trying provider assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr\
Microsoft.PackageManagement.NuGetProvider.dll
DEBUG: 00:00:00.2470021 Trying provider assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr\
Microsoft.PackageManagement.CoreProviders.dll
DEBUG: 00:00:00.2471015 Trying provider assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr\
Microsoft.PackageManagement.MsuProvider.dll
DEBUG: 00:00:00.2481953 Trying provider assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr\
Microsoft.PackageManagement.MetaProvider.PowerShell.dll
DEBUG: 00:00:00.2483738 Trying provider assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr\
Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.2548208 Attempting loading of assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fu
llclr\Microsoft.PackageManagement.MsuProvider.dll
DEBUG: 00:00:00.2552504 Attempting loading of assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fu
llclr\Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.2553149 Attempting loading of assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fu
llclr\Microsoft.PackageManagement.CoreProviders.dll
DEBUG: 00:00:00.2565633 Attempting loading of assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fu
llclr\Microsoft.PackageManagement.MsiProvider.dll
DEBUG: 00:00:00.2645071 Attempting loading of assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fu
llclr\Microsoft.PackageManagement.NuGetProvider.dll
VERBOSE: Acquiring providers for assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr\Microso
ft.PackageManagement.MsuProvider.dll
VERBOSE: Acquiring providers for assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr\Microso
ft.PackageManagement.CoreProviders.dll
VERBOSE: Acquiring providers for assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr\Microso
ft.PackageManagement.MsiProvider.dll
VERBOSE: Acquiring providers for assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr\Microso
ft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.2699655 Attempting loading of assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fu
llclr\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
VERBOSE: Acquiring providers for assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr\Microso
ft.PackageManagement.NuGetProvider.dll
VERBOSE: Acquiring providers for assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr\Microso
ft.PackageManagement.MetaProvider.PowerShell.dll
DEBUG: 00:00:00.3082065 Registering providers via metaproviders for assembly Microsoft.PackageManagement.MetaProvider.PowerShell.Internal.PowerShellMetaProvider
DEBUG: 00:00:00.3611335 Initializing provider 'Programs'
DEBUG: 00:00:00.3613425 Initializing provider 'zipfile'
DEBUG: 00:00:00.3613614 Initializing provider 'Bootstrap'
DEBUG: 00:00:00.3613827 Initializing provider 'WebDownloader'
DEBUG: 00:00:00.3614467 Initializing provider 'msu'
DEBUG: 00:00:00.3615922 Initializing provider 'msi'
DEBUG: 00:00:00.3617934 Initializing provider 'NuGet'
DEBUG: 00:00:00.3995587 Provider 'zipfile' Initialized
DEBUG: 00:00:00.3995946 Using Archiver Provider zipfile
DEBUG: 00:00:00.4029037 Provider 'WebDownloader' Initialized
DEBUG: 00:00:00.4029362 Using Downloader Provider WebDownloader
DEBUG: 00:00:00.4036450 Initialize Bootstrapper
DEBUG: 00:00:00.4114923 Calling 'msu::InitializeProvider'
DEBUG: 00:00:00.4115243 Provider 'msu' Initialized
DEBUG: 00:00:00.4115437 Using Package Provider msu
DEBUG: 00:00:00.4110385 Provider 'Bootstrap' Initialized
DEBUG: 00:00:00.4115995 Using Package Provider Bootstrap
DEBUG: 00:00:00.4116610 Calling 'msi::InitializeProvider'
DEBUG: 00:00:00.4116804 Provider 'msi' Initialized
DEBUG: 00:00:00.4116930 Using Package Provider msi
DEBUG: 00:00:00.4118225 Calling 'Programs::InitializeProvider'
DEBUG: 00:00:00.4118409 Provider 'Programs' Initialized
DEBUG: 00:00:00.4118545 Using Package Provider Programs
DEBUG: 00:00:00.4123612 Calling 'NuGet'::'InitializeProvider'.
DEBUG: 00:00:00.4123936 Provider 'NuGet' Initialized
DEBUG: 00:00:00.4124121 Using Package Provider NuGet
DEBUG: 00:00:00.4289008 Calling 'WebDownloader::GetFeatures' 
DEBUG: 00:00:00.4289207 Calling 'msu::GetFeatures' 
DEBUG: 00:00:00.4289793 Calling 'zipfile::GetFeatures' 
DEBUG: 00:00:00.4295316 Calling 'msi::GetFeatures' 
DEBUG: 00:00:00.4296145 Calling 'Bootstrap::GetFeatures'
DEBUG: 00:00:00.4298511 Calling 'NuGet'::'GetFeatures'.
DEBUG: 00:00:00.4310419 The provider 'msu' is imported
DEBUG: 00:00:00.4310904 The provider 'NuGet' is imported
DEBUG: 00:00:00.4310952 The provider 'msi' is imported
DEBUG: 00:00:00.4311088 The provider 'Bootstrap' is imported
DEBUG: 00:00:00.4319966 Calling 'Programs::GetFeatures' 
DEBUG: 00:00:00.4320460 The provider 'Programs' is imported
DEBUG: 00:00:00.4326535 SUCCESS provider assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr
\Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.4330041 SUCCESS provider assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr
\Microsoft.PackageManagement.MsuProvider.dll
DEBUG: 00:00:00.4333376 SUCCESS provider assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr
\Microsoft.PackageManagement.MsiProvider.dll
DEBUG: 00:00:00.4337750 SUCCESS provider assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr
\Microsoft.PackageManagement.NuGetProvider.dll
DEBUG: 00:00:00.4337871 SUCCESS provider assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr
\Microsoft.PackageManagement.CoreProviders.dll
DEBUG: 00:00:00.4893396 Calling 'WebDownloader::DownloadFile' 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409','C:\Users\erik.mathijsen\AppData\Local\Temp\Mic
rosoft.PackageManagement\b11jxro5.qjb','40000','False'
DEBUG: 00:00:00.6390729 Trying to register metaprovider
DEBUG: 00:00:00.6683806 Initializing PowerShell MetaProvider
VERBOSE: Cannot download link 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409', retrying for '2' more times.
DEBUG: 00:00:00.7027360 Calling 'WebDownloader::DownloadFile' 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409','C:\Users\erik.mathijsen\AppData\Local\Temp\Mic
rosoft.PackageManagement\b11jxro5.qjb','40000','False'
VERBOSE: Cannot download link 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409', retrying for '1' more times.
DEBUG: 00:00:00.7446710 Calling 'WebDownloader::DownloadFile' 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409','C:\Users\erik.mathijsen\AppData\Local\Temp\Mic
rosoft.PackageManagement\b11jxro5.qjb','40000','False'
VERBOSE: Cannot download link 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409', retrying for '0' more times.
DEBUG: 00:00:00.8395452 Attempting to load PowerShell Provider Module [C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PowerShellG
et\2.1.2\PSModule.psm1]
DEBUG: 00:00:01.0539427 Loaded PowerShell package provider: '[C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PowerShellGet\2.1.2\
PSModule.psm1]'.
DEBUG: 00:00:01.0605575 Loaded PowerShell Provider: PowerShellGet
DEBUG: 00:00:01.0624707 Initializing provider 'PowerShellGet'
DEBUG: 00:00:01.0893488 Calling New() : MethodName = 'InitializeProvider'
DEBUG: 00:00:01.0893779 ErrorAction: SilentlyContinue
DEBUG: 00:00:01.0893856 WarningAction: SilentlyContinue
DEBUG: 00:00:01.0921100 INVOKING PowerShell Fn Initialize-Provider with args  that has length 0
DEBUG: 00:00:01.0939209 Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Microsoft.PackageManagement.Providers.Internal.Bootstrap.Swid.DownloadSwidtag(IEnumerable`1 locations, BootstrapRequest request)
DEBUG: 00:00:01.1005110 In PowerShellGet Provider - 'Initialize-Provider'.
DEBUG: 00:00:01.1007912 PowerShell Script 'PSModule' Function 'Initialize-Provider' returns null.
DEBUG: 00:00:01.1013095 Done calling powershell «Initialize-Provider» «PSModule»
DEBUG: 00:00:01.1013624 Provider 'PowerShellGet' Initialized
DEBUG: 00:00:01.1013740 Using Package Provider PowerShellGet
DEBUG: 00:00:01.1083248 Calling New() : MethodName = 'GetFeatures'
DEBUG: 00:00:01.1083456 ErrorAction: SilentlyContinue
DEBUG: 00:00:01.1083558 WarningAction: SilentlyContinue
DEBUG: 00:00:01.1089779 INVOKING PowerShell Fn Get-Feature with args  that has length 0
DEBUG: 00:00:01.1117944 In PowerShellGet Provider - 'Get-Feature'.
DEBUG: 00:00:01.1161929 Done calling powershell «Get-Feature» «PSModule»
DEBUG: 00:00:01.1163054 The provider 'PowerShellGet' is imported
DEBUG: 00:00:01.1190104 SUCCESS provider assembly: C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PackageManagement\1.3.1\fullclr
\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
DEBUG: 00:00:00.0000004 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0001726 Force: True
DEBUG: 00:00:00.0001895 Debug: True
DEBUG: 00:00:00.0001992 Name: MicrosoftPowerBIMgmt
DEBUG: 00:00:00.0002099 Verbose: True
DEBUG: 00:00:00.0008911 INVOKING PowerShell Fn Get-DynamicOptions with args Provider that has length 1
DEBUG: 00:00:00.0070206 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0167456 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0196484 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0196635 Force: True
DEBUG: 00:00:00.0196722 Debug: True
DEBUG: 00:00:00.0196804 Name: MicrosoftPowerBIMgmt
DEBUG: 00:00:00.0196892 Verbose: True
DEBUG: 00:00:00.0201444 INVOKING PowerShell Fn Get-DynamicOptions with args Source that has length 1
DEBUG: 00:00:00.0207301 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0222623 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0272761 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0272911 Force: True
DEBUG: 00:00:00.0273008 Debug: True
DEBUG: 00:00:00.0273100 Name: MicrosoftPowerBIMgmt
DEBUG: 00:00:00.0273183 Verbose: True
DEBUG: 00:00:00.0278147 INVOKING PowerShell Fn Get-DynamicOptions with args Package that has length 1
DEBUG: 00:00:00.0284499 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0339389 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:00.0359607 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:00.0359747 Force: True
DEBUG: 00:00:00.0359835 Debug: True
DEBUG: 00:00:00.0359922 Name: MicrosoftPowerBIMgmt
DEBUG: 00:00:00.0360004 Verbose: True
DEBUG: 00:00:00.0364203 INVOKING PowerShell Fn Get-DynamicOptions with args Install that has length 1
DEBUG: 00:00:00.0369440 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:00.0392431 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:01.6202084 Calling SearchForPackages. Name='MicrosoftPowerBIMgmt'
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
DEBUG: 00:00:01.6292130 PackageProvider::FindPackage with name MicrosoftPowerBIMgmt
DEBUG: 00:00:01.6296101 Calling SearchForPackages After Select 1
DEBUG: 00:00:01.6524911 Calling New() : MethodName = 'FindPackage'
DEBUG: 00:00:01.6577648 ProviderName: PowerShellGet
DEBUG: 00:00:01.6592470 Type: Module
DEBUG: 00:00:01.6600339 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:01.6613207 Force: True
DEBUG: 00:00:01.6620480 Debug: True
DEBUG: 00:00:01.6630186 Scope: AllUsers
DEBUG: 00:00:01.6638632 Verbose: True
DEBUG: 00:00:01.6645740 Name: MicrosoftPowerBIMgmt
DEBUG: 00:00:01.6656896 INVOKING PowerShell Fn Find-Package with args System.String[], , ,  that has length 4
DEBUG: 00:00:01.7138724 In PowerShellGet Provider - 'Find-Package'.
DEBUG: 00:00:01.7822753 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:01.7835311 OPTION: Type => Module
DEBUG: 00:00:01.7846055 OPTION: MessageResolver => Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:01.7856179 OPTION: Force => True
DEBUG: 00:00:01.7864082 OPTION: Debug => True
DEBUG: 00:00:01.7871835 OPTION: Scope => AllUsers
DEBUG: 00:00:01.7880664 OPTION: Verbose => True
DEBUG: 00:00:01.7888082 OPTION: Name => MicrosoftPowerBIMgmt
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
DEBUG: 00:00:01.8426530 PackageProvider::FindPackage with name MicrosoftPowerBIMgmt
DEBUG: 00:00:01.8575461 Calling 'NuGet'::'FindPackage' - name='MicrosoftPowerBIMgmt', requiredVersion='',minimumVersion='', maximumVersion='''.
DEBUG: 00:00:01.8604378 Iterating 'MicrosoftPowerBIMgmt'.
DEBUG: 00:00:01.8864901 Calling 'NuGetRequest'::'RegisteredPackageSources', 'C:\Users\erik.mathijsen\AppData\Roaming\NuGet\nuget.config'.
DEBUG: 00:00:01.8881299 Loading a configuration from file 'C:\Users\erik.mathijsen\AppData\Roaming\NuGet\nuget.config'.
DEBUG: 00:00:01.8922327 Loaded a configuration from file 'C:\Users\erik.mathijsen\AppData\Roaming\NuGet\nuget.config'.
DEBUG: 00:00:01.8948707 There are '0' registered sources in 'NuGet' provider.
DEBUG: 00:00:01.8964378 Source 'https://www.powershellgallery.com/api/v2' is not one of the registered sources in 'NuGet' provider.
VERBOSE: An error occurred while sending the request.
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2' for '2' more times
VERBOSE: An error occurred while sending the request.
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2' for '1' more times
VERBOSE: An error occurred while sending the request.
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2' for '0' more times
WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.
VERBOSE: Total package yield:'0' for the specified package 'MicrosoftPowerBIMgmt'.
DEBUG: 00:00:07.1900019 Completed iterating for 'MicrosoftPowerBIMgmt'.
DEBUG: 00:00:07.1966390 PowerShell Script 'PSModule' Function 'Find-Package' returns null.
DEBUG: 00:00:07.1977202 Done calling powershell «Find-Package» «PSModule»
DEBUG: 00:00:07.2025149 unmatched package name='MicrosoftPowerBIMgmt'
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'MicrosoftPowerBIMgmt'. Try Get-PSRepository to see all 
available registered module repositories.
At C:\Users\erik.mathijsen\OneDrive - Ricoh Europe PLC\Documents\WindowsPowerShell\Modules\PowerShellGet\2.1.2\PSModule.psm1:9349 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
 

PS C:\Windows\system32>

**Comment by SydneyhSmith** [comment]
Thanks @ErikMathijsen could you please provide more information including repro steps, and environment information

**Comment by ErikMathijsen** [comment]
Hi Sydney,

The steps are quite simple and are listed in the screen capture as well.


  1.  Open PowerShell as Administrator on my Windows 10 Client
  2.  Connect-MsolService     (we do have mfa enabled)
  3.  Checked version of Security Protocol with [Net.ServicePointManager]::SecurityProtocol        -> Response Tls12
  4.  Tried to Install-Module -name MicrosoftPowerBIMgmt

Further related environment information:

PS C:\Windows\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.858
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.858
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


If you need any other information, then please let me know.

Regards,

Erik Mathijsen
Compliance Manager
ESM Pro
Ricoh EMEA IT


Ricoh Europe PLC
Nieuw Kronenburg
Prof. W. H. Keesomlaan 1,
Amstelveen
1183 DJ
The Netherlands
Postal address: P.O. Box 114, 1180 AC Amstelveen


Tel: +31 205474760
Mobile: +31 6 50601445

erik.mathijsen@ricoh-europe.com<mailto:erik.mathijsen@ricoh-europe.com>
https://ricoheurope.webex.com/meet/emathijsen
www.ricoh-europe.com

<https://www.iengagewithricoh.com/community/it/windows-8.1-project-faq>

[cid:part16.05090702.04070506@idmcomp.com]<http://www.ricoh.co.uk/>

[cid:part18.01050101.09050505@idmcomp.com] <http://www.linkedin.com/company/ricoh-uk/?email-sig>   [cid:part20.07050304.08040900@idmcomp.com]  <https://twitter.com/RicohUK/?email-sig>   [cid:part22.00090303.01070501@idmcomp.com]  <http://www.youtube.com/user/ricohukie/?email-sig>   [cid:part24.08090402.09090201@idmcomp.com]  <http://transform.ricoh.co.uk/?email-sig>

[200803 OSCAR Outlook Footer]

**Comment by SydneyhSmith** [comment]
Thanks for the update @ErikMathijsen ...looks like the screen capture didnt come through on our end 
![image](https://user-images.githubusercontent.com/43417619/107054476-04933680-6785-11eb-971e-d287a229e251.png)

**Comment by ErikMathijsen** [comment]
Hi Sydney,

I see, lets see if this would be better.


PS C:\Windows\system32> $PSVersionTable

Name                                                 Value
----                                                       -----
PSVersion                                          5.1.17134.858
PSEdition                                           Desktop
PSCompatibleVersions                  {1.0, 2.0, 3.0, 4.0...}
BuildVersion                                     10.0.17134.858
CLRVersion                                       4.0.30319.42000
WSManStackVersion                     3.0
PSRemotingProtocolVersion       2.3
SerializationVersion                       1.1.0.1


Regards,


Erik Mathijsen
Compliance Manager
ESM Pro
Ricoh EMEA IT


Ricoh Europe PLC
Nieuw Kronenburg
Prof. W. H. Keesomlaan 1,
Amstelveen
1183 DJ
The Netherlands
Postal address: P.O. Box 114, 1180 AC Amstelveen


Tel: +31 205474760
Mobile: +31 6 50601445

erik.mathijsen@ricoh-europe.com<mailto:erik.mathijsen@ricoh-europe.com>
https://ricoheurope.webex.com/meet/emathijsen
www.ricoh-europe.com

<https://www.iengagewithricoh.com/community/it/windows-8.1-project-faq>

[cid:part16.05090702.04070506@idmcomp.com]<http://www.ricoh.co.uk/>

[cid:part18.01050101.09050505@idmcomp.com] <http://www.linkedin.com/company/ricoh-uk/?email-sig>   [cid:part20.07050304.08040900@idmcomp.com]  <https://twitter.com/RicohUK/?email-sig>   [cid:part22.00090303.01070501@idmcomp.com]  <http://www.youtube.com/user/ricohukie/?email-sig>   [cid:part24.08090402.09090201@idmcomp.com]  <http://transform.ricoh.co.uk/?email-sig>

[200803 OSCAR Outlook Footer]

**Comment by SydneyhSmith** [comment]
Thanks @ErikMathijsen could you please run `Install-Module -name MicrosoftPowerBIMgmt -Verbose -Debug` and provide the output as well as `Get-Module PowerShellGet, PackageManagement -Listavailable` Thanks!

**Comment by ErikMathijsen** [comment]
Hi Sydney,

Ok, so that capture in the original ticket is also not visible.
I’ve attached it to this email.

Regards,


Erik Mathijsen
Compliance Manager
ESM Pro
Ricoh EMEA IT


Ricoh Europe PLC
Nieuw Kronenburg
Prof. W. H. Keesomlaan 1,
Amstelveen
1183 DJ
The Netherlands
Postal address: P.O. Box 114, 1180 AC Amstelveen


Tel: +31 205474760
Mobile: +31 6 50601445

erik.mathijsen@ricoh-europe.com<mailto:erik.mathijsen@ricoh-europe.com>
https://ricoheurope.webex.com/meet/emathijsen
www.ricoh-europe.com

<https://www.iengagewithricoh.com/community/it/windows-8.1-project-faq>

[cid:part16.05090702.04070506@idmcomp.com]<http://www.ricoh.co.uk/>

[cid:part18.01050101.09050505@idmcomp.com] <http://www.linkedin.com/company/ricoh-uk/?email-sig>   [cid:part20.07050304.08040900@idmcomp.com]  <https://twitter.com/RicohUK/?email-sig>   [cid:part22.00090303.01070501@idmcomp.com]  <http://www.youtube.com/user/ricohukie/?email-sig>   [cid:part24.08090402.09090201@idmcomp.com]  <http://transform.ricoh.co.uk/?email-sig>

[200803 OSCAR Outlook Footer]

**Comment by ErikMathijsen** [comment]
Hi Sydney,

I have found the solution, which is described here:

https://www.alitajran.com/unable-to-install-nuget-provider-for-powershell/

Regards,


Erik Mathijsen
Compliance Manager
ESM Pro
Ricoh EMEA IT


Ricoh Europe PLC
Nieuw Kronenburg
Prof. W. H. Keesomlaan 1,
Amstelveen
1183 DJ
The Netherlands
Postal address: P.O. Box 114, 1180 AC Amstelveen

**Comment by SydneyhSmith** [comment]
Thanks @ErikMathijsen for all the detailed information, it sounds like your issue is now resolved, is that correct?

**Comment by ErikMathijsen** [comment]
Hi Sydney,

Yes by setting the registry settings the issue is resolved.

Regards,


Erik Mathijsen
Compliance Manager
ESM Pro
Ricoh EMEA IT


Ricoh Europe PLC
Nieuw Kronenburg
Prof. W. H. Keesomlaan 1,
Amstelveen
1183 DJ
The Netherlands
Postal address: P.O. Box 114, 1180 AC Amstelveen


Tel: +31 205474760
Mobile: +31 6 50601445

erik.mathijsen@ricoh-europe.com<mailto:erik.mathijsen@ricoh-europe.com>
https://ricoheurope.webex.com/meet/emathijsen
www.ricoh-europe.com

<https://www.iengagewithricoh.com/community/it/windows-8.1-project-faq>

[cid:part16.05090702.04070506@idmcomp.com]<http://www.ricoh.co.uk/>

[cid:part18.01050101.09050505@idmcomp.com] <http://www.linkedin.com/company/ricoh-uk/?email-sig>   [cid:part20.07050304.08040900@idmcomp.com]  <https://twitter.com/RicohUK/?email-sig>   [cid:part22.00090303.01070501@idmcomp.com]  <http://www.youtube.com/user/ricohukie/?email-sig>   [cid:part24.08090402.09090201@idmcomp.com]  <http://transform.ricoh.co.uk/?email-sig>

[200803 OSCAR Outlook Footer]
