### ISSUE TITLE
LICENSE is not recognized by Github as MIT

### ISSUE THREAD

**Issue by xtqqczze** [PowerShell/PowerShellGetv2#680]
See also: PowerShell/PowerShell#12729

**Comment by alerickson** [comment]
HI @xtqqczze do you mean the PowerShellGet license is not recognized by GitHub as an MIT license?

**Comment by xtqqczze** [comment]
> HI @xtqqczze do you mean the PowerShellGet license is not recognized by GitHub as an MIT license?

Yes, the license in the following file:
https://github.com/PowerShell/PowerShellGetv2/blob/master/LICENSE

Compare to the following file, which is recognized:
https://github.com/PowerShell/PowerShell/blob/master/LICENSE.txt

**Comment by anamnavi** [comment]
@xtqqczze thanks for pointing this out, this is resolved now.
