### ISSUE TITLE
Properties of AdditionalMetadata are case-sensitive

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShellGetv2#7]
The Microsoft.PowerShell.Commands.PSRepositoryItemInfo has an AdditionalMetadata property that contains a hash table of properties and values. The hash table keys are case sensitive.

```
PS C:\Program Files\PowerShell\6.0.0.10> (find-module pester).additionalMetadata.downloadCount
21670
PS C:\Program Files\PowerShell\6.0.0.10> (find-module pester).Additionalmetadata.DOWNloadcount
PS C:\Program Files\PowerShell\6.0.0.10>

PS C:\Program Files\PowerShell\6.0.0.10> (get-installedmodule pscx).additionalMetadata.published
6/30/2016 4:18:25 AM
PS C:\Program Files\PowerShell\6.0.0.10> (get-installedmodule pscx).additionalMetadata.PUBLISHED
PS C:\Program Files\PowerShell\6.0.0.10>
```

I think this is because the source is XML, which is case-sensitive, but I haven't had time to verify.

**Comment by kilasuit** [comment]
Root cause is likely due to this issue that was raised in PoshCode StyleGuide repo https://github.com/PoshCode/PowerShellPracticeAndStyle/issues/60
