### ISSUE TITLE
SourceLocation and ScriptSourceLocation must be different URI's

### ISSUE THREAD

**Issue by dotps1** [PowerShell/PowerShellGetv2#76]
## Expected Behavior

Right now you you cannot set the SourceLocation (modules) and the ScriptSourceLocation (scripts) to the same URI/Feed with Register/Set-PSRepository, and I'm not sure why.  I have a ProGet Server set up in house, with two NuGet feeds, one hosting modules, one hosting scripts.  But, if a script requires a module in the module feed, how is it supposed to find that?  The setup for the PSGallery seems like it was sort of hacked together to overcome this:
```
PS C:\> Get-PSRepository PSGallery | select *


Name                      : PSGallery
SourceLocation            : https://www.powershellgallery.com/api/v2/
Trusted                   : False
Registered                : True
InstallationPolicy        : Untrusted
PackageManagementProvider : NuGet
PublishLocation           : https://www.powershellgallery.com/api/v2/package/
ScriptSourceLocation      : https://www.powershellgallery.com/api/v2/items/psscript/
ScriptPublishLocation     : https://www.powershellgallery.com/api/v2/package/
ProviderOptions           : {}
```

## Current Behavior

an error gets thrown if you the same URI's are used:

> PackageManagement\Set-PackageSource : SourceLocation 'https://server/nuget/powershell/' and ScriptSourceLocation 'https://server/nuget/powershell/' should not be 
same for URI based repositories.

## Possible Solution

Allow the same URI to be used, maybe have `module` and `script` tags?  I'm not sure why this isn't allowed now.

## Steps to Reproduce (for bugs)

1. use the `Register-PSRepository` or `Set-PSRepository` and set the `-SourceLocation` and the `-ScriptSourceLocation` to the same URI.

## Context

depending on the NuGet feed provider I'm using, it either won't install the script because it cannot find the module from the #Requires statement, or it will install it, with no mention that the required modules are missing (I feel like it used to give a warning when this was the case, but it no longer does).

## Your Environment

```PowerShell

> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
> Get-Module
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.1.1.0    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvider...}
Script     0.6.1.2... posh-git                            {Add-SshKey, Enable-GitColors, Get-AliasPattern, Get-GitDirectory...}
Script     1.1.2.0    PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability...}
Script     1.2        PSReadline                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PSReadlineKeyHand...
> Get-Module -ListAvailable PowerShellGet,PackageManagement
Script     1.1.1.0    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}
Script     1.1.2.0    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
> Get-PackageProvider
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
NuGet                    2.8.5.208        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, All... PowerShellGet            1.1.2.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, ... Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent
> Get-PackageProvider -ListAvailable
Name                     Version          DynamicOptions
----                     -------          --------------
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
nuget                    2.8.5.207
NuGet                    2.8.5.208        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, All... PowerShellGet            1.1.2.0          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, ... PowerShellGet            1.0.0.1
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent
```

**Comment by dotps1** [comment]
I notice when you do `New-ScriptFileInfo` there is
```
.EXTERNALMODULEDEPENDENCIES 
.REQUIREDSCRIPTS 
.EXTERNALSCRIPTDEPENDENCIES
```
but no `.REQUIREDMODULES` metadata attribute.  Maybe for a solution, that could be included, and the when `Install-Script` is used, it can look at that metadata field, and it would look at the `SourceLocation` value from whatever PSRepository was used to install the script.  that would allow you to have an internal repo with 2 feeds, one for scripts and one for modules, and have the required modules be auto installed when needed by a script.

**Comment by dotps1** [comment]
so, any plans on a fix for this?  or a work around?  its getting harder and harder to use PowerShellGet in an internal production environment when you have scripts that count on internal modules.  We either need to have them in the same feed, or have a way to specify alternate feeds in the ScriptInfo as to where the modules are located.

**Comment by bmanikm** [comment]
@dotps1 
Using the same web-based endpoint for both modules and scripts is not a supported scenario. Please feel free to add the required functionality/enhancement in PowerShellGet for your internal production environment.  Please note that adding additional tag based search for web-based repository  for both scripts and modules with different search criteria is not performant.

Workaround 1: Same SMB-based network share path can be used for both modules and scripts.
Workaround 2: If you are not concerned with Find-Module returning the scripts and vice-versa, you can specify the same endpoint for both modules and scripts by 
```powershell
Register-PSRepository -Name MyInternalRepo -SourceLocation https://server/nuget/powershell/api/v2 -ScriptSourceLocation https://server/nuget/powershell/api/v2/
```

**Regarding requiredmodules for scripts**: You need to use -RequiredModules parameter on New-ScriptFileInfo cmdlet to specify the required modules. Required modules will be added as `#Requires -Module ...` in the generated script file.

**Comment by dotps1** [comment]
But you cannot supply the same values from `SourceLocation` and `ScriptSourceLocation` i pasted the error in the original post.  If i could do that,  i would just do that, and set them as the same single NuGet feed.

**Comment by bmanikm** [comment]
Please note the difference in location values with difference in ending '\\'. Which will help you in registering.

**Workaround 3**: Take a look at the test utility function
https://github.com/PowerShell/PowerShellGet/blob/development/Tests/PSGetTestUtils.psm1#L905

**Comment by dotps1** [comment]
i have to ask though, if you can get around the check for using the same URLs with just a trailing `/` then what is the purpose of the check?

**Comment by bmanikm** [comment]
Yes, that is a known issue.
