### ISSUE TITLE
New-FileCatalog -Whatif creates 0-byte .cat file

### ISSUE THREAD

**Issue by ghost** [PowerShell/PowerShellGetv2#89]
Using -Whatif with new-filecatalog creates a 0-byte .CAT file.

## Expected Behavior
Expected behavior is that -Whatif should have no impact on the system, so that removing -Whatif and replaying the command will succeed.

## Current Behavior
Current behavior prevents replaying the command without -Whatif because the 0-byte .Cat file is present.
That file cannot be over-written without adding .Force, so replaying the command fails.

## Possible Solution
No .Cat file should be created if -Whatif is specified. 

## Your Environment

> $PSVersionTable
Name                           Value                                                                           
----                           -----                                                                           
PSVersion                      5.1.14393.693                                                                   
PSEdition                      Desktop                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                         
BuildVersion                   10.0.14393.693                                                                  
CLRVersion                     4.0.30319.42000                                                                 
WSManStackVersion              3.0                                                                             
PSRemotingProtocolVersion      2.3                                                                             
SerializationVersion           1.1.0.1                                                                         

> Get-Command new-filecatalog
Cmdlet: New-FileCatalog        3.0.0.0    
Microsoft.PowerShell.Security

**Comment by bmanikm** [comment]
@JKeithB New-FileCatalog cmdlet is part of PS/PS repo. Please move this issue to PS/PS repo.
