### ISSUE TITLE
PSScriptInfo : the content of the field 'description' do not support the French alphabet

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/PowerShellGetv2#9]
This string :

```
Remplace toutes les occurrences d'un modèle de caractère
```

is converted into :

```
Remplace toutes les occurrences d'un mod�le de caract�re
```

The content of the field 'description' is incorrect : 
https://www.myget.org/feed/ottomatt/package/nuget/Edit-String

The [PSScriptInfo](https://github.com/LaurentDardenne/ProjectTools/blob/master/Edit-String.ps1) datas :

``` Powershell
<#PSScriptInfo
.VERSION 1.3.0
.GUID 9fcc3ac5-5135-4c0c-bed3-f0e8e7aedb84
.AUTHOR Laurent Dardenne
.COMPANYNAME
.COPYRIGHT CopyLeft
.TAGS Replace Regex Template String Edit
.LICENSEURI https://creativecommons.org/licenses/by-nc-sa/4.0
.PROJECTURI https://github.com/LaurentDardenne/ProjectTools
.ICONURI
.EXTERNALMODULEDEPENDENCIES
.REQUIREDSCRIPTS
.EXTERNALSCRIPTDEPENDENCIES
.RELEASENOTES 22 août 2010
.DESCRIPTION  Remplace toutes les occurrences d'un modèle de caractère, défini par une chaîne de caractère simple ou par une expression régulière, par une chaîne de caractères de remplacement.
#> 
```

Windows Seven
Powershell v 5.0.10586.117
PackageManagement 1.1.0.0

**Comment by bmanikm** [comment]
This is happening due to default ANSII encoding of the .nuspec file created using Set-Content cmdlet. We will have to use the Out-File cmdlet to create the .nuspec file during publish operation, here Unicode is the default encoding.

**Comment by LaurentDardenne** [comment]
Thank you.
