### ISSUE TITLE
Unsigned module not triggering publisher check

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShellGetv2#94]
Filed at Mani's request: [https://twitter.com/bmanikm/status/837938902333718528](https://twitter.com/bmanikm/status/837938902333718528)

PowerShellGet: Version 1.1.2.0
PSVersion: 5.1.14393.693

When I install Pester 4.0.2 on a clean VM with Server 2016 RTM in AllUsers scope, I get a catalog signature error. 
```
PS C:\Users\Administrator\Documents> Install-Module Pester -Force -AllowClobber
PackageManagement\Install-Package : The version '4.0.2' of the module 'Pester' being installed is not catalog signed.
Ensure that the version '4.0.2' of the module 'Pester' has the catalog file 'Pester.cat' and signed with the same publisher 'CN=Microsoft Root Certificate Authority 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' as the previously-installed module '4.0.2' with version '3.4.0' under the directory 'C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0'. If you still want to install or update, use -SkipPublisherCheck parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.1.2.0\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],    Exception     + FullyQualifiedErrorId : ModuleIsNotCatalogSigned,Validate-ModuleAuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```
-------------------------
When I install the same module on my dev box with Windows 10 Pro in the CurrentUser or AllUsers scope, I do not get the catalog signature error, although the Verbose text in the transcript notes that that hash doesn't match, it can't find a Pester.cat, and it's not signed by Microsoft. 

I'm sure that I used -SkipPublisherCheck on this machine some module in the past, but I don't recall which module or version.
[PublisherCheck.txt](https://github.com/PowerShell/PowerShellGet/files/818807/PublisherCheck.txt)
[PublisherCheck-AllUsers.txt](https://github.com/PowerShell/PowerShellGet/files/818808/PublisherCheck-AllUsers.txt)
```
VERBOSE: Hash for package 'Pester' does not match hash provided from the server.
VERBOSE: Catalog file 'Pester.cat' is not found in the contents of the module 'Pester' being installed.
VERBOSE: For publisher validation, current module 'Pester' with version '4.0.2' with publisher name ''. Is this module signed by Microsoft: 'False'.
VERBOSE: For publisher validation, using the previously-installed module 'Pester' with version '4.0.2' under 'C:\Users\JuneBlender\Documents\WindowsPowerShell\Modules\Pester\4.0.2' with publisher name ''. Is this module signed by Microsoft: 'False'.
``` 
I'm attaching transcript files for both the CurrentUser and AllUsers installation. If you need anything else, please let me know.

**Comment by bmanikm** [comment]
As per the below verbose message, latest version of Pester module is not signed. So, user has installed an unsigned version.

```powershell
VERBOSE: For publisher validation, using the previously-installed module 'Pester' with version '4.0.2' under 'C:\Users\JuneBlender\Documents\WindowsPowerShell\Modules\Pester\4.0.2' with publisher name ''. Is this module signed by Microsoft: 'False'.
```

Publisher check is applicable only when already installed latest version is signed.

**Comment by juneb** [comment]
Thanks for explaining, Mani. So, SkipPublisherCheck has a persistent effect, even though the switch affects only the command in which it's used.

**Comment by bmanikm** [comment]
Answered in #96.
